### ISSUE TITLE
Sybil Attacker Report 

### ISSUE THREAD

**Issue by manhar2491** [hop-protocol/hop-airdrop#102]
0x567438f48fe463240eb0298da771404045ab4da0
 0xE52895D1566737e8B2e0FeFfb176Da7515269a4D
 0xc9839914b54f793a34959aDF43BECbe13d762780
 0x8fd0b29e67279e69ac8222cecae6094ff3c17564
 0x6315a11391a7db9737124ec79024b638aac4028b
 0x08a3c56bd57aa4f7df5ffc324b8fd8102a482bbf
 0x1d6c03aa03013d3a159c9a25c45e58e0aa9bb067
 0x373e87951a875a926c6690851d3b64069e1fe136

0xc035e68be3fe1ccebe27a5eec9fa1d91e9074f97
 0x91286ce9b4a872b9442bceecd480d4bf1b96c552
 0x5bb779c5a65dd1c53be707bdd31233d683aec520
 0x5b1d17e7c4379d3c75399f57d9f5f76e454669ba
 0x4dc1a14a7965b9393d647491a1281c2d620013f3
 0x9dc34c5bf36141c0b4f9c1b0e89ab3e8084851a7
 0x0bdde7369f7752bb1ee29fc375235035510a830b
 0xd162a301f06f30def5eb394c2ab7ff8d686b52bd
 0x9cdcebc213c14f3f5062a784d1e47bac9359ab18

0xfd09741d3ddb8ddd1c20757f919d8ea4a3008737
 0xcf8e27b103221c841b059bed5140912d52132966
 0xbdea107bb1cbd3337d8c3a17c2390b90c6ad1a9f
 0x7058fa98796fd722471528b9b0ca28cfa1c067cd
 0x1bc7e0cef20c589a13101e2e886b85fb529885a5
 0x89ac7b58ecd219aacf459038cdb00e1c8d16c0dc
 0x2970346bc9ae3bdf23fd3f5f004ff6644f60845b
 0xce781591e029bb18da97af92bb4f051ff1f41d5a
 0xfe237e25b520cb094b98420a26bc76369c6c38ae
 0x532ff84bdc946466693c92d1051e75f0690b2c1f
 0x60450c2f0dc8a9164cae8399283c0f85da76b2c5

0x3246cb8afb6370b61a025941fe53622f8c26a07b
 0x9281d5e1317cf6e02be1f79682213bd066a284ac
 0xb99a69b6329d31f1334b5a6770bc350c2790cd4d
 0xa4603080a69a939d61467c9119de15424cffc2f3
 0x419edc5caa29d9d82d12d56538e48e7a83923c71
 0x47ce63549f82a373ff66d194fd2ab300a01d3e9c
 0xa1f60a89afb4c8efb7a27206db74d560dcc89027
 0x564694cc4c2de51432a9797c359ee71cf4aa56eb
 0x6e8f1d296542945f7d2ae256134240b3702916e6

0x17b83ffa9ddb2fe0e8127ab69fe28b31d7176b97
 0x258678988088dce483e8447d5b9210b3b8a0abcc
 0xe489d7a03b56aba23aa5789eede512b2f0d22f78
 0x97db5d5150eb3ce9b2cc641e5d1644625aecd2e3
 0xf0ec2f42a79848e667b17755c2fe37b6e467c758
 0x091aa7626c870a4ab387b4c32965847033b8e27a
 0x1ad5b0c31531216e9c969b2cd458c786a0609c31
 0x6ab4d88305547e5f62e6138b0b96846f6f0a3660
 0x8e8f34213df20480f74bd2e2859b055a74c93824
 0xa51d217f94289c6c47f2580ddb9549566f3056f3

0x864a0a63f78a2154af847678e4e8228796101991
 0x4f4c9cb014347d263ade692f224b139d5b07ae22
 0x03a1ba34bf95dabd79c035fdfc0942260f0b79f8
 0xfcb47215f65c6df8478d704da4e737fd41f18f46
 0x5afc38ea0b228d9e1cdfa3796c6b2d9253774eb9
 0x25ecaea5299131ee87b51df1bd5feeb9d56dce0c
 0x6349dac9f4ae712e5fcffaa80ff943a0d6fdfc45
 0xdcc047fcaf4629d14b7d672679d8311a1e5cbebc

0x3B92f6DdfB7856b44435bEE215C909CEedE4d03E
 0xc811e0f83ff22a3b777ca15eb785dc834fb3f386
 0x0b84aad27c53cf93148ce952837ccea14bded578
 0xa86f92b240254eb9cf788f2bd64461ed12882c67
 0x114b3ce9d5dbd9a2632cead3709d02ae930a5c12
 0x5322fd6a0145c89f46c7f3049afa5542976abd70
 0xae4e0b6252faada49caf311f4647add0ea090e9f
 0x5a7a4d247903d15a39fb1b5acd3f5af05cd80bbc
 0x1771452912056018243180c60fe7fc19bb3069f1
 0xf2f9ee8d3d53eee3b6b84c8404720c51a4d4b888

0x6a6ec3c0025fa996f0cb34b0a41d412d0575b29d
 0x966810c872588ce702f4a36c4de206932143b793
 0x8fbc48c711aa68699d1c9023bf3ca7c7f0cf0b74
 0x9f1123b79295ec2e866c053a95b91c6d2aef7352
 0xa8b62cf97a6dbecded91a44f9634aac61d133a4f
 0x4e633547c075c53bc921e49d4c26bda57fe7ace9
 0x761c8414657421440cc71926a073493e67f947f9
 0x72d954062aec9af4313cd4aad6302bf08e549c0f
 0x889a653a0f4ce0d8cb4fcb714997bfd1a6752f64
 0x2459b7b9b810e779095984cd7be5a9a9fb647340
 0xc241528de0326403416bba44991012ca26fde5e1
 0x5a0a5e0dd7f2ea29554bfa886609b13e13944d39
 0x8859425a6f152861a01e1199c2adedacd5421837
 0xd78cf9380fe8fefaaed882ed0682a35071ac16b8
 0x8d9e128d193cfec966fd90e6af8a2cfc3987f36d
 0x8d9e128D193cFEc966Fd90e6af8A2CFC3987F36D

Time frame : 128 days proof : 900+matic received transaction
Blockchain : polygon (matic)

all addresses controlled by 1 person , you can check first address received matic transaction (930+ matic ) 
And you can check this transaction then showing another address after clicking on new address in transaction hash , there is again showing matic received transaction from another address , 
![Screenshot_20220507-073925_Telegram](https://user-images.githubusercontent.com/46083591/167233799-9e152dae-a15c-4b99-a701-c0c623fe949d.jpg)

check one by one transaction, this is biggest farmers i think , , i can give you screenshot for easily understand
![Screenshot_20220507-072956_Chrome](https://user-images.githubusercontent.com/46083591/167276375-edc75344-b438-43d2-8bba-f24427855113.jpg)

In first screenshot matic received transaction showing , 128 day 1 hours 

![Screenshot_20220507-072856_Chrome](https://user-images.githubusercontent.com/46083591/167276367-0eef51b2-06fb-471e-a4d1-57130fa1e0e4.jpg)

Again check its matic received transaction from another address , one by one performed all transactions in 128 day 1hours to 3 hours by 1 person

**My reward address for finding this Sybil Attacker**
0xbC0920c838ae3D76D33c93db260eA8bE56413128

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 1 of these addresses is eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
