### ISSUE TITLE
Wrongly flagged as a Sybil Attacker

### ISSUE THREAD

**Issue by Shaneue** [hop-protocol/hop-airdrop#104]
Hi Team. I am not a Sybil Attacker, below is my only address Kindly take a closer look why I am wrongly picked as a Sybil Attacker?

0x28df359ec0a70c354e050c7AbB7f2Cefc517E2E9

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
