### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by HYEONTAEKWOO** [hop-protocol/hop-airdrop#11]
# Related Addresses

0x4CD4B247BdE11887A7662826D5225B9F5729000B
0x4a1685e8Ebbd6F791D343368b54Fa4e2be3DeBFd
0x9032ce9549fCa3E3b04A75255e185eA9324da4FD
0x728A4a4F8310698f6417400C386322B433D24b0D
0xf78899968A12243F5DA0c6a83bC7ce63AC4abDb3
0xF95E9d448a09A7708E00476058752Ff61b2d2A42
0x98A60a279B8F8fFC28d0817813377127c38EE841
0xc42d9Ce4A49f562E8999650e0ef65dff91a1Ac10
0x41259b7C4052aB07d5E23DB71210e8ab862CeDda
0x4Fb06b24Ac4B2D8e540400aA52451a5cdBaDFaF4
0x4EC899e7ae10A9A93b5244d198C5EC173dE80a66
0x6488270124edf61b28fd3d3f2976339f633abf2c
0xc06c66C6096c1FF9545aBb2B8463B8c508859897
0x99ED70868f9641983464CCAaA871d33D98c77431
0xBB3F327fD0864003130B9Eb57344EF047659320E
0xFCEf5b183b460Db114a239C9911C8bE3B2ca7328
0xd83d51A7E07090a266EfE127F3Eaf8AE59a85058
0xE2DeAc58d47b036345f480B4AF9F261807B9C4f1
0x9edFC56775e4Fa92775aec198Ce416Ec503E6433
0xE73D22Bb2469a449a9807702e2d6e1349dC4d944
0x2265888ACf3aFd0a4d487CbF8943F221CD836FD0 -not qualified but linked-
0xF54Db269e2Da6F40E65BC70c3cD935a792D17F10 -not qualified but linked-
0x443370dc32b10Aa8348f293955BCA4f818Ea917d -not qualified but linked-
0x197b5F848C2E22323aC2f8628281DB69C486266A -not qualified but linked-
0x5CCC698267595FE5C8ed5F4B6799aef099455D87 -not qualified but linked-
0x0c2431A5c8Bdeae39586D98E8F2603E8a7f0C93c -not qualified but linked-
0x9cb3ceF0df0E1620b767e2c255DF2145667e40be -not qualified but linked-
0x1719D81A01112Fa95f1dE1D24b63E6694105574d -not qualified but linked-
0x25Fa3966387FFa4b51fED170bCB3C1c32661582D -not qualified but linked-
0xe98d166ab5c022BcB20E46abF976D677d26895D4 -not qualified but linked-
0xA5ba91ce60af8138B2D43610227BFE5A65498341 -not qualified but linked-
0x17898cE3d9BCaFeA6fE02F3D52416eB85EDDE8F7 -not qualified but linked-
0xf639Cf0414A4Cc9A77e00bC54E18d5c19018dbf7 -not qualified but linked-
0x16f1340E531aC93d57f735EE053aE8919A548d38 -not qualified but linked-
0x3b2b2E6183192E3044edA73cD1876D5c1fA35974 -not qualified but linked-
0xe6c7B16f84cF7d6B2Dd443Af818A4452942AA005
0xb6E32142f36643C1fF033BD79Bfe3187b0d13b66
0x7F83a275B2C54E0c97B585B3AD6aCCA93fD59B24
0x1a9A303DD9040960B9E0ed8C6F334c4C4726b4A6
0x68562549bB294CE2d0EAbBFf23849682A4A5400f
0x74f3fdb89EAa78eb61FAB6657f5F2C14DacBF829
0x0Eb96B612E6fd6ab254412f026D32B307EEFeAAC
0x8122f867128beC4068a687f39C9407135feBAc53
0x9b1b76ae25764ED969B685c156E9C5bd05640310
0x2f082154F916a90C6E9C10dba25ABcBDcBbDef7b
0xc116b322e01732848278d4090d946AedcEc9b3f6
0x85F14c9B66A4756D7295Ec4DA034b57cA15B0E40
0xb2126c4A48d7c2eaF1Fc5efA2E20ecc498a3BD2A
0x8Cb059a0f19Fee4bfaeBf1372fccAaD90EAbf17E
0x271Cb1b605bDb172f89797ED274e38A9fE663f8F
0x5D1e9B836C70A0d6546F4d4eb5e4633397C8443c
0x1335Cbd1BCd3080D8ACfeBF747433e3a7681Ae45
0x2767a303b33fC96793b70d0aD336dA2863ca213D
0x3E85De3C8fc0C2CB18f89DFf689b0A638E1A4BA8
0x0607E95c0a88F0af81512b21D8791d99c84dF0ac
0x98C605a26be86D92E00D353E96AA14b6A9096ED3

0x0DE64Ab6D945B1aA28f5868220D09219574f78d2
0x9032ce9549fCa3E3b04A75255e185eA9324da4FD
0xF0949976a6Db8F9d346E23c4423D079eB09F530C
0x8bb2Ea31a8aA0740D7b86f54Db6fA5Af8fb3719b

# Reasoning
it started from 0x4CD4B247BdE11887A7662826D5225B9F5729000B
then sent to 0x4a1685e8Ebbd6F791D343368b54Fa4e2be3DeBFd
from 0x4a wallet, the rest are linked orderly. addresses called ‘0x415565b0’ and other similar transactions then sent to next wallets on polygon on around Dec-26-2021 ~ Dec-29-2021 In the exact same sequence.

# Methodology
I’ve looked into every single wallet in the list herehttps://raw.githubusercontent.com/hop-protocol/hop-airdrop/master/src/data/eligibleAddresses.txt?token=GHSAT0AAAAAABH3XLL7B2HXRO5VHMIYZURSYTUCDMQ
I found 0x4CD4B247BdE11887A7662826D5225B9F5729000B then looked into each wallets orderly. those wallets’ transactions are quite similar and linked.

# Rewards Address
0xb33e018fd80466E46Cb0d52F46eA98105E7B53ec

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only one of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.

**Comment by HYEONTAEKWOO** [comment]
Gm. I don’t understand. I’ve checked all those wallets were on the list before and still can check they are eligible on the hop website(but not on the new list) maybe you guys haven’t updated on that side. thet means there should be someone who filed earlier than me with those addresses because they are on the list and can check on the website but i can’t find anyone earlier than me filed same addresses.

**Comment by shanefontaine** [comment]
Hello @HYEONTAEKWOO . It looks like you are correct. I have reopened this issue and this submission will be reevaluated.

**Comment by shanefontaine** [comment]
Thank you for your report @HYEONTAEKWOO. We have verified that the addresses in this report are Sybil attackers.

The report included 44 eligible addresses as Sybil attackers which means you are eligible for 6954.998103637976685502 HOP!

Please note, you had a duplicate submission for address `0x9032ce9549fCa3E3b04A75255e185eA9324da4FD`.

The qualified addresses are as follows:

```
0x4cd4b247bde11887a7662826d5225b9f5729000b
0x4a1685e8ebbd6f791d343368b54fa4e2be3debfd
0x9032ce9549fca3e3b04a75255e185ea9324da4fd
0x728a4a4f8310698f6417400c386322b433d24b0d
0xf78899968a12243f5da0c6a83bc7ce63ac4abdb3
0xf95e9d448a09a7708e00476058752ff61b2d2a42
0x98a60a279b8f8ffc28d0817813377127c38ee841
0xc42d9ce4a49f562e8999650e0ef65dff91a1ac10
0x41259b7c4052ab07d5e23db71210e8ab862cedda
0x4fb06b24ac4b2d8e540400aa52451a5cdbadfaf4
0x4ec899e7ae10a9a93b5244d198c5ec173de80a66
0x6488270124edf61b28fd3d3f2976339f633abf2c
0xc06c66c6096c1ff9545abb2b8463b8c508859897
0x99ed70868f9641983464ccaaa871d33d98c77431
0xbb3f327fd0864003130b9eb57344ef047659320e
0xfcef5b183b460db114a239c9911c8be3b2ca7328
0xd83d51a7e07090a266efe127f3eaf8ae59a85058
0xe2deac58d47b036345f480b4af9f261807b9c4f1
0x9edfc56775e4fa92775aec198ce416ec503e6433
0xe73d22bb2469a449a9807702e2d6e1349dc4d944
0xe6c7b16f84cf7d6b2dd443af818a4452942aa005
0xb6e32142f36643c1ff033bd79bfe3187b0d13b66
0x7f83a275b2c54e0c97b585b3ad6acca93fd59b24
0x1a9a303dd9040960b9e0ed8c6f334c4c4726b4a6
0x68562549bb294ce2d0eabbff23849682a4a5400f
0x74f3fdb89eaa78eb61fab6657f5f2c14dacbf829
0x0eb96b612e6fd6ab254412f026d32b307eefeaac
0x8122f867128bec4068a687f39c9407135febac53
0x9b1b76ae25764ed969b685c156e9c5bd05640310
0x2f082154f916a90c6e9c10dba25abcbdcbbdef7b
0xc116b322e01732848278d4090d946aedcec9b3f6
0x85f14c9b66a4756d7295ec4da034b57ca15b0e40
0xb2126c4a48d7c2eaf1fc5efa2e20ecc498a3bd2a
0x8cb059a0f19fee4bfaebf1372fccaad90eabf17e
0x271cb1b605bdb172f89797ed274e38a9fe663f8f
0x5d1e9b836c70a0d6546f4d4eb5e4633397c8443c
0x1335cbd1bcd3080d8acfebf747433e3a7681ae45
0x2767a303b33fc96793b70d0ad336da2863ca213d
0x3e85de3c8fc0c2cb18f89dff689b0a638e1a4ba8
0x0607e95c0a88f0af81512b21d8791d99c84df0ac
0x98c605a26be86d92e00d353e96aa14b6a9096ed3
0x0de64ab6d945b1aa28f5868220d09219574f78d2
0xf0949976a6db8f9d346e23c4423d079eb09f530c
0x8bb2ea31a8aa0740d7b86f54db6fa5af8fb3719b
```
