### ISSUE TITLE
Why mark me as a Sybil Attacker ?

### ISSUE THREAD

**Issue by midKingKing** [hop-protocol/hop-airdrop#114]
I'm supprised that i was marked as a Sybil Attacker ,  there must be some wrong with you guys,  I'm a truly user, not an airdrop hunter!!!!  Here is my only address: 0x123743121254cbC9A33bde9221e8bb5B4742550E, and i expected your feedback.

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
