### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by r4bbit2015** [hop-protocol/hop-airdrop#118]
# Related Addresses
Group-1
```
0xe04a49782638ccf21c5467d597b8ef24025ebdac
0xc99afb81244dc923286a7d57d9147856749b45c2
0x86f23dccc544e6d63dfe1a6bf53ed71ead683488
0xf929d7ae1e38a177f691bc501ac10f934dff5d44
0x7ea9ce758918d6650de8e3f512384d31002ac343
0x42d447d14d0846173347262e27af02c2b2b3393e
0x0539a0465ef282e76d05b9b73992bff8cb23ecb7
0x38186638b33919059d1821f75b736f42c66e6608
0x549f9d80a8896b4ad6896501d148d8d49f4c8172
0x2340e85f921f3bdc3d1935aa168b9a0c8f54934f

```
Group-2
```
0x0c4ab94e9b135a72f4968fb9854dd8cfdfabdafc （main address)
0x9be5ac4a7b360c83ad038a0e04b684cb8b82621a (sub address)
0x3344e8838c93561608c9218156713c30280d176a (sub address)
0x811ce9a522195d9172048183b4d0a9593c8b684b （sub address)
0xf5306cfb28d1fe8961ca539248ecb364cfcc5c2c (sub address)
```

Group-3
```
0x99bc322353b1dc913aff540ba200d6b10ed82426 （main address)
0x27dcb0b6630982381ab1c7699af2d8f72c19c73b (sub address)
0xa618d7d5b58835fd26f9b22fc29130e6cde59fc8 （sub address)
```
Group-4
```
0x1e86a644042139f989d4011abf41a71883fe8a4b
0xb9d7ea26c5d0cf3c8aafb5158ead7602572c5dad
0x921c5f12bde84e04b8d6849304615a83c194d0f8
0xcd844407e10c8f059d497eff065c0580b32c0092
0xbe8b61bfa8790be6c3ec7d0fa0885ec7bdb8544a
0x0f58ac80cf47b483cc41348477c7deea9a203e12
0x91aec548a258ee6486c41df0baf42b9232e4d794
0x658257857a5cfb099d19119c0b2fb5163b5ef538
0xd8a7c9896316c6d8ce5f26d140a468c3db5dabcb
0x7d9b4127d2d38080dd858e94d8857ca2ad7e82f6
0xe7345c7828c9badfd98f7f1444536a81c62aff8d
0x6e7fb1f25f7b480baf41f84eceab50131fa9a0ed
0x09dbe5c087e756afb87e82f0e8576844b55a05f2
0xe769d48dcf1daaf817fdfc2999681e14541407ab
0x2b99255d9b0016ce8b6b2aeda3d16f6c3791fd2e
0x0a63a9e8efe766e20f27f458ac7a18da7357ee43
0xd2e73677750699021262d3a93f13074f9147487b
0xfa3ebf673e0338bc0a19594ed73579f987abc0a6
0x36a4a144c23b0eafcdf6a986af4127b0ee2f0a43
0x91b362d63c60954b1fde22f70fdaba5a20a4626c
0xf5362275daf726a3128912cf6d61830daf77d576
0x61f3d318c010c1b01c1ec3ddc81d83d55e98baa8
0x2f641d68a8422305c37980b41e44646644dbd4b4
0xeb17e5bb40007e67a5a738cca871a59cf858b7e8
0xbb11dcbc251e7c5ddb70f856d027e9706c0f179a
0xe7195c18902481bc8808b0fcb885bd3567682100
0xb6ee636d3c8e98eb005fc51ec31959e9b60c25d6
0xc96866a7f1d0d32ddfc1d78f9b906da0f19f8e3c
0x822fca5faa70bffb20d6b23665947fc8b7b6fdc2
0xe48f6c103a74f38bff91d5621ef688de3a391e02
0x4aa4a47b364aa582782a33293c04c3f34ed0e15a
0x41b7c6be6a14e7d88f8a2057127c1843fbf389d6
0x955b2ebe91ef5ba5c0f54aaf1a9f0eea46149ca9
0x985c28dc50c44e9199dd232874f6d59add02fa55
0x14d3435f6183d1b981a0992500b79033459ae4fb
0x18b8139de623972ad0398b5127e456cc145dd1bf
0x7ec0057b5841cd7088f208da0f60414375406dfa
0x8898f09d0e2c1d40b20a84624316e7edac3813dd
0x79c66ba834964c11abeba2fcaad881244e55f470
0x5599b317366e954115b1cb83e29d80663c82d5c3
0xd64de22168a08e5f491880357ed036dae437722f
0x90f22eafe4b2751e6bd690f2256b4347ef0d803c
0x0bb67cbb57b4f4f689bd2dec0a2303f5319e9d0c
0x35bd8d8a74bc00f3ebbc19226441bf7c04e3ddc0
0x5131915240dc5b3be3ce7d860437b06672962ee8
0x37519f50f3b0f45e64ecd60cead777ff13c73c9b
0xe28f92f2c76b7d60803752833d670ee3d652964c
0x4696c14a7cac6a979f4bc27f049b2319d1a7229b
0x4e6e987153ad35ad7e43a77884c294459ac41bb0
0x690796a6ed48e3e5b5cf19d34f79285750ab7bc9
```
Group-5
```
0xecfc9074bda27d970b6b5b33439ab1d826f90d64
0x3db1b99ebc005ed3425cd2a8b251af6772c3ce6e
0x57fae085bea0a435e860ff94de6ce6d388ebae61
```

Group-6
```
 0x55ed65b72bbf83d068d3e55977d157dc12345678
 0x0e832bf00a3596a09f73ee2417c0d0d8c4aeebf9
 0x56804e4a2976b72fbcb3e8abe53a3c7616ca0da5
 0x6424ff9d34a597699ff3bffb248f915cc112fec6
 0x912efc4f166566a6ae47a78a886a8ac03a031321
 0x69a55b70c6b571895ea4e7593517b4f7a7ba27d3
 0x53a162b47249b9408900daa79d2fe5a882df763d
 0xa513384e37d80900ed8670efa078b7446e201d99
 0x1c9ef07c3b66a41bc0cd18b6e11c5521e2e67a0f
 0x2d55be349f2b599b1185dc61368f72aca3ca2285
 0x13e610380b21d2075008fd4b626b36d9e70c2ddb
 0x133742030386619945b5c937b1294119321d78ca
 0x2de0b8a75cfdb9b149fb451e2080fc6a59e58ab3
 0xd14f8cdcb93d012c774c70ebd0afb4b8bdacc2d6
 0x69420d9ab623255ef8c2289ddc6e4b9529ff639f
 0x88d15351779522cd232f834555cb5b3e9ba69420
 0x1761280155d13a4fd0cdf4a16e88aa5159f92ff0
 0x0000000367ba4371cb48816a1cf2f3902448f1bc
```
Group-7
```
0x033c6728ce67510feae338bb1d2ced699a6a27a4 （main address)
0xf8c0f571e40b0dcc7ce9ab718b6ccd99062aa5ab
0x415c26cbacece7b2499de2c25591be225319b1c0
```
# Reasoning
Group-1
CoinTool: MultiSender
https://etherscan.io/tx/0x79df5ef0e32aa92042690493420d52011428e858ba566239c092411ff3d6e830
Bulk use tools to send small amounts of ETH, then use hop protocol
Obvious Sybil Attacker 

Group-2
Subaddress funding is provided by the primary address，The subaddress started trading with the cross-link bridge as soon as it received the funds, and then never traded again after 180 days
[Transaction History Transaction amount Transaction Time All the same]
https://etherscan.io/address/0x9be5ac4a7b360c83ad038a0e04b684cb8b82621a
https://etherscan.io/address/0x3344e8838c93561608c9218156713c30280d176a
https://etherscan.io/address/0x811ce9a522195d9172048183b4d0a9593c8b684b
https://etherscan.io/address/0xf5306cfb28d1fe8961ca539248ecb364cfcc5c2c

Group-3
Same operation as Group-2，There are only a few transaction records for subaddresses, all of which are about Hop Protocol，Funds from the main address。
https://etherscan.io/address/0xa618d7d5b58835fd26f9b22fc29130e6cde59fc8
https://etherscan.io/address/0x27dcb0b6630982381ab1c7699af2d8f72c19c73b

Group-4
Same operation as Group-1
https://etherscan.io/tx/0x8017d2219261450144c69d3c9acc1ce8f9c2ac9ca519d81e734c76e0418d6c4e

Group-5
Same operation as Group-1  Disperse.app
https://etherscan.io/tx/0x44282b9a38228330dfbf1c2de5ea6f4103add5d9482b1c47f832b5c69a98dc2a

Group-6
Same operation as Group-1  Disperse.app
https://etherscan.io/tx/0x40ed361c8e50602a573cd368c940726f96b9eb3888e36f0aae6545332d9b7d19

Group-7
Same operation as Group-2

# Methodology

This is based on addresses filtered by the code I wrote and then manually tracked against i these addresses
The first round of screening.
1. whether the first From address is the contract address
2. The transaction record is less than 20
3. ETH interaction is 0 - "because the interaction in other chains, temporarily excluded and abandoned
The second round of screening: (transaction records less than 20 into the second round of screening)
1. Addresses that have interacted with the HOP smart contract
The third round of screening.
1. Addresses with similar number of airdrops (enter the manual traceability)
Fourth round of screening.
1. the first transfer to the same address (1 to many)

This is just a small part of the code, I can provide the whole code if you need it
```

def check_airdrop(address):
    urls = f"https://airdrop-api.hop.exchange/v1/airdrop/{address}"
    res = requests.get(urls)
    data = res.json()
    airdrop_sums = float( data['data']['totalTokens']) / 10 ** 18
    airdrop_sums = f"{airdrop_sums:.2f}"
    # print (data)
    return float(airdrop_sums)

def main():
    airdrop_dict = {}
    address_lists = read_address("de-from-exchange.txt")
    count = 1
    for address in address_lists:
        airdrop_nums = str(check_airdrop(address))
        if airdrop_nums in airdrop_dict:
            airdrop_dict[airdrop_nums].append(address)
        else:
            airdrop_dict[airdrop_nums] = [address]
        print(f"{address} {check_airdrop(address)}")
        print(airdrop_dict)
        count = count + 1
```

# Rewards Address

Example:
Update moved to 178
#178

**Comment by rotate-eth** [comment]
Additional evidence for Group 4 is that the addresses follow similar bridging behaviour (Hop Ethereum > Optimism, then Hop Optimism > Polygon) with near identical volume, number of transactions, and are executed sequentially with roughly a minute between the timestamps.

```
address | totalTxs | totalVolume | timestamp | diff (seconds)
-- | -- | -- | -- | --
0x1e86a644042139f989d4011abf41a71883fe8a4b | 2 | 8244.56 | 1.6E+09 | NaN
0xb9d7ea26c5d0cf3c8aafb5158ead7602572c5dad | 2 | 8244.53 | 1.6E+09 | 23
0x921c5f12bde84e04b8d6849304615a83c194d0f8 | 2 | 8244.49 | 1.6E+09 | 44
0xcd844407e10c8f059d497eff065c0580b32c0092 | 2 | 8244.45 | 1.6E+09 | 42
0xbe8b61bfa8790be6c3ec7d0fa0885ec7bdb8544a | 2 | 8244.41 | 1.6E+09 | 55
0x0f58ac80cf47b483cc41348477c7deea9a203e12 | 2 | 8244.37 | 1.6E+09 | 76
0x91aec548a258ee6486c41df0baf42b9232e4d794 | 2 | 8244.33 | 1.6E+09 | 9
0x658257857a5cfb099d19119c0b2fb5163b5ef538 | 2 | 8244.29 | 1.6E+09 | 71
0xd8a7c9896316c6d8ce5f26d140a468c3db5dabcb | 2 | 8244.25 | 1.6E+09 | 43
0x7d9b4127d2d38080dd858e94d8857ca2ad7e82f6 | 2 | 8244.22 | 1.6E+09 | 42
0xe7345c7828c9badfd98f7f1444536a81c62aff8d | 2 | 8244.19 | 1.6E+09 | 82
0x6e7fb1f25f7b480baf41f84eceab50131fa9a0ed | 2 | 8244.15 | 1.6E+09 | 12
```

**Comment by r4bbit2015** [comment]
> 



> Additional evidence for Group 4 is that the addresses follow similar bridging behaviour (Hop Ethereum > Optimism, then Hop Optimism > Polygon) with near identical volume, number of transactions, and are executed sequentially with roughly a minute between the timestamps.
> 
> ```
> address | totalTxs | totalVolume | timestamp | diff
> -- | -- | -- | -- | --
> 0x1e86a644042139f989d4011abf41a71883fe8a4b | 2 | 8244.56 | 1638443313 | NaN
> 0xb9d7ea26c5d0cf3c8aafb5158ead7602572c5dad | 2 | 8244.53 | 1638443336 | 23
> 0x921c5f12bde84e04b8d6849304615a83c194d0f8 | 2 | 8244.49 | 1638443380 | 44
> 0xcd844407e10c8f059d497eff065c0580b32c0092 | 2 | 8244.45 | 1638443422 | 42
> 0xbe8b61bfa8790be6c3ec7d0fa0885ec7bdb8544a | 2 | 8244.41 | 1638443477 | 55
> 0x0f58ac80cf47b483cc41348477c7deea9a203e12 | 2 | 8244.37 | 1638443553 | 76
> 0x91aec548a258ee6486c41df0baf42b9232e4d794 | 2 | 8244.33 | 1638443562 | 9
> 0x658257857a5cfb099d19119c0b2fb5163b5ef538 | 2 | 8244.29 | 1638443633 | 71
> 0xd8a7c9896316c6d8ce5f26d140a468c3db5dabcb | 2 | 8244.25 | 1638443676 | 43
> 0x7d9b4127d2d38080dd858e94d8857ca2ad7e82f6 | 2 | 8244.22 | 1638443718 | 42
> 0xe7345c7828c9badfd98f7f1444536a81c62aff8d | 2 | 8244.19 | 1638443800 | 82
> 0x6e7fb1f25f7b480baf41f84eceab50131fa9a0ed | 2 | 8244.15 | 1638443812 | 12
> ```

你非常聪明

**Comment by shanefontaine** [comment]
Thank you for your submission.

Unfortunately, the submission must have [20 _related_, eligibile addresses](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc). If possible, please consider resubmitting individual issues for each batch if it consists of 20 or more addresses.

**Comment by shanefontaine** [comment]
Thank you for your submission @r4bbit2015 .

Groups 1,4, and 6 were considered because they have 10 more more addresses in each group. However, there are only 1, 0, and 0 eligible addresses in each group, respectively. 

Because of this, I will now close this issue.
