### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by fml-fyl-fol** [hop-protocol/hop-airdrop#12]
# Related Addresses
0x01f95f5d003b36cf396ae52d011e8e466e648a5b
0x02749940a45e2922bd3c25e0be16d1d1d175181e
0x02831b77313afb6acabfe1cb338c5ee7c4e06c7a
0x0390c41c14ffa9ea4ffb4f923a3717140458d196
0x048c782053b50f37d1fa6ed37da77f80fd02e69b
0x053ec8210eea3ed7c78b74ff527381f65225f7e2
0x071c03be86e230c7d0793112f45a2bb461c18b84
0x07b6f1b22fc442ffc60ad372782a34a0d559ce3b
0x087a8c57d558d370caa8c0b8db06a31883a75fd9
0x0b208b54fd6ee6b577cc53538645b53e5b36e435
0x0c1d82af11be125f1b9167d9cdc2830c0647bda2
0x0c4c6f4ee77c7071422319d0dbae2eb17ff8d4ea
0x0c5d4a8a5f199b6c9f9ee87f861a707a2516bf4c
0x0ce9b885435aba8e3fb2bbeab99d07140abf34ff
0x0d4d894cafbb7f587794110ff7994d5ccb987f78
0x11b0576760c2842504dd7c1057a97937ead7ac89
0x11e0a0ea9580b1e26d02d1908b23b22bd7a288b2
0x13b3603b863e955eca54c89c9bfa9cbcaaf15cb0
0x15e9bf34e3ade881fa18047ef1ae1d7a024d9519
0x1695f7a587d7dcd94705e2cf43a4b271695eaa9c
0x18c5c48df0d30ab9b0fb6d8f1617ee62cd82cba2
0x19e9364b3344df19a528077f356190029389e6fa
0x1c67dcb97e6a832cbb3abe9bba71505353fbc610
0x21dd6a115b0dfbb0850fe736260e079bf51ae18f
0x2530b0356c222260fb335d24167ad11ebc61e16e
0x26a8584948412a7f2c4939668c65354700f1da38
0x296ae915e6396217cac7b30daa0e06b8d34a2154
0x2a86859ada559ebd336ddecb35f6621835cc4422
0x2af013fbf0e23ca466f8c4a5a579f293c8b7ec3e
0x2b7f3cd79b15bfe6c247b88e711496e52ba84839
0x2d671a75fd62828bba6b36d60e2699c37cfd3ef0
0x32ef859719dc8b4267c97ace1f2ebd889fac08e1
0x36b0a292706425b0c973476adf3f318e1478d21f
0x3e5d94a7a33a99643d9ca2290bfac38bfc08bb1a
0x413e2de16aded892da1580a07242c952ea24ce5e
0x43ac66990ba634a08e8af7ec28b55fe789dddb96
0x43b2d8b81d90c8f37e257853aaef6dc302542c5e
0x4597fbc7502aeb6d8fb25bef7da8f0f296a4ea43
0x463232b1aecb2b7a2c29ddfa41c188d5a8276b9c
0x4d0fa262a958f0d643325b2b6e2a64be84e4da2b
0x57f9ae3a8200a189b6fdae54e55a1f9a95af2614
0x5c3102482a8ec00bd37b7dd70a0167eeece3c136
0x5cc9651107c2e8a6c235e409d8889af4302a6751
0x5e73afcc5909f5f274bfb49b2f5ce372ceefb1c8
0x64e396c65c6496d6325e700380f52f0fd5adf8a4
0x6515668efda3faa3f5a3919aec17c00c3b0150c7
0x6ff54d88401e2599e8f405b0055709db9b8337ca
0x70b09fdffe2ce8f8e84c85a74ec5d43eb90233f3
0x7261aa48f4f71d57063604a045e93bba8538d863
0x73a236ce8193adadfe5cce4c6412b71c858dd184
0x757c3b7407bc766ee8176a0055d5c4974fcb87b8
0x77a459e34b95337dda7cf201349a2976cd2d08f4
0x79dcd71cb757dbe10b727b42f955378250077ba6
0x7e75c9ba64f6746b492eac0490f46e8587e91c27
0x81ff507101c7101b562656786632d656aaee0bcb
0x8504fe36f554f67be1ff1d01ef3658c5247e3ee3
0x85b31310906ffca7e33b9372d787331c74af38db
0x862278ec94cefcea6a529f54343acc595bc447e6
0x8cc7d6bffa6ab718a8c00377ab01d591856c4f0f
0x8e3404b99513f2880b5e46d7951d5cccb6f5b687
0x8f296ebfa2b94aa59ab72557300f6f4026018d1b
0x8fb1b389d7fa9cd10caa5271aac3895cec120021
0x8fc21347669362cd03e1c3eb32adee96520ab700
0x911502d69b4308901477f34abc257013f19e2c81
0x950f6f4b1013758fa1febaff7175878a9b2a3ab0
0x9d3e430619d1b0d65b8bc9c4b8cfb67f70e9d5db
0x9d5431bc7b899e5bc3553b1f2b0fa9771d3c02a7
0x9d9393ece18f6e117de900a19a4704de0184c339
0x9f1e7a8cb2846bd10395be85d478d97938237e5a
0xa0c4a416b0bf4ced13a367877abb7c36ef09ae21
0xa19a75e842b0d3108bb550d4172c3552e6aa69a6
0xa3746baa8b040ff5bf3b74144e251b567158541f
0xa4e7340cb6a69cea75c0336853aad5bacf84e1e7
0xab3420324b56d7032dbe11a29b95111e62419aa0
0xafbd59afcb2a758338e34867a86abf1e83a8d4ee
0xb086be92130a7947dbec5635a1a0b2523870dbe2
0xb14edb6f5e66834cc81620c8259b6260921c0a74
0xb3e8bd3a506ead54b2e2b07e6665dc4a3fa92134
0xb6730705644f2fe50825879342164cee57cf2d96
0xc168aa12e05e82c01d53a8a92bc5965e0014e39b
0xc175a47e3f288c4dca98e6b6accb714a2a4123cb
0xc8823eeab75afed3ce0efa5c7b330177e3bc6691
0xc9793cddd34af8f1baa08cb10e430a4c381e7b40
0xcfbce4a6273a79d353fb01ba88e815fcadd615b9
0xcff2ae88c99ffcc83f7fc623cc9baab8091710f9
0xd1239a67b469c3dce5eab7c723b6ad5812282ba8
0xda24c3f948a7d1e1a4b82762494bac3693d962b0
0xde48bc3cef066bbea6ce0ade056de860a93344c2
0xe01b273e69e943462dd017e4848f942660cdf2b4
0xe84b80b7d1f6353f70fb5f6d11b351957b365314
0xe86c6688346d74f31f37365cf8827bab29495725
0xe8be75369abb81799952dedb9a48590f1c457c8d
0xea27b7eb5a69b2ccff00c560291c38cfc9aad64d
0xec6af661b1638fd3a97ffbb84a0b42cfef3c6247
0xef2b89e8c1f60231dc257812cc4267c78595cc25
0xf0d55cc171ce4fd8cb26305619da8acf8ce1b974
0xf81c07a3d8d5012bceaa8f4a5f596095423a4399
0xf896d73c7c864f62b1e214b2036ecc45852743f1
0xf8d1fc6bad70cf7e8a85f17479e8f77dcc4cc8cb
0xfbfc7387423848dee1ab8db800ba481956504dfd
0xfe0e3cbc13b7f4ded638ea774b0224c0a72c784c
0xbcc264edc95752a14211a416c409c3bc07ea2d37

# Reasoning

This Address: 0x43ac66990ba634a08e8af7ec28b55fe789dddb96 transfered many usdc to other wallets, and all this "other" wallets used HOP

# Methodology

Around 16 oct 2021 my hop transaction got stuck, so I opened hop explorer, as I wanted to find out why some transactions didn't go through, I looked closely at some transactions and found that many stuck transactions contained coins/tokens that they recieved from the same address, then I sent a colleague the etherscan link in Facebook chat noting that this address was probably hoping for an airdrop

With this etherscan link i wrote a quick and dirty script to compare this wallet transactions & airdop addresses

https://raw.githubusercontent.com/fml-fyl-fol/hop-airdrop/main/quick-and-dirty.js

# Rewards Address

0x6b50f12453108AbB1281739Dc4Cf0A8669EbE8F8

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only one of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
