### ISSUE TITLE
wrongly flaged as a Sybil Attacker

### ISSUE THREAD

**Issue by rochestor** [hop-protocol/hop-airdrop#120]
Hi Team. I am not a Sybil Attacker, 
i only have one address, i have many NFTs ,  IT  IS  NOT A Sybil Attacker
Kindly take a closer look why I am wrongly picked as a Sybil Attacker?

here is my address, it is binded to my  discord handler : rochestor#1448
0xba07e5cb42cA05D2fc3D96514461D7245050eb7B

thank you sir

**Comment by rochestor** [comment]
i admitted that 
0x62D1556564Aca67d7F92c61e1946a02d83255Cb2 
0x4D184E5198ee0b9d646cd450243DaEbEB6b8cc86
0xe6E2E69030c82aFe3dE8E0E5F3d422ACA43879A2
0x896d6845fe202B70805212E372FE29be84682fE3

are also my address.

other address in that group has nothing to do with me. 
I don't want to affect others just because of me.


here is the tx for your reference  https://explorer.hop.exchange/?account=0xba07e5cb42cA05D2fc3D96514461D7245050eb7B

thank you for your work
wish you a happy day

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
