### ISSUE TITLE
Wrongly flagged as a Sybil Attacker - Important Proof

### ISSUE THREAD

**Issue by seofig** [hop-protocol/hop-airdrop#123]
Dear  CEO Of Hop,

Hope you will take it seriously. 

my address:  0xF6a441Db6Ec3666e6A1b1E3c4be411E08ff2067F   > my wallet marked as  Sybil Attacker  
Here my arguments & proof provided. 
my discord:  seofig#6697

# Here i made 18 TX with $200K USD.  
Yes, maximum TX in one months. But not in same day. All in single day, when i need to trade. As a real trader.  I want to know who is the fool to trade as hunter $200K?? airdrop hunter never trade $200K.   If i use hop bridge $10k , i will get 9970-9960?? why one hunter do this??  hunter know $2000-$3000 enough for airdrop eligibility.   You are a block chain specialist , why don't you understand ,i am not Sybil Attacker. 

# Important things: i use this address to trade optimism, I trade around 1M usd trade in optimsm chain. 

please don't do injustice to me. I hope your will solve this issue if you really love real trader.    

# For safety reason , defi trader use multiple wallet for safety purpose. If one wallet got hack, trader will ruined & all will be gone. Safety need always.   multiple wallet need to use for safe fund purpose.   as a developer you know better than me.

# many user use multiple wallet for security purpose, use multiple wallet fund for safe trade. if one people add all fund in one wallet may be in high risk. multiple wallet safe.  

Please solve this issue. my one wallet eligibility will not destroy your token. Will help to get real user .

**Comment by litocoen** [comment]
Hi, Send me an email: litocoen.hop.exchange@protonmail.com

**Comment by litocoen** [comment]
Hi, Thanks for reporting.

Can you send me an email?: litocoen.hop.exchange@protonmail.com

Thank you
