### ISSUE TITLE
Bot receive socail reward!

### ISSUE THREAD

**Issue by nekooei** [hop-protocol/hop-airdrop#127]
MEE6 bot receive airdrop of social reward!

https://github.com/hop-protocol/hop-airdrop/blob/6dacce3913d0c4bedb551f13bcef496d3d41bba7/src/data/social/discord_data.txt#L8

**Comment by miguelmota** [comment]
the mee6 bot will be removed from the final list

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
