### ISSUE TITLE
The address eliminated from airdrop by a mistake

### ISSUE THREAD

**Issue by dannyoceangit** [hop-protocol/hop-airdrop#128]
Please consider the fact that address 0x920C0aB1dCeF3C5A22d7Fa4B3099B922e93Efe9e was included into a groupName 0x74c3b2d22ed5990b9ab1f77bd3054d4fd4afcf96. However there are no relations between them. 
I have only one address 0x920C0aB1dCeF3C5A22d7Fa4B3099B922e93Efe9e, I have provided LP and used bridge and I don't understand how my address is connecte to those all addresses in the group. There might be a mistake in sybil attack detecting algo that led to banning my address.

**Comment by litocoen** [comment]
Shoot me an email: litocoen.hop.exchange@protonmail.com

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
