### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by 0xAlex6** [hop-protocol/hop-airdrop#13]
# Related Addresses

0x7b31eeae3e035926bf11091aaf1fc319a2eb4402 [](https://debank.com/profile/0x7b31eeae3e035926bf11091aaf1fc319a2eb4402)
0x558cc7e8d448f183b53a9225e07edc3a2ca5028d []https://debank.com/profile/0x558cc7e8d448f183b53a9225e07edc3a2ca5028d)
0xaabd4635340c94074049c9c8298dd4bfbc868a5e []https://debank.com/profile/0xaabd4635340c94074049c9c8298dd4bfbc868a5e)
0xfe6d74549bb14b25cd04f46014c24c5bfe9a60e1 []https://debank.com/profile/0xfe6d74549bb14b25cd04f46014c24c5bfe9a60e1)
0x3feef327ad9530b9b4b73ef0bc61cfc13004428f []https://debank.com/profile/0x3feef327ad9530b9b4b73ef0bc61cfc13004428f])
0xd6f5f7353af74416302ee9a6cd15934769c63b3a []https://debank.com/profile/0xd6f5f7353af74416302ee9a6cd15934769c63b3a)
0x73d05eb78a200b1400b882939aab240dfcd6a824 []https://debank.com/profile/0x73d05eb78a200b1400b882939aab240dfcd6a824])
0x0cf690add58dde3daf03c9c9dc08af4f6ff4cec0 []https://debank.com/profile/0x0cf690add58dde3daf03c9c9dc08af4f6ff4cec0)
0xd247ee248eabb4472c6fd9175a2c4bc875bf83c2 []https://debank.com/profile/0xd247ee248eabb4472c6fd9175a2c4bc875bf83c2)
0xcf5d291812668bbbf41dbb794925a5919c88f631 []https://debank.com/profile/0xcf5d291812668bbbf41dbb794925a5919c88f631)
0xd5dfd751e4336261e790110bae6fce0953a669ae []https://debank.com/profile/0xd5dfd751e4336261e790110bae6fce0953a669ae)
0x4940fb2b88dfb4d6a99a143b97252c372958f58e []https://debank.com/profile/0x4940fb2b88dfb4d6a99a143b97252c372958f58e)
0x1084577b94a412ac182434b37d3b07b3319580d5 []https://debank.com/profile/0x1084577b94a412ac182434b37d3b07b3319580d5)
0x0b00ab0a5e1b1e7a88e246a27b8a60e02f063bf9 []https://debank.com/profile/0x0b00ab0a5e1b1e7a88e246a27b8a60e02f063bf9)
0x2c93fadd2bd95cd66b8c33b3636dbaa70c431db4 []https://debank.com/profile/0x2c93fadd2bd95cd66b8c33b3636dbaa70c431db4)
0xfd73d18cf5372084ebe4a6d40f19b88019317f28 []https://debank.com/profile/0xfd73d18cf5372084ebe4a6d40f19b88019317f28)
0xc50f1bf9c9f604af0501f96aa23779b0c2d1a3ca []https://debank.com/profile/0xc50f1bf9c9f604af0501f96aa23779b0c2d1a3ca)
0xb7b3491e7716e9093af8c749957f74f62bced4d6 []https://debank.com/profile/0xb7b3491e7716e9093af8c749957f74f62bced4d6)
0xa34417c1837171910f4d72ad4876a83e9d3103c9 []https://debank.com/profile/0xa34417c1837171910f4d72ad4876a83e9d3103c9)
0xb4ea76d9488ed2e56feb5f803a9733d513cc9027 []https://debank.com/profile/0xb4ea76d9488ed2e56feb5f803a9733d513cc9027])
0xbc093e5bf1e6961f3a0319cec8fc4c52665911d8 []https://debank.com/profile/0xbc093e5bf1e6961f3a0319cec8fc4c52665911d8)
0xd50698b560b12e1bb915768af6a75226ceb25de8 []https://debank.com/profile/0xd50698b560b12e1bb915768af6a75226ceb25de8)
0x776defc2147a9fabd011b8511ebdd8da43ed105e []https://debank.com/profile/0x776defc2147a9fabd011b8511ebdd8da43ed105e)
0xc3ce97eef618f9c6061d70312e8b310fa0dcb81b []https://debank.com/profile/0xc3ce97eef618f9c6061d70312e8b310fa0dcb81b)
0x16a472f0f29ffb72348f7ce6e56e7c9acbd0bba3 []https://debank.com/profile/0x16a472f0f29ffb72348f7ce6e56e7c9acbd0bba3)
0xa98972d02e723d83371e5ff1eac36c980cee0224 []https://debank.com/profile/0xa98972d02e723d83371e5ff1eac36c980cee0224)
0x601ea3fc02c7c28df001c22aeb9c76d6fca3f5b2 [](https://debank.com/profile/0x601ea3fc02c7c28df001c22aeb9c76d6fca3f5b2)
0x278e2ddc31ee9fe61e73b10ee5ce5fbf5a401049 [](https://debank.com/profile/0x278e2ddc31ee9fe61e73b10ee5ce5fbf5a401049)
0xff5ae7f6be86dec4972e39d548dfbb241142bd93 [](https://debank.com/profile/0xff5ae7f6be86dec4972e39d548dfbb241142bd93)
0x62b417e3852913f4964b1ea2b7b191871a91ccab [](https://debank.com/profile/0x62b417e3852913f4964b1ea2b7b191871a91ccab)
0x07bab9184eae3e2ab3a5b487f3206de16448ad64 [](https://debank.com/profile/0x07bab9184eae3e2ab3a5b487f3206de16448ad64)
0xc6c3e4bbcdc719e7b5793a31a36937f729605c33 [](https://debank.com/profile/0xc6c3e4bbcdc719e7b5793a31a36937f729605c33)
0x5b90524b361e3c4a0a8939e618c90318f30c764c [](https://debank.com/profile/0x5b90524b361e3c4a0a8939e618c90318f30c764c)
0x7adb2cfef773aa9422a32d2456bf6fe21f04dad7 [](https://debank.com/profile/0x7adb2cfef773aa9422a32d2456bf6fe21f04dad7)

# Reasoning

All the adresses provide you liquidity with ridiculous amounts (1-10$) on the maximum number of pools possible, and on all Blockchains.

Adresses interact with the same protocols which have airdrops rumours, always with ridiculous amounts (1-10$) (Clipper, TokenSets, Synthetix, Ribbon, Element finance which has already been distributed, 

They also provide ridiculous amount of liquidity to the same AMMs (1-10$) (SushiSwap, Uniswap, QuickSwap, AAVE, Alpaca)

Some of them collect the same NFTs collections and set them as profile picture in DeBank.

They all seekings for new followings on DeBank just to get on return followed back by a ton of followers to grind even more the Social Web3 ranking system in DeBank and so probably get the DeBank airdrop.

They also all have a common point : all those adresses followed me the same day on DeBank, without I add to advertise my adress on social network or whatever.

# Methodology

I checked all the DeBank profiles adresses mentionned upper and see too much similarities between those to think it's not operated by a single person.

# Rewards Address

0x2e9D73745E04A90A83Ba13303705d5534E38F296

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only three of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
