### ISSUE TITLE
Sybil hop report

### ISSUE THREAD

**Issue by arian1757** [hop-protocol/hop-airdrop#130]
# Related Addresses

i sign my wallet with sign word ("HOP_SYBIL_REPORT")

Adress | Signed Message | Signature Hash
-- | -- | --
0x2a88a2243bb7919d4932c38be07ff5870c121531 | HOP_SYBIL_REPORT | 0xd1aa149cb7466d6c6487188c3f82d1c7fef64ec477d30941450cd01e61290ad95184ec826b15e251d109af74f4f97e25f978cd066eaa68869318677cedd520751b
0x4a4cb567201b9bee9c1b7d10116823c2039c53ad | HOP_SYBIL_REPORT | 0x6e24c9cd470eb047dd67347e596a69fd6cf70efbf2cd894cea2a523ca777297d5cb704c40d6a657b544239b72cc6ea568ea92ebd0e59a8c31343997d6c763a451c
0x387b14cC590650a323EC82E54EF8316aB52AcAf5 | HOP_SYBIL_REPORT | 0xb63c11ac931c27cb69ce7dffd5da5c3ff8af592c865c91a48f5af78a3dfb23033aad7b03c84ad47e3d52a34dd3b44f70b1719cdac88e01757b6ba6a1433045061b
0x6D8aE826c8CEAe07DCd2024e2D882C4969E0caA6 | HOP_SYBIL_REPORT | 0x1c855998857fcbb5e1c82a162504fbfffbc3c68fa6def476340ae51eca0be53942a131dec82e35ff6712e9d9df9d28e6dfebd949d9b8dd38efaad1e10c0b0fa51c
0xfE17Bda72632e5E09EB9E4865cb51F1555228D10 | HOP_SYBIL_REPORT | 0x5d7920ffb4e9d905b067d612ada1b4af2555478c1de31ece74ccc1f310a154ac07ed217c9c2351502dc5f0f458f90cfee410ee8560a79a39ebb48ad089ec12381c
0xF0bFDFc73888D15F928d9B391708A2eBCb96d402 | HOP_SYBIL_REPORT | 0xb3faa2c667c3d68110aedfcd2f28faa9aeb13b09c43213c8ed0a655b47b65e8533f127c55bfd2e2849cac032740d0d23bea6e08bedc06ea1853a5ba986b361041c
0x2074Ce70a16C9cB189acDa036383FcE1eC8c8551 | HOP_SYBIL_REPORT | 0x030ffd68c0c61a75a7d852581e579feecacd249bc7eddb1eb648427edec22d35448f610d13f3f5ff4eb243f689a09bbc1e2ae6d8ccd063209476605e6e28f4df1c
0x9DFDFA09AD7a7cBC429851933fd27D5BD69c066f | HOP_SYBIL_REPORT | 0x30e7568aedda23914efe82bf59518a1621038a7c5e499fa6e5e3b52831f3b92e49a5ad1f09d99ddd0e39288a0b001a957f92883087064e9d2e5f9d5c9aaef5861c
0xc70c2425cd07da601e50a6566d1b1d9297849618 | HOP_SYBIL_REPORT | 0x45c8fa682209d2ffab71c2c9e3c89c7bb6fd5d68717bbc9efc5cf3c14b684ac401a0e04c9736a1ba41cb9d7144dfbfecf839bfcacc174b8ffda99aa18b8ec4ab1c
0xa5803b97d4567e9ca1f8a8cef4ce00fd7d57a918 | HOP_SYBIL_REPORT | 0xcdd5e0d8159e977e4765665a500c873a8249f8d6b8ebf6d31ae9220f820597fc17119e547f1a47d2ebac27f432988be2b0c0a4baa8c5b836b55f5dbd200a8d1d1b
0x5e46d461e4601f45b06cee41091a17eb63569f05 | HOP_SYBIL_REPORT | 0x9bd428ebd11da928daa2ac02474c861ca67ead133257e5b6c4ccf594bf12d0246d08e3cf596f92bf7625178f405207c4f59b6aebae689ffc1a485e7b9e69bb9c1c
0xfc61d7dd41c4403d398802bd142a2d8ce06cfca9 | HOP_SYBIL_REPORT | 0x6091422a90bb69fe90b031ff98a995ce832789c5bb50070a7450701e7cb652396ec49bf2f97ab0ae93cb6796b1a2d657a8354a557b99382ad02a753e73aa88e81c
0x9becd9495c4ff275d9ad6076ecb8d6a6e3eb1e2e | HOP_SYBIL_REPORT | 0x932af7618fcf5f03d8f17b0df03616b339d8f9f457c45022664958beaeaa3b066ee365c181ecdc31d934214f793468e1df82a96a7e075c47336602d7bc51b6171b
0xae7bbe9fd7780dc3baf1692de6c392344771da0c | HOP_SYBIL_REPORT | 0x0705d4434b8e5119ec4f36139fd8129ba7bdfe088e88614122915462dd1138c54859caa1cab38b90acc6ba997632894d1544f4d971585f70eeb50394a86063b41b
0x18ea8c03bbd79506032b4b367d816ff6713eb75e | HOP_SYBIL_REPORT | 0x2b8bfb02bf47a90b6a7df0850693838f156d5961647405aa2b13a3ee4b1692fa2f3a424219074d3d3164d524af117c90cf0d60d4826318b28c1a2d6e7bd23bad1b
0x5e5af6ae7c2da0f7e7df4e6c6c199ca0b624d86c | HOP_SYBIL_REPORT | 0xa225ebf323869400d360c01777afec04633adcdb6ddde0c5ad0c311b45faa24068b8c5c6aa8fb834701d0dc143c9ece551b39144cc795cbacd6d9afae3b7b1ae1b
0xcc4a1f6bcbde99fd49c5f4dc183ea8c625ded2f4 | HOP_SYBIL_REPORT | 0xd3cf8aa33d7a427fe1b322f75a6ca8759acb736c186c8a12a893b33c8a19d9d3569e6a19929e85b6477d7d0d00a24f9b6c1373b939a79c3bf7b5796e9dc91c411b
0x28e128546aeb134da356a194f15938ecc35ddf57 | HOP_SYBIL_REPORT | 0xb0faa938f682bc3165fb909bdac94d9f688354f3a7a83851e8146fa5810974a005b640b2ee390d4227c9eff6ca6fd6606011a7dd97d06d1dd428c1c7b7bffd1e1b
0x19f35df783e2b13702ae1e7ad4a6dc98ea085252 | HOP_SYBIL_REPORT | 0xba65551663660b2f643442d3f7fdd74bcec0b8ef7f9bb1c2747efd114c1838d919719941cfd5425269d1f6c90fb205b42334194310c294936ee4f598a386c9981c
0xdc080b5d5fc51d4494f3605857f280bf7349b948 | HOP_SYBIL_REPORT | 0x253b520042df76de64591b4a58e19491c172c74b4aa713d80266cf9849d2647e20bbd2eba1051e9090849f99116512e7343d7406db33cfe6830a1f1d11ccbd541b
0x345a1e8fefe5f5169e0d4f0da4ec268fac8bf6f7 | HOP_SYBIL_REPORT | 0xd16d14053b12fe61a3a8895fb370317104306e09029185987aa754124ec024234aa74c6d984aaada8e6c2778b724f9d675dd9ae5109108051bbec89201a39b171b
0x8711ec4a9f9bcb758eef52cfe40a8af078f3ae23 | HOP_SYBIL_REPORT | 0xc324d037b96f15871901d22a38bc62ae922d8ac4afd5fff6d7e863ad8f2ea16854005ef3a65b30799ef0339472944a3e5356b1e0d1ee68e61d800d386240dd0d1c
0x3d47a0ff952c31b1723f7f33df2049ab2ba43f10 | HOP_SYBIL_REPORT | 0xca35313743aef93542739e2f64c89fdb881a002721f683ab14739d06c59ebe7f66f8f5473dba01882f1e8a467b886cb1776ff4071f47c7e610562407e7ac879d1b
0x2d6fc2f6592187dee94adf54ab4598267312aff7 | HOP_SYBIL_REPORT | 0x3a46c513934bc7a7d84482e43646e2a01c810d944008a6bbd811db89fac65f4b115fcf013a35d3e36b92b1f274fd96373ca82cec3c0007dcae5392816c5bae321c
0x75ac066bad9b26d3fb2868b79afbff9ee3e1a4e6 | HOP_SYBIL_REPORT | 0x62c6a48c92edc534aac36a0bbd765a19e3f3de732e48b0bbf1e7d655c7de4d230eb18ede048cdd53bf2d681b4acc11aa112b144cd126ac4854dbcd116f9c78a41c
0xb5e96bd864e60545055848e21656679e2d64b537 | HOP_SYBIL_REPORT | 0x427c1359217b73b6a0914e1ffe9cceca459addcea50aeb5fed28ee52810bb1551b21e7aaba271c4c63b1c318ede14e3214f5b1cb27fa8b203cbbae2980b117da1c
0x756980078bbe9782daa3cff16291376400e10e1e | HOP_SYBIL_REPORT | 0x2ba9203f19ef22938b3364380ee3ab985f7065194781a80fc25410227a0630243c4c5b5890f11685ddc15c1620c6f961768e684883599b7edcf6ef21d0bd161d1c
0x684b3ff80ee833582446d3bd6f974f6c1dd90e0c | HOP_SYBIL_REPORT | 0x798486808b7eab865b4e7f752dad25d2abd16226fd0696068650ef27549e77155e3e53ca5486a619be7e63c28197b331f7be4fb8b665a4ff77d93484301f285b1c
0xe8688d46b58e6cf3a3ae4829468be337d7476531 | HOP_SYBIL_REPORT | 0xb61b0a3a2d8ab1c1bfa8f30993f4b1c3df351df459a42c690d4b18cedfbc9e834aa145b7bb13182b17878621801eb53fff25b84131387506965b52ef400ea04d1b
0x262967a0060e5a84b92210f598733062af5b8e6d | HOP_SYBIL_REPORT | 0x0c3dd1172c8e3f1be1759f0d8f970f8302831600579d82b4e836e26ecab0d9fb48dba9947d9e87f4825723c7317b45d7e33d1a2e3cd437ceb9cbcf06f6e49ac11c
0xad2423c594f2da0f38ea63a6e86c243fbc7e2225 | HOP_SYBIL_REPORT | 0x443b87d53cda70fc3c8472d4b45535fe5eabc03473cb7c867e92950ff4a15b724cb6153dabcdfc3a2692de22c5d0820881004e08e18b1a4baf5c04870eaad4d81b
0xc9da782dd37d943676385d76931249df36e5f4d2 | HOP_SYBIL_REPORT | 0x282b6febd29cbfe13add9b57bd50390a3d8f52c0e2a3ceba18aa4b3be9e220cd2839a0a2390719f468176009a9bb2f42b3581f78e5e3935bb54b4e83fea2c4d21b
0x104c3c4fb24387b984e89893d5fd1e0415d6a48d | HOP_SYBIL_REPORT | 0x275df3ad5f70b03843e440e685b0f3a36a6684789a8b48e1c1fb7336a2f781ab6eb6c92e74ed0ad1e4b9167076f4a79557c6c9e74fb2fbf867dd3665506782681b
0x203f8ccace8d129f2c57d161bc95d4996c8fec28 | HOP_SYBIL_REPORT | 0x6b758f5eac5a367c927d0e57dd21b9b937ef30d985937a6824374dbccdf792332c90da20f1bba106ca30c4f93dd6c094efc89dd73cd290bd2f99f74e521cc8e01b
0x64f449d758c86b32f22d92bc05c434306031601c | HOP_SYBIL_REPORT | 0x3c93bbf43161ae59a412f98e193954045fc3a7e71ae61d17a65a13f994e68fad4a3a72154b47be281f8035c971b2b0c9e351996d414b126022c4a787250647121c
0x672ab74dcbb5f16c236a0e534cd8b32dab0cc6fa | HOP_SYBIL_REPORT | 0xd1b963e99218af436adae093c6326f7de485c6cca8ff37f9ff1b0bfaa4ebdbbd6c089b5a5654a7f953b15f9049fbf52ffe40df836b3f9895e905ddf11b2ac8471c
0xb1c88838f180daba9e2e54e2c63c994710f4c9ad | HOP_SYBIL_REPORT | 0xdd443bf06bc96c9686c71a7f9bbd2f60eb0014b454b599761bc855287e969b576dc348eda01a3198bd84bc3a53bba9a3e320a93a7bbf5e94ab33fdf038dfbfa11c
0x8147ce3df428bf59edb6ab3d43aed3297c98d319 | HOP_SYBIL_REPORT | 0x05d29457d2aa61bade45d12d10d5d5cee1354efb232940c7a5501089a9fa01174c02fd94bba805fcea7eadaa5f0bb920220759185098c62d10fb2515174fd2131b
0x4829f805da616bcb3e07b1cd08fd5bf03d0fc2d6 | HOP_SYBIL_REPORT | 0xe0ae682f9c5b02a37dda4c3265549b736f36422e19a1b944eb8e39dd9f611f0715f28ef3524b26ba767f30ef3b7cefaf7d7c303554da3ad7616101739329d2961b
0xca36b43920cca2b9a6007a4c4b52724b347d14dc | HOP_SYBIL_REPORT | 0x76484f2921713adc1068305b0659ad0968f1b873f3e3134268069553dc69f81728cac6e076356aabead13a6294503405e23482041d696a428be70af4ec39e4331c
0x237659a5700be0b4639436111473773ab25c29b3 | HOP_SYBIL_REPORT | 0xd0bc5436f40bb70ba2bf793c2c56404eb5dba38f0e283dc090aa848aaa81e54a01220d784318d0a19ca147c5037b652723f2b68533105c3bb41e0c6624f435021c
0x18566d7f82ecec1008471856cda865085d6b9451 | HOP_SYBIL_REPORT | 0x35369c7fa632587ba9b0b297e5719201e44fda4bf06af09e5dc79dec14f249743906846262d493e82a34ddea9dec4151b297cd341e00068ecf4dd55a032de4f11c
0x30a676abb21ac4d17db1d159c0c993ed5c79f892 | HOP_SYBIL_REPORT | 0xb16a24186dbf59cc3c84419f1238248eec659043854db7650176843e23ac6821391cbc94f8bc991cc82b9006c4959226e26e72977322caa681000babb2429dff1c
0xb7fce771bb38ca33d727fa15e354213bfd941dbe | HOP_SYBIL_REPORT | 0xff3873269634f4289f3f897d9ad889c9afdef48278fa397d244f8db03bd430551d4d3972874b2cd9f3aea1c0905166f3a14776318419a9b74f658f5c28f9b6231c
0x24f2e8aa69d50c424db4db9219e6011d755ba75a | HOP_SYBIL_REPORT | 0x400dc8e672e121d2c2c3bf617247b3081919e2e085036399124910940098668b1af472c804943ff4a85427d2fa022e8f971843474a6157213488dbd6a60176001c
0xbeaf711431ae202796ed47509e28f80fbc56238a | HOP_SYBIL_REPORT | 0xa75b8e15b9d473d29f2641e9d2528d4454f2417ed6b92df37f181def503e765261b9451bee5187d64250e9706795f6a16289694336ad7795ba6c85dd833e90b71b
0xab88165f83fa673ae0ee64f4c0b91a71453b5dd1 | HOP_SYBIL_REPORT | 0x108ea8673dbc0aa5fea617499e31840851d122025f4429d04b744dd7e71cf36364193b24e9bd40a0920f874b4a6dd57a4930b9639e557949c31cbbaa40cee8af1c
0x4615dc7e6e6750c24300f3057335bbf473950f38 | HOP_SYBIL_REPORT | 0x102f136d10ea5c814aaa6e3b8b3df8aef6d2f4203c5dbfe132b6192a4df36b9a495b1d0660bbc54de9307d985dea4c78d861a056070550561ef703809d7becb41b
0x539698d145faec4199e0d86cddf8900dce46a868 | HOP_SYBIL_REPORT | 0x92b82ff60298083bcc0f05c04bd30738b6eab02a255ab03dd36d353a5ec4f106583424e900475e13c5d8be657533e5774969655509dba6b754f59a8cfe87b6a21b
0x751cdf0da1f2d5397d44e12825788ff426f1aba6 | HOP_SYBIL_REPORT | 0x2e39a57eec1617a2695d4f6ff12acf75b74bbadec11602328844267681d1af2539d1b428c4daf6d9b192396f091a2c07e3c9bedff5c3f38e4424b8f0da8d2f351b
0xf31350341ce843a1ef9b4108640064d60d639365 | HOP_SYBIL_REPORT | 0xec13dd58f2d64b6c15a19379d515a814da63e64e5de84d8eac898e99454ccdd2746095baf6a17f3a9e7d2247e1ac640344345a067a4eb93c4d4930b0909cbfa01b
0xf20658e4d1279d965f50309eced5f96da3b2a8d9 | HOP_SYBIL_REPORT | 0xcccfaffda4be6fccc9ac4396f1cd8386257becc770fbe56e804534348c2c967f5ca0b66d7489f7d4bddd1ad7016f2c13cac27d91158cb2e52563d16cf45962e21c
0x46830f4f5f04770e70b5eff46eedf50279c5bcff | HOP_SYBIL_REPORT | 0x12b297cf23c9ec5aa9b297d137dc648ec60d9fef94d60c3a4d17581713739db60c66d8d6728ca6feb9e6ab688ecca1e42451107887fc442114013744c292dba41c
0x9fd3a798bee7ad7a2fda4c7c2eec6b7967c48839 | HOP_SYBIL_REPORT | 0x1d34c3d7eb0927aea30ad7171631da973cf203d927d8a652fcb0ce8c76cb3a4d0df1621b574c3385bb65ee3ccf0144444330643e41524591092b072fc63dbbb41c
0xdb5399169313a48f7fd0f6a1fd514e0cb5949d17 | HOP_SYBIL_REPORT | 0x07dcd85c66ef66a1159537611bb2fe83c82a86cd6f90ad96c724587ceaf796e45bc41b02c73acd4f647351c69ec94f59e7b0ed95f46e37ff367e6be030b0dfb51b
0xffb2db3d55919a2eef201a13122746b5ea2b072d | HOP_SYBIL_REPORT | 0xf776a7ad79028bfa266ef7b4ae8c31aae61d95969803eb1771c2df832486e9fd0bda1a5592487f5883aa4358b69a6b0687bdcf72de33008eb0f2d43641a44c971c
0x05456d2f36d60772d8f4e4f5214eb5850b1ab937 | HOP_SYBIL_REPORT | 0xf24e8ef6d296bebd33a9b3e4b2a8cf02cf7a30b7a8af439663342bff381c5e694c301b794ed260ba88a0c35d9bc3aedf4e523f8779e4e0122a9459a113545aa41b
0xc8afe7f011596bb15e82d9c735f891e1190c4e9b | HOP_SYBIL_REPORT | 0xe164427fbf973033a111bcaa7375ecddf936fb5986805685b938f37996b41b561e66e70d5fb365042e961def33c0e6e156deea1137b54d5c1fb3a2d3559ba8551b
0x1e41c932a267a326333e5f6a630db9e201c816b1 | HOP_SYBIL_REPORT | 0x572892a044db8ca29518bf8d4709927fa651395c5f6e0e4a23cbc6c8432c121a04e5191926f78ff007729239ead577183f6aea11289060a2313543e7e81f48141b
0xf08aa2410a660569f0ec58d634aaf0baa4d45e55 | HOP_SYBIL_REPORT | 0x7b8777b043296e34006ccae46739c15311e3de6b5442e9f9f8d622edcfe65c222833c4e22f3b187d7691ec0ce5da5a34136faa4bad19e111017982486c39a6511b
0xe0dc6c5d55d9ea5b9582f8837297fe2dd92b8482 | HOP_SYBIL_REPORT | 0x7fda74256feb1a63b277d7a28af81956724173f3f99511e61c87773a9127cf3a3b025d21142ab4100944fa6d6a400146ceb40af95d2ecf60096dd632f497d53c1b
0x3a36c2dee82e7ec3fd4ebda98e2d6f6ab293c9ef | HOP_SYBIL_REPORT | 0x83ed2fd47c6b43ce848b8557e3a3897ec28b689ed7f92c5f7f9eeabfffd0d93b1184aabaa43a3134274e5ca4b1501294a9d91d6dcd62bb8b43caf9a7866ad6d31b
0x1189a08012ee645cf18c84d921518f328687868d | HOP_SYBIL_REPORT | 0x20211c4bd462bb96aa4b0c2bcd15ad1043dd7cc582864376e3a8267696acda927a32f209fa5c0580ecc3ac6b3489be822148d3ff3014cd27b7d99e8c3d59e4e51c
0x31dde8edd4be987fdb32a6dd3cf6d7fcba70a774 | HOP_SYBIL_REPORT | 0xd4bcdc1bda51fac112016d5bf153ece1ea18e4e1b0c2f6086f7e8189ad79bd8f7c8a8ed6d944e0d92ed75677af23d3bf56a1a4d262234470c906af3528f073b11c
0x2bfd2b169fd8f389528e80f2eca7ea3eb525c019 | HOP_SYBIL_REPORT | 0x1545b456391d74aef56288ff930e5288f8c43dcc8f997b36581385fc036c92ce1751bfbd10a66aae600ed52fb4bfef16787b9b35f5e36db134a851a3c0788a4e1b
0x9d534d8939b6aaf2d36b4a66872798592ed6a754 | HOP_SYBIL_REPORT | 0x9e5e78c03fbb85d0981e9c2981feaf92d85e67fba279419db3dc655fcfc70ebd06320f004cee08f045894207d0cdde15b93872aa4289af165bcf67ef1a5abaa11b
0x2328c73203fd463466e7e2c17d0de256f0d9c52f | HOP_SYBIL_REPORT | 0x3ceae62b8508cfb817ca463933dfc0d2369b328b5181077eaa2b119dd85ef4e551b67705496ad13abe8f914281641c8127e9f4bb2d0ba1ff2a3374b9940a102d1c
0xeb53fec14f0b78fc93df42aecce2d9879d1ce2b0 | HOP_SYBIL_REPORT | 0x8f4d389e059df408929d9c0dab418fac9dbf0721d3eb214c9d3477132ef8ac310acf7cb514729b0fe623ee6c9b07b65c0fe300623918c89a2d3a2cd4aca0eefd1b
0x578831812087b8c86105a4be03adf2125247cced | HOP_SYBIL_REPORT | 0xf952bcfc0b620972d5765fc798e20c51f951eb5bfbbe1d18a5d7ed1c7ab2c5f502df2b1f8352cf44fc31701a1111ef518166a38ca4aafb657c380cb20b2ee5791c
0x192d77bb910f53467033cff54cfe68250dd4307f | HOP_SYBIL_REPORT | 0xc7066bf2993550d2b9259c52120f88946d6458ee6450dc6772b626761257ed877db63bd6cd16765a2b8b5292dc41b297cb77141987d0297d792a33c4a01551ac1b
0xad50ce5a16b3d02dcb2142e698978d653b61c731 | HOP_SYBIL_REPORT | 0xc4e06df3c9d135a2240bb6de1343850a2f314fa237cddf98a149339db5b153d74c44cd6fee337faba92e046b023d0300ba103ff155309307c35cb2803cd08a0b1b
0xf9bd24fb6e36f9135bf22749f6a8c5725d66a078 | HOP_SYBIL_REPORT | 0xd166f5c23f1c894cfd30b6be091d2c6df71ea8e25dab5dea23367ed7427ae02d7544302e306f372cf0ab19781b7de0aca06772145b1f08b2a106a5e078efed621b
0x004d4350148777d3d508dd5f8c3e64d10d6cb6dc | HOP_SYBIL_REPORT | 0x75aeacf2523c9ed9078c318a0bbe36ad0d40f171bb1d404d8701f1a3a722f17c6ab67d0d27fbad00983f20ea4a21ceb596fbb2fe245ee080d71dd4b06ebed7071c
0x6d35f6c15190bfc5f4e5e5047618d48e2ae586f1 | HOP_SYBIL_REPORT | 0x82f75bdafcfc2a9bab55a07f232e62f42fbe511f89f19a2644d99eec02b9a13e03dc06003df17f57f41d81459aea189008c63843f5e01324f03adc75b31202a31b
0xfec043a2d95e8e4067e14d255fb9686dffa6b699 | HOP_SYBIL_REPORT | 0xe863a90b520275737d7f324ef8ec2ce3f1af63adbc521ba065737341635a1412536efd82c4c8a978adce5a0ddb1d6e3f34683212e4f9e20e85182d98f14d86141b
0xf8dd37ad553e86daa162aa887c8af55903811f27 | HOP_SYBIL_REPORT | 0xcd301424db81d8dbaf7a4ff5e1e62fcc8950cdb629d837ae993bc2ecf0855afe2f3c9dc024706b3615a14923ae313962c9b271c5272ffdf0c22e5b173a745e261b
0x52dd9b5f2019ba7837005a7a23e89b18ba9b5b17 | HOP_SYBIL_REPORT | 0xe6881f1eee5b19373cc4b1a98430e09d96f56eed0f3bef0a3f82cebc7278abe951abe46802b7b88214f4ff29dff5986eff978065d9f7974dec9284dea6edd7361b
0x63a2ffa4553d75d62e6fe908c9a94a0d14043d6f | HOP_SYBIL_REPORT | 0x7d7d2425eefb280b8c2b618b37aa7856cc8eea49fc6a846600d759a2e8f590b33753739b18a33df2b5d1f09a5c4baaa60e172eedec13a0cb46da51ea3371b6641c
0x9797604b956903c1e5cd1065a1e2d0d08395b6cc | HOP_SYBIL_REPORT | 0x696031c30ad7ce29601543a51ff129f081eaae7fa28226d2f59875d718af39081395439978aa8c2808e5bb4496be1729e15aa146f3fb84c2524d690830201a2f1b
0xfac24577f69e7e70121260070d81d74d5ddfc549 | HOP_SYBIL_REPORT | 0xc3a248c89393a75af4fcabb538bcfb788f51a8591d73c83c417e37c79d179beb3ddf9ae7e2a064704f22d8a1b24dd0788c0415f9acf92d10849d294272d5ded41b
0xe7dc254da047834d796cae9c4e308e3a790d1dbc | HOP_SYBIL_REPORT | 0xa09fb5b4e07ee0a4caa3886d0871634c2955e917e784f691ce5e42b0e343667338af814fc73fde90ef5f874b916da793934720331d3c297a6a6fe4e62d5c6d551b
0xd7c9b339d66085339d013ca472f1acf9cc0aeb1b | HOP_SYBIL_REPORT | 0xa3d328282340dc12d535acb8b8621bcb532d0cb50b97c7231434070960e90ecf7e416f7c47a49b78cd82101c123868da27dfe42bc492cbcf5edeed387f1660281c
0xc794c162fe6655a2643cf60fccf078f86633b4ad | HOP_SYBIL_REPORT | 0x0adc0da3b4b09a733c2f54195a51045d9f89de1a39f269d2a7f8d747d841962430e98944a5676ad77f9b6068d180c22127aaebf83540f508b039626f9242ab3c1b
0x23eee5a988aca9ea4fe1e0740260f0adcc7fd3cb | HOP_SYBIL_REPORT | 0xf95dd0f033070c3a825963f69563ff68993458224a621fabea36f273f03b6f1920daada6d221f3e013fbed9e640f0d3b4b1dd61c6039880f286f8832efc6fead1c
0xc45bd9f9f04bcba82873771d0884a31a88b5b8f5 | HOP_SYBIL_REPORT | 0x86a8de3f6cf9cc1e9887e5ff7d899d074b5ee9783077caea8b092648660da2bf6c6f7084d60f4c97980e443cb0a14a09e7233c376dc5dbcd1c92827ed2d597381b
0x940627d2892ad48df4aa0aaf6641b0871096290f | HOP_SYBIL_REPORT | 0x3f65e4390b3605e4915f8c1e3d26d23d98dafd6a9a7f90343396018cf6a6e02a1aaa4b43e4e8d57b78a46b5e9f0807417b5649a0b8c7ac210686ee55afb8164e1b
0xf4592f663600f1ddfc6070f7c94126126e4ffc50 | HOP_SYBIL_REPORT | 0x3cff888e17592d5d62189bad162698287a086a74c20e4d1ad66feb8c7f89e06b05064b22f243a374c5e85597d1ed4ee5e3c357c6459c9f5d699e2a8a08e55abf1c

# Reasoning

# Methodology

# Rewards Address

[new sign hash.csv](https://github.com/hop-protocol/hop-airdrop/files/8640319/new.sign.hash.csv)

**Comment by shanefontaine** [comment]
Thank you for the report! We appreciate the self-report.

Your addresses are only eligible for the LP token allocation. This allocation does not take into account the Sybil attack list. Because of this, your addresses will receive the full allocation.
