### ISSUE TITLE
This user is not found in Hop Server 

### ISSUE THREAD

**Issue by nekooei** [hop-protocol/hop-airdrop#132]
This user is not found in Hop Server  but receive airdrop!

https://github.com/hop-protocol/hop-airdrop/blob/6dacce3913d0c4bedb551f13bcef496d3d41bba7/src/data/social/discord_data.txt#L210

![image](https://user-images.githubusercontent.com/12533428/167130867-10b7d7d6-6c7a-424b-9176-f63faab90f0d.png)

**Comment by miguelmota** [comment]
The user does exist in Hop server

![DeepinScreenshot_select-area_20220508140831](https://user-images.githubusercontent.com/168240/167315858-7a585970-442d-4f5c-ba33-e548b8451024.png)

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
