### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Zonerz** [hop-protocol/hop-airdrop#135]
# Related Addresses
Gathering account of the airdrop hunter : 0x174191c5da2a67c75830735ccc93e3f4cff554a2

**List of the eligible adresses:**
0xf760e110703b6669dba540597bb0751df5156561
0x93ae71c4f3f19a5d4644e3bf5c749adc8a6a47af
0x844cdeecb96988d3f69dfd1a3882f399e12253d8
0x6e3d28367b85ae95232dc3e458f0bd775b2f3127
0x78ad85279c5d18c4845e79ea0c4d3ad5e7ebdea2
0xc7623a76c1609cd86253f8b0d641b68532c490fa
0xa528777d181f5816b39c529e229493a939a55848
0xb450c9c66b98fff943eaa1b920cd65843bec3216
0xd7ed027ac871f4d2ff75768c2ee2be90aed30ccf
0x1dcc09f12c3c78f00a4430accff7abb5cf2855cb
0xc096668f3a1e3c5e1dbb88b68b22ea448e6563ec
0x8d4022aea3201cbaec2b4da8d9078854cfde6b1c
0xdc28d1f3285a33e7d699f4434683b83487739c94
0xf33fe81a1b710e97839e7a746d28cf779de78a29
0xabd2334307895e3483df2a95aaea970d1e862ecf
0x996450d786c4a3b25115426d6ee19dd9360e8f71
0x97245b59517ecc0de2e300298a088bc92b80ffff
0x3f62f12bb58437d88736fcd93ada0905325b4f6f
0x7a9a5394100320097c4c0e984731e723b5b4fd8d

# Reasoning
Before starting this report, I'd like to mention that there're only related 19 adresses. I know this is not matching your criteria of 20 BUT this guy will earn a lot of HOP token and since this is unfair to the rest of the community, I thought it'd be good for everyone. I hope that even if there're only 19 adresses you'll compensate my work with your promise of giving 25% of the gamed token resulting of this Sybil Attack because I'm doing this by hand and it takes time... (I can't code scripts unfortunately)

# Description:
It's very easy, check this account; **0x174191c5da2a67c75830735ccc93e3f4cff554a2**
I recommend to check on DeBank to have a better view : https://debank.com/profile/0x174191c5da2a67c75830735ccc93e3f4cff554a2/history?chain=matic
This is his MAIN account where he regroups/gathers all the money that was added to liquidity for a few months on different adresses, this account is NOT eligible for the airdrop.
This address received 19 different $USDC incoming transactions from the 19 different adresses listed here above (which are all eligible) between : May-05-2022 11:38:06 PM UTC and May-06-2022 04:15:04 AM UTC. Only 2-3 hours after the airdrop announcement.

All these adresses added liquidity barely at the same time back 23/10/2021 around 10am.

And here you can see a transaction of 92000$ to a CEX : https://polygonscan.com/tx/0x692e717a1c638e5895fb28602d48de444a891f9827732ee0bd268bd2fbb4a273

# Methodology
I checked manually the people that used the "remove liquidity" method on your contracts and take the time to see where the money is going. This is to see if it ends in one wallet that gathers all the money that was added as liquidity.

# Rewards Address
0xe79bc9BfFEE91dd38cF2B9a01F1C89816a355690

**Comment by litocoen** [comment]
Hi, Thanks for reporting.

Can you send me an email?: litocoen.hop.exchange@protonmail.com

Thank you

**Comment by Zonerz** [comment]
Hi Lito,

I sent you an email.

Best,

**Comment by Zonerz** [comment]
> Hi, Thanks for reporting.
> 
> Can you send me an email?: [litocoen.hop.exchange@protonmail.com](mailto:litocoen.hop.exchange@protonmail.com)
> 
> Thank you

I edited the post so you can see everything I wrote.

**Comment by rochestor** [comment]
attention, lito is a liar, attention with you assets

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
