### ISSUE TITLE
Sybil Attacker Report: Sybil attackers are reporting their own addresses for rewards

### ISSUE THREAD

**Issue by sybilreporter** [hop-protocol/hop-airdrop#138]
Is there any mitigation against this?

**Comment by 0910841082130913312** [comment]
https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc

> If you are a Sybil attacker who targeted the Hop airdrop with a large number of addresses, you are welcome to report yourself before someone else does.

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
