### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by gunboatsss** [hop-protocol/hop-airdrop#141]
# Dispute request

I would like to exclude `0xAB12253171A0d73df64B115cD43Fe0A32Feb9dAA` or onedickdao.eth from sybil group `0x08e0f0de1e81051826464043e7ae513457b27a86`.

# Reasoning

I believe this address was marked by being the address that first funded `0x2ffa0bdcdbe9132b8a28db192a22d71c53da9287` on Arbitrum One. This is however not a sybil attempt but this is just friendly gesture to helping friend to mint Arbitrum Genesis NFT on A1 rollup. Attach here is screenshot for this proof.
![image](https://user-images.githubusercontent.com/92352063/167156539-4505b1da-71db-4126-98c5-3c912551cd61.png)
![image](https://user-images.githubusercontent.com/92352063/167157843-c2b68a5a-f596-47c8-85b7-1dc4a2cdb4f3.png)

And here is mint NFT transaction immediately after `0x08e0f0` address received ether. 
https://arbiscan.io/tx/0x739ba0a0a063eca77c9b30f0f5e357bc7e81bfe88eb659add8b86801fcbbe11e
This is mint NFT transaction at the nearly the same time from onedickdao.eth before sending ether to `0x08e0f0`.
https://arbiscan.io/tx/0x6f4e5606785654adfeb899cf7bb781e99c9af9b28fd270d637b5921e4393915e

While he went on and funded sybil group on polygon network with `0x08e0f0de1e81051826464043e7ae513457b27a86` with bunch of transaction here (oof)
![image](https://user-images.githubusercontent.com/92352063/167159300-55e66447-4df1-4570-b1b1-962267846eea.png)
(https://polygonscan.com/txs?a=0xda07bc30428a66de2050accfa86ee2912229cd07). I don't own those address and I hoped those evidence will cleared me from being marked as sybil.

**Comment by litocoen** [comment]
Hi, Thanks for reporting.

Can you send me an email?: litocoen.hop.exchange@protonmail.com

Thank you

**Comment by Devjohn12** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
