### ISSUE TITLE
Be wrongly flaged as a Sybil Attacker!!

### ISSUE THREAD

**Issue by gyltlsc** [hop-protocol/hop-airdrop#143]
Hop is the first cross-chain I used, and it is also the cross-chain I use most in my daily life. Because compared with other cross-chains, hop is indeed the smoothest. So, you can see that I have a lot of volume, a lot of times. 
I have passed the identity authentication through 'brightrid' last year. It can prove that I am not a robot, I am a real user! I only have one account,  I have many NFTs. i am NOT A Sybil Attacker.
I urge you to re-evaluate, thank you very much!
here is my address:
0x21Fa2cf8E56B9938402A7e08703BFBe4Be0943fb
my discord handler : leolin#6637

thank you sir!

**Comment by r4bbit2015** [comment]
Hello
I checked your address and about 4 other addresses you have and you are not trading on eth, may I ask where you are trading from?

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
