### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by ramangitcoin** [hop-protocol/hop-airdrop#144]
Hello Sir,

First of all I would like to congratulate you on creating the best bridge for cross chain transfers and a well thought of criteria to allocate the hop tokens.

I am reaching out to report myself as a sybil attacker. I have been already excluded in the initial list that was rolled out but just wanted to clarify my position and interest in governance of this protocol. I have a total of 28 addresses mentioned below.

**Why I should be included**
My purpose of creating Sybil wallets was not dump tokens on day 1 but rather have a genuine say in the community governance.
I am really a big fan of this product and I sincerely want to participate in the community governance. Allocating me at least some tokens (may be what my primary wallet deserved) will give me a due share in the community governance. To prove that i am genuinely interested, i even propose that please lockup 75% of tokens that my primary wallet deserved but at least give me 25% of the tokens that will give me some say in the governance to start with and then judging my community participation you can unlock the rest 75%.

Your this generosity will teach me a great lesson and will also give me some say in the governance of this protocol I am genuinely interested in.

**My Hop Journey**

Over the past 6 months I have been a consistent user of hop bridge. This is reflected in the amount of transactions I did from my primary wallet - #1 in the below list - 0x2a7AF8aAD8461B730410fbe0166166F3B2aA856A.  I have done more than 50 transactions from this wallet and the gross volume is more than 20K for this wallet. I am an ardent user of gnosis chain and used hop to consistently transfer my funds between hop and gnosis.

While I really liked the bridge - UI, Fees, Speed etc. I just kept using the bridge and that made me create 27 more wallets to use this awesome product. Even the Sybil wallets i created i used the bridge almost consistently. - I did a total of more than 250 transactions and gross volume of 60K combined. 

If needed, I will send signature requests as a proof that i am owner of these wallets

List of wallets

1. 0x2a7AF8aAD8461B730410fbe0166166F3B2aA856A
2. 0x5e964D0744C123Db30746C1B1aB169Bd0E89a55C
3. 0x5140f2Ab91dd52596e48D450C7EFD8dA28b91AA5
4. 0xE120eDC7836bE76E54A5D7716eF6f03DCeF588C6
5. 0xEa26A289903dfb20ab55b28dfB8E99Ee259eff97
6. 0x256C616BB867023ffdeF9F58330568Bb7545D3D4
7. 0x7A418506b12dA921a6dC72952CD32CA171A51A37
8. 0x0d9fDf4d1b6980272f74112b889a6abe6A8F4AD8
9. 0x7a7F874f005945B38C410c1e28217367BCd65288
10. 0xd2bcc45022bBAd00958BB0a54eadEb8bf843d845
11. 0x3f15cEcADd58292846d71e06D06c77B5763E3a9b
12. 0x72c89Cc9F4409edC5dA0dBd595aC208d26FC2c90
13. 0xD3dfcce57Eee0Eb7fd37B401F3084eB14749596f
14. 0x6ceB80aCdb6DED269524f78376c135B446b3B047
15. 0x5403aBe4368984bbEBb700033913eBa75CfCCEF0
16. 0x8067c949E85AFDC3e3738E5a8768BE90d8AB5B75
17. 0xecb0B39125d0ac70A87e0C28abf2a80205794Ae1
18. 0x4D5baed1d8f193F19d5B48143763e8B2C38dF5a0
19. 0x6bf48ba04eE31d8f6B5eA3849a3eC85A48Fe9cfe
20. 0x03688571404Ac44d8e968F1A0270E589BcCBA93b
21. 0x38f6eF0a0F83C461a7b5668E4a519E9C635f30F8
22. 0xEcEB6d70C57e45b39F4660a1ED184f32eCfA63F0
23. 0x227f5e5284dd0e439f9257943d757df362512CE6
24. 0x974896b9888D834E15ccf86A98f9b598266E8568
25. 0x07F79A8A4580d843A7bef571B1912DEb0f5A943F
26. 0xbBF07c1Fb248ECb9938e3dF96D9E0895E872EC6e
27. 0xD95cdD2de1b399a0041368E05E916B185C500e9b
28. 0x308557Af1459978D9F4B8789fc6F67A37df8c4bD

**Comment by ramangitcoin** [comment]
Sir, My issue was discussed in this tweet by Defi L2 News in this tweet - https://twitter.com/DigitalOutlet1/status/1522590676466421760. 
Please consider my case

**Comment by shanefontaine** [comment]
Thank you for the detailed explanation, @ramangitcoin.

We genuinely appreciate this post. Unfortunately, we will not be able to remove your addresses from the Sybil attacker list, as they meet all the criteria that we defined at the start of this process. By removing your addresses, we would be walking back on our rules that have already been set in stone and would set a bad precedent for future submissions.

We hope you understand. Again, thank you for all the details.
