### ISSUE TITLE
Sybil Attacker Report - Hop Ethereum USDC Bridge

### ISSUE THREAD

**Issue by Keane54** [hop-protocol/hop-airdrop#145]
**Results are based on Hop's Ethereum USDC Bridge contract.**

**328 unique addresses linked. / / / 5 Groups of likely attackers.**

# Related Addresses

https://gist.github.com/Keane54/21aaac9b831d0ad6f932708170a02e40

# Reasoning

**Results are based on Hop's Ethereum USDC Bridge contract.**

All the addresses listed above have made 1 or more transactions to other wallets in a dataset obtained by querying the blockchain for any address which interacted with the Hop Ethereum USDC Bridge since its creation.

This was verified by querying each address against every other address in the data set, for number of transactions to/from said addresses, where there were 1 or more transactions between them, and they **appeared as a sender to other wallets on this data set 8 or more times**. If there were 1 or more transactions between any pair of wallets matching this criteria, this is added to a CSV which we compare against the existing list of sybil attackers posted on the Hop Github, to eliminate duplicates. The remaining addresses are potential unidentified sybil attackers, where individuals have used multiple wallets to attempt gaining an airdrop.

This is a link to the spreadsheet with the results, for more detailed information, should the team wish to view it -https://docs.google.com/spreadsheets/d/15ApKj8RAbwbmD-kym2NAekLZ3Aj54mBHZxfb3qJy0wY/edit?usp=sharing

If the team has any further questions please contact me: spookyb54@gmail.com /// SpookyTM#8606.

# Methodology

I have an algorithm to determine associated wallets. This algorithm is based on the Ethereum USDC Bridge contract, but will be ran against the others with significant transaction volume. I ran a query to get the addresses of Ethereum users who have interacted with the Ethereum USDC Bridge contract since its creation and then ran our algorithm against this set of wallets.

This algorithm compares all addresses against eachother in the dataset and returns how many times an address has sent/received to/from other addresses in the same dataset. In this case, we ensured each address had a minimum amount of transactions to/from of 1 or more times to identify likely potential attackers. We also applied a filter to where **an address had to appear 8 or more times as a sender to other wallets in this list (i.e - They have funded 8 or more wallets that also appear in the data set)** to prevent affecting legitimate users.

The result is a formatted list of addresses who have made transactions to eachother over the course of time since the relevant contract (Ethereum USDC Bridge) was created, which are likely to be one user with multiple wallets.

This list of addresses was compared against the existing identified sybil attackers posted on the Hop Github, which has >10,000 included. Any that had already been identified have been removed.

If the team has any questions regarding this algorithm, please ask. My contact details are in the above sections.

# Rewards Address

Gnosis Safe Wallet:
0x38E637fd9f679d88dfCf0372Cb6e887371c18A99

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
