### ISSUE TITLE
tagged like sybil attacker

### ISSUE THREAD

**Issue by Moncryp** [hop-protocol/hop-airdrop#146]
**Describe the bug**
hello. i just ckeck the airdrop and noticed that i have 15 hops to claim. then check the explorer.hop.exchange and noticed 3 +1000 transfers with the protocol. then check the attackers and noticed my wallet is considered like attacker.
is there a bug with the airdrop? if i am consider as an attacker where can i see the reason for that?
i wasnt hunting for the airdrop. i have it only in 1 wallet.
i can send you all screenshots and my wallet adress and you can check everything was legit. i dont want to send my adress and screenshots here because of my email. but would like you can check the info.
thanks. also nice bridge always worked well for me.
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by litocoen** [comment]
Hi, Please add your wallet here, otherwise we won't be able to check. Thank you!

**Comment by litocoen** [comment]
You can email your public address here: litocoen.hop.exchange@protonmail.com

**Comment by Moncryp** [comment]
> 
@litocoen 
0x16562EB02a3C95712C10914c6c7ba0f4b0502d6C
tagged #928 in the attackers list
also have send you screenshots via email
i think i should qualify for airdrop
also hope you arent having a bad time with people.
thanks

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
