### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Javigr94** [hop-protocol/hop-airdrop#148]
Hello, I have a problem with the hop airdrop. I appear with my main account in the sybil attacker list. I only have a second account, where I decided to bridge because it was necessary and decided to trust hop (single tx). However, I only have my main account entitled to this airdrop, since I have made several tx worth more than $1,000.
main account: 0x3eFEc9925973AFe87CBFE219DFE31fbBA4266369
secondary account: 0x6B53e47D58D0AB423e7128d2Fe365B6782d50d50

So I don't know why I appear on that "black list".
I hope everything is resolved. My discord account is javigr94.
Greetings and thanks for everything.

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
