### ISSUE TITLE
tagged as a sybil attacker

### ISSUE THREAD

**Issue by Moncryp** [hop-protocol/hop-airdrop#152]
**Describe the bug**
hello. i just ckeck the airdrop and noticed that i have 15 hops to claim. then check the explorer.hop.exchange and noticed 3 +1000 transfers with the protocol. then check the attackers and noticed my wallet is considered like attacker.
is there a bug with the airdrop? if i am consider as an attacker where can i see the reason for that?
i wasnt hunting for the airdrop. i have it only in 1 wallet.
the adress is 0x16562EB02a3C95712C10914c6c7ba0f4b0502d6C
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
