### ISSUE TITLE
I've been tagged as a sybil attacker :(

### ISSUE THREAD

**Issue by AndyHG1** [hop-protocol/hop-airdrop#155]
I've been tagged as a sybil attacker!! 

Hiii, there's been a problem with my airdrop, I match the criteria for the airdrop, I did several bridges and two of them are worth more than 1000USD, my Discord name is AndyGG and my wallet is 0xa0055CdcBf9A644805e264c6D64e25A0657eE58B, I'm in row number 6420 of [https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv](url)

I have two more addresses with which I have used Hop protocol but they don't qualify for the airdrop, I didn't perform any sybil attack  I don't know why I'm on this sybil attacker list.

Greetings and thanks for everything.

**Comment by DavilkaS** [comment]
admins are worse than in paraswap. -rep

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
