### ISSUE TITLE
I am NOT Sybil Attacker. Rockhollywood 2189 discord

### ISSUE THREAD

**Issue by Rockhollywood** [hop-protocol/hop-airdrop#160]
My son is coaching me, so if I mess this up, it is his fault
My discord: 
Discord : Rockhollywood #2189

my hop wallet:
0xC8654f25653aD8043D85704B8A801Bbb2E4af5f4

So, I am eligible for airdrop. My sons wallet is:
(Note from my son).
It would also be smart to mention that this is your son’s wallet:
0x90c6577fb57edf1921ae3f7f45df7a31e46b9155

I bought a half eth, and my son help me wrap it and stake it on hop in hopes of increasing my investment.  Did hop on 1 Jan.

Transaction Hash:
0xeab9f7cbef5074a5b7cbe6d2b3c062a11ae66694e69939d299848d36b1984374

Block:  
23232187

Timestamp:
125 days 17 mins ago (Jan-01-2022 06:56:37 PM +UTC)

Tokens Transferred:
2
From [0xc8654f25653ad8043d85704b8a801bbb2e4af5f4](https://polygonscan.com/token/0x7ceb23fd6bc0add59e62ac25578270cff1b9f619?a=0xc8654f25653ad8043d85704b8a801bbb2e4af5f4)To 0x266e2dc3c4c59e42aa07afee5b09e964cffe6778 For 0.42 ($1,127.16) Wrapped Ethe... (WETH)
From Null Address: 0x000…000To 0xc8654f25653ad8043d85704b8a801bbb2e4af5f4 For 0.415030545895962742 Hop ETH LP T... (HOP-LP...)

I hope this is enough info to fix my problem. Rock

Submit a report here:
https://github.com/hop-protocol/hop-airdrop/issues/new?assignees=&labels=Sybil+Report&template=sybil-attacker-report.md&title=Sybil+Attacker+Report 
(List your main wallet and then list your non-main wallets and say that your main wallet should not be on the sybil attacker list. Your non-main wallets shouldn’t be airdropped. Also if you send funds directly to/from coinbase, then that should be mentioned)

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
