### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by xZCT2017** [hop-protocol/hop-airdrop#164]
# Related Addresses

0x4f855Cd9c9e47890ED7E394379E7ad5cE048dDd9
0xf8df9716c5b83d02F09a34E9d62C9e22F62C616C
0xbACAF16F83ea0511123D937bBE83480d6eeBC118
0x79dBa1d434c26746B21233d3a46660523FB934A0
0x4b1C21C93Ff275Cbe80Eed552964dA91d5eBafb3
0xa473855ec37a981a4FaBAa196A1D536AB904e674
0x68cdD84267c53882271a93221a18FE5515fb8921
0xD6ccfDf5cC9aB482eE1d6b8D29904f2D08420Abf
0x7c67Ec08525672a4703c51125709DEe33C24A240
0x4B188a3c642762c21d6bDeb44819c40a61873Dc1
0x0FD2Cf82D6D0131233b4793BdEeAc02e76A16207
0xCa253fE65D86E0a1848864184C170FaaC021F862
0x74C3b2d22ED5990B9aB1f77BD3054D4fD4AfCF96
0x3E1daf2C9477D7b0C9E8500180e80D7Ef93584d8
0xaDAe85E5438e81AE5F272A394EF9B0E8d8152185
0x3D4f5869abfb38EF6a8E7350060d0b9c58d36776
0xca8937ccfd9486A69e1299184ee39f50B098d1F4
0x9EB1a1f5252fC6cDC857497e883a4500b88c04BE
0x455Ca2eEEB67bd243993C58Afea5268F2af9de9A
0x451B6B19E0B84730c0306628fFf4BE7A9509affd
0x3D764EF787cb2D5A4326EFB126b3C87C41dea03E
0xC74B2EC0fF1a0F37Dc9F88B476a45941cF28a473
0xD0c5817fc7989fDc13cf8E4E0c53948BA4E9eC9f
0x7F57AD6d2FEad3609A541e9EeCE99b0474784c51
0x7e4D4C3F1e36CD5E3E1f933Efd4A88f5b27e49FA
0xcDAF5Fd2a2D199B9C8E05f7C7079A1E4bbC87fDd
0xA547478BdfA44eAA7650905fe95034187C3dc96D
0xc645303a36d7313f1414250DdfDdD58A972e1a35
0x74a191ff18e99A7eB7c6E58269ABBD9a86a5D930
0x17256EC32f4c6759582f4d272D92Ef68F6d3004C
0x774699AE2615EFD12f93Cf90ff7213E6D61b6d06
0x7E491C2Abe6fa9e39c96bBCBc3f142B2E160A604
0x36b7562e9087cd0D2fdA4870997fd2ac2dEF4C70
0x3f2a9A1DB4D1CF4bcAbCeF32F2E25cA6419Ad1F6
0x96430447cc9E9816100d9c5E365de6463F9BBB66
0x0a59342aC0D4d559Dcf0f25c9313668d4BDC6228
0x8c81fA9Ae3CA9499e7FC374aFB09d9219d26a866
0xd884808c8D9c40Af3108c853b0455D991105c8cA
0x5d2249B3e1675d56CCFDC8b4318942e88eA3f127
0x1ca661110Bf33560498DC1d955961AFb05CC4972
0xA7239A6c9E8151A887d45cfD64e854eF9207Cca4
0x3b04F42507442408B8385ADfBaE74b6a43f5f7dD
0x13928F482a3483Cd5fFAdE46A98797561230805a
0x6bFE350873CC600035C6697A748fBff708A6e14f
0xD4e46de7D58c58061ff72d6F69C18330186ea5De
0x9a1Ce61815C2e7cAFd55a8cA2F03Af7dA34B1b84
0x33E6744fd08EAfc3bC8fDE1b15457Cf154E11297
0xF2b0d6296c0f2321Dc17f6778138d9c42535540B
0xd233C7B02C2F245F90d7764E4f083d5b82156e2c
0xcE0b352177038599b1df4505F50ff731FF6421eb

0x396AD0FE7e212294529c061597cB06a978e73644
0x9fC2b6F63135F0aeFb9d092eCAf4a27C315f51a7
0xCba7820137164bDd765c29a185190Bbca95046A3
0x6a9d38AE74EDBc70F642507B5EB370a4bE73e6B0
0x043e684fbe088442826931315d04f1009FDBb02E
0x3E0c89dC904dFE4BDc135cc0534AF47F6c3BFDE4
0x5F47A9a2365D846328509f11F66f9650C93E5190
0xD3F1CEbE695d80831321E04159a403758cc0A1A5
0x09c38641e7F6322f7Eb2F16A94993D7864A287aD
0x01d9f91c2579b3197b08c560AFC660EB929936cC
0x2e01Ac614B9e918f7886e99393154B340208d8b9
0x5B93F7cC6Be95DB6417701Bc39C0e503451cfc98
0x6A4f7191A69F09636D51f2efB93640B86D288Ce0
0xF468c3D06e2261fa01eBF73A0bd1cda63E8e0d0f
0x6D1b8DC14B1718c61336550C400844353168ecD3
0xBbe8e353CeC9242B94054dd89C0ccd80c22F4279

# Reasoning

All addresses got funded by [0x9bdfaeb9cb28dc05b09b37c0f14ecbc9a876cee0](https://arbiscan.io/address/0x9bdfaeb9cb28dc05b09b37c0f14ecbc9a876cee0) with 2 contract calls, sending out 1 ETH to 50 addresses in the first tx and to another 16 in the second tx

1) https://arbiscan.io/tx/0x4bb79c4621d5894f8f900d1bbb9e25575d21e94af4e0021de8c6d7963286b22c
2) https://arbiscan.io/tx/0x7fc8ced62e5b210d3ad4f0cb96b42d0eae7bce4112b33e8baa8b12157d8ae25f

# Methodology

The disperser contracts paints a clear connection. Besides, all addresses called `AddLiquidity` on Arbitrum between 2021-10-14 20:00:00 and 2021-10-14 21:00:00 and add exactly said dispersed 1 ETH. All addresses also interact with the main disperser address on multiple occasions sending and receiving albETH on Arbitrum. The exact same sequence can also be seen on the 'AddLiquidity' function supplying USDC. These were roughly done between 2021-09-19 10:00:00 and 2021-09-19 9:00:00 supplying ~$5465 USDC per wallet.

# Example

The reported addresses were discovered by identifying contract calls designed to send out batch transfers. These individual addresses were then used to perform identical actions aimed at maximising the potential airdrop surface of said addresses. 

Double checking and cross-referencing was done via Sheets.

# Rewards Address

0xb1a2F951B5406d9426FC8b40121b2AB8708749Ac

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
