### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by hebelubes** [hop-protocol/hop-airdrop#170]
# Related Addresses

0x65412637bb7841182fb1e8c6622ca3749061dfad (Sender From - Also Eligible)
0xa83a93e19a4c9e7d370f3287b199fa3dae25e644
0xd41de94e621ea8329bc0e0e37428a8d080127cf0
0x751fb9cb9e7f5e1e59104b1bcc8dd00cc82d59c8
0x22c1d82e0d3ba8087c2dfad766befe511184c8a3
0xec2b0d51600fb93a304016043825abc644e2baa8
0x27eb71cc17988eb77298072259d3855b4223c5ae
0x1af39fb2578c1fe55439840f586f7bed40e8126c
0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4
0xb75d94b05156938df46ab456e33ce4c9cdf93d73
0x84400c5e12bcbf953fb01f61695733ccc5f260bc
0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
0x736a4478d84aca7bb59558ee77aa05262059de09
0x4062e35c566233830abac6a75332feb0fc0e84cc
0xbc44b397e25780ecffac98fe217138c36baa6c8f
0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
0xb5d5cd6870d3e0211f8072a29648a738681195c2
0xb3b54dfbbe03fb44ce61331237195639cc309d5f
0xa36d9ec999e4a82d96141262f7aa3463a27475b7
0x2dc3162ac2d359f9b91ade2d48bdaf131f513a9a

# Reasoning

All addresses has multiple disperse transfers from one address. And they have other similarities.

Disperse links (connections):
https://polygonscan.com/tx/0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c
https://etherscan.io/tx/0xfad048a2b67043255b54c6b71243c38b49315ba21408a20a564356bcc29d3f83
https://etherscan.io/tx/0x0d5fa2281d284d32859d1f445d6453a97261bb9a58426bbd8db7e639331fa5d1
https://etherscan.io/tx/0xf7a3f30bac2f41fd2766567c070568b9f8213d5ec5a10ffa68f994d2bfb53ac1

All accounts used platform at same time (3th week of december 21) and with similar amounts. They used bridge with ~0.26 eth and the second bridge with ~0.14 eth.

https://explorer.hop.exchange/?account=0x65412637bb7841182fb1e8c6622ca3749061dfad
https://explorer.hop.exchange/?account=0xa83a93e19a4c9e7d370f3287b199fa3dae25e644
https://explorer.hop.exchange/?account=0xd41de94e621ea8329bc0e0e37428a8d080127cf0
https://explorer.hop.exchange/?account=0x751fb9cb9e7f5e1e59104b1bcc8dd00cc82d59c8
https://explorer.hop.exchange/?account=0x22c1d82e0d3ba8087c2dfad766befe511184c8a3
https://explorer.hop.exchange/?account=0xec2b0d51600fb93a304016043825abc644e2baa8
https://explorer.hop.exchange/?account=0x27eb71cc17988eb77298072259d3855b4223c5ae
https://explorer.hop.exchange/?account=0x1af39fb2578c1fe55439840f586f7bed40e8126c
https://explorer.hop.exchange/?account=0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4
https://explorer.hop.exchange/?account=0xb75d94b05156938df46ab456e33ce4c9cdf93d73
https://explorer.hop.exchange/?account=0x84400c5e12bcbf953fb01f61695733ccc5f260bc
https://explorer.hop.exchange/?account=0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
https://explorer.hop.exchange/?account=0x736a4478d84aca7bb59558ee77aa05262059de09
https://explorer.hop.exchange/?account=0x4062e35c566233830abac6a75332feb0fc0e84cc
https://explorer.hop.exchange/?account=0xbc44b397e25780ecffac98fe217138c36baa6c8f
https://explorer.hop.exchange/?account=0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
https://explorer.hop.exchange/?account=0xb5d5cd6870d3e0211f8072a29648a738681195c2
https://explorer.hop.exchange/?account=0xb3b54dfbbe03fb44ce61331237195639cc309d5f
https://explorer.hop.exchange/?account=0xa36d9ec999e4a82d96141262f7aa3463a27475b7
https://explorer.hop.exchange/?account=0x2dc3162ac2d359f9b91ade2d48bdaf131f513a9a

# Methodology

Checking correlation address with decode input data and check address on API Hop Airdrop

```js
const axios = require('axios');
const Web3 = require('web3');
const web3 = new Web3('https://rpc-mainnet.matic.quiknode.pro/');
var abiDecoder = require('abi-decoder');
const ABI = [{"constant":false,"inputs":[{"name":"token","type":"address"},{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseTokenSimple","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"token","type":"address"},{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseToken","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseEther","outputs":[],"payable":true,"stateMutability":"payable","type":"function"}]
abiDecoder.addABI(ABI);

const txMultiSender = "0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c";
web3.eth.getTransaction(txMultiSender, async function(error, result) {
    if(!error){
        const decode_data = abiDecoder.decodeMethod(result.input);
        for(let i=0; i<decode_data.params[0].value.length; i++)
        {
            const checkEligbility = await axios(`https://airdrop-api.hop.exchange/v1/airdrop/${decode_data.params[0].value[i]}`);
            if(Object.keys(checkEligbility.data.data).length > 0)
            {
                if(checkEligbility.data.data.hopUserTokens > 0)
                {
                    console.log(checkEligbility.data.data.address);
                }

            }
        }
    }
});
```

# Rewards Address

0x12FB89D601C674aeA4d91f92ABD30eB9bb57a95E

**Comment by GreyPK** [comment]
I probably found 9 more wallets from this group. 

```
0x8d5ba2b764356ddc9997fed94dcf83367e8a10a2
0x4062e35c566233830abac6a75332feb0fc0e84cc
0xbc44b397e25780ecffac98fe217138c36baa6c8f
0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
0x1af39fb2578c1fe55439840f586f7bed40e8126c
0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
0x84400c5e12bcbf953fb01f61695733ccc5f260bc
0xb75d94b05156938df46ab456e33ce4c9cdf93d73
0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4
```
Address 0x8d5ba2b764356ddc9997fed94dcf83367e8a10a2 send ETH on arbitrum to next 3 addresses. Address 0x65412637bb7841182fb1e8c6622ca3749061dfad send ETH on arbitrum to remaining addresses.

All these wallets used HOP swapAndSend in almost same day on Optimism and Arbitrum (12-20 Dec 2021) with under 0.5 ETH.
https://explorer.hop.exchange/?account=0x8d5ba2b764356ddc9997fed94dcf83367e8a10a2
https://explorer.hop.exchange/?account=0x4062e35c566233830abac6a75332feb0fc0e84cc
https://explorer.hop.exchange/?account=0xbc44b397e25780ecffac98fe217138c36baa6c8f
https://explorer.hop.exchange/?account=0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
https://explorer.hop.exchange/?account=0x1af39fb2578c1fe55439840f586f7bed40e8126c
https://explorer.hop.exchange/?account=0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
https://explorer.hop.exchange/?account=0x84400c5e12bcbf953fb01f61695733ccc5f260bc
https://explorer.hop.exchange/?account=0xb75d94b05156938df46ab456e33ce4c9cdf93d73
https://explorer.hop.exchange/?account=0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4

**Comment by shanefontaine** [comment]
@hebelubes

Thank you for the submission. Unfortunately, this submission does not meet one of the criteria for submissions:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours.

**Comment by 0xtoshi** [comment]
Hello @hebelubes @shanefontaine i was found same this list address correlation, to proove this is truely sybil attack so iam finding disperse contract and found this tx [0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c](https://polygonscan.com/tx/0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c) this Tx show sending 32 Tx to correlation address and iam check address eligible and found 19 Address list (20) 19 + 1 Sender From Address
```
0x65412637bb7841182fb1e8c6622ca3749061dfad (Sender From - Also Eligible)
0xa83a93e19a4c9e7d370f3287b199fa3dae25e644
0xd41de94e621ea8329bc0e0e37428a8d080127cf0
0x751fb9cb9e7f5e1e59104b1bcc8dd00cc82d59c8
0x22c1d82e0d3ba8087c2dfad766befe511184c8a3
0xec2b0d51600fb93a304016043825abc644e2baa8
0x27eb71cc17988eb77298072259d3855b4223c5ae
0x1af39fb2578c1fe55439840f586f7bed40e8126c
0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4
0xb75d94b05156938df46ab456e33ce4c9cdf93d73
0x84400c5e12bcbf953fb01f61695733ccc5f260bc
0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
0x736a4478d84aca7bb59558ee77aa05262059de09
0x4062e35c566233830abac6a75332feb0fc0e84cc
0xbc44b397e25780ecffac98fe217138c36baa6c8f
0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
0xb5d5cd6870d3e0211f8072a29648a738681195c2
0xb3b54dfbbe03fb44ce61331237195639cc309d5f
0xa36d9ec999e4a82d96141262f7aa3463a27475b7
0x2dc3162ac2d359f9b91ade2d48bdaf131f513a9a
```

# Methodology
Checking correlation address with decode input data and check address on API Hop Airdrop
```JS
const axios = require('axios');
const Web3 = require('web3');
const web3 = new Web3('https://rpc-mainnet.matic.quiknode.pro/');
var abiDecoder = require('abi-decoder');
const ABI = [{"constant":false,"inputs":[{"name":"token","type":"address"},{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseTokenSimple","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"token","type":"address"},{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseToken","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseEther","outputs":[],"payable":true,"stateMutability":"payable","type":"function"}]
abiDecoder.addABI(ABI);

const txMultiSender = "0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c";
web3.eth.getTransaction(txMultiSender, async function(error, result) {
    if(!error){
        const decode_data = abiDecoder.decodeMethod(result.input);
        for(let i=0; i<decode_data.params[0].value.length; i++)
        {
            const checkEligbility = await axios(`https://airdrop-api.hop.exchange/v1/airdrop/${decode_data.params[0].value[i]}`);
            if(Object.keys(checkEligbility.data.data).length > 0)
            {
                if(checkEligbility.data.data.hopUserTokens > 0)
                {
                    console.log(checkEligbility.data.data.address);
                }

            }
        }
    }
});

```

So if my explaination help you and its was valid report you can tip me at : 0xdaa2fAA20484ef193F4678a802cEa58750638B2A

Regards 

0xtoshi

**Comment by hebelubes** [comment]
> Hello @hebelubes @shanefontaine i was found same this list address correlation, to proove this is truely sybil attack so iam finding disperse contract and found this tx [0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c](https://polygonscan.com/tx/0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c) this Tx show sending 32 Tx to correlation address and iam check address eligible and found 19 Address list (20) 19 + 1 Sender From Address
> 
> ```
> 0x65412637bb7841182fb1e8c6622ca3749061dfad (Sender From - Also Eligible)
> 0xa83a93e19a4c9e7d370f3287b199fa3dae25e644
> 0xd41de94e621ea8329bc0e0e37428a8d080127cf0
> 0x751fb9cb9e7f5e1e59104b1bcc8dd00cc82d59c8
> 0x22c1d82e0d3ba8087c2dfad766befe511184c8a3
> 0xec2b0d51600fb93a304016043825abc644e2baa8
> 0x27eb71cc17988eb77298072259d3855b4223c5ae
> 0x1af39fb2578c1fe55439840f586f7bed40e8126c
> 0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4
> 0xb75d94b05156938df46ab456e33ce4c9cdf93d73
> 0x84400c5e12bcbf953fb01f61695733ccc5f260bc
> 0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
> 0x736a4478d84aca7bb59558ee77aa05262059de09
> 0x4062e35c566233830abac6a75332feb0fc0e84cc
> 0xbc44b397e25780ecffac98fe217138c36baa6c8f
> 0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
> 0xb5d5cd6870d3e0211f8072a29648a738681195c2
> 0xb3b54dfbbe03fb44ce61331237195639cc309d5f
> 0xa36d9ec999e4a82d96141262f7aa3463a27475b7
> 0x2dc3162ac2d359f9b91ade2d48bdaf131f513a9a
> ```
> 
> # Methodology
> Checking correlation address with decode input data and check address on API Hop Airdrop
> 
> ```js
> const axios = require('axios');
> const Web3 = require('web3');
> const web3 = new Web3('https://rpc-mainnet.matic.quiknode.pro/');
> var abiDecoder = require('abi-decoder');
> const ABI = [{"constant":false,"inputs":[{"name":"token","type":"address"},{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseTokenSimple","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"token","type":"address"},{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseToken","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"recipients","type":"address[]"},{"name":"values","type":"uint256[]"}],"name":"disperseEther","outputs":[],"payable":true,"stateMutability":"payable","type":"function"}]
> abiDecoder.addABI(ABI);
> 
> const txMultiSender = "0x143583b0f2ea7abbf397b36a1c8330df309b45040086c7bb680ec06257f48c2c";
> web3.eth.getTransaction(txMultiSender, async function(error, result) {
>     if(!error){
>         const decode_data = abiDecoder.decodeMethod(result.input);
>         for(let i=0; i<decode_data.params[0].value.length; i++)
>         {
>             const checkEligbility = await axios(`https://airdrop-api.hop.exchange/v1/airdrop/${decode_data.params[0].value[i]}`);
>             if(Object.keys(checkEligbility.data.data).length > 0)
>             {
>                 if(checkEligbility.data.data.hopUserTokens > 0)
>                 {
>                     console.log(checkEligbility.data.data.address);
>                 }
> 
>             }
>         }
>     }
> });
> ```
> 
> So if my explaination help you and its was valid report you can tip me at : 0xdaa2fAA20484ef193F4678a802cEa58750638B2A
> 
> Regards
> 
> 0xtoshi

Thank you very much. I'm going to do if can get.

**Comment by hebelubes** [comment]
> @hebelubes
> 
> Thank you for the submission. Unfortunately, this submission does not meet one of the criteria for submissions:
> 
> > Methodology that has a non-negligible chance of eliminating legitimate users will not be considered
> 
> There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours.

All done, thank you.

**Comment by shanefontaine** [comment]
Thank you for your report @hebelubes. We have verified that the addresses in this report are Sybil attackers.

The report included 20 eligible addresses as Sybil attackers which means you are eligible for 2367.403547057800850941 HOP! When Hop DAO is live, we will make a proposal for this reward — subject to a 1 year lockup, as mentioned in the [original Mirror post](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc).


The qualified addresses are as follows:

```
0x65412637bb7841182fb1e8c6622ca3749061dfad
0xa83a93e19a4c9e7d370f3287b199fa3dae25e644
0xd41de94e621ea8329bc0e0e37428a8d080127cf0
0x751fb9cb9e7f5e1e59104b1bcc8dd00cc82d59c8
0x22c1d82e0d3ba8087c2dfad766befe511184c8a3
0xec2b0d51600fb93a304016043825abc644e2baa8
0x27eb71cc17988eb77298072259d3855b4223c5ae
0x1af39fb2578c1fe55439840f586f7bed40e8126c
0xbcb8295d192b1ee9b61b0c89cff33f8d840966d4
0xb75d94b05156938df46ab456e33ce4c9cdf93d73
0x84400c5e12bcbf953fb01f61695733ccc5f260bc
0x47944ed819868698065d01ee8c7b8d1ee42e8fb9
0x736a4478d84aca7bb59558ee77aa05262059de09
0x4062e35c566233830abac6a75332feb0fc0e84cc
0xbc44b397e25780ecffac98fe217138c36baa6c8f
0xe4d53f7d24ad19a03073b4d75ead4d2cb18201c1
0xb5d5cd6870d3e0211f8072a29648a738681195c2
0xb3b54dfbbe03fb44ce61331237195639cc309d5f
0xa36d9ec999e4a82d96141262f7aa3463a27475b7
0x2dc3162ac2d359f9b91ade2d48bdaf131f513a9a
```
