### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by ZagTheDestroyer** [hop-protocol/hop-airdrop#172]
# Related Addresses

0x552455c18DAFfF303Ee34E8278DD68B9E7DF06a7  / Main wallet

SENT COINS IN VALUE OF 0.03 ETH ON MULTIPLE WALLETS LISTED BELOW
1. 0x9eD74AE301cF2aB26e2598032d77D71Bd2036364
2. 0xF963188C94B46Fdff4f8bea349548491e49C21b9
3. 0x7E158e91699091CEc919500E5FC3B3C0c932DB79
4. 0xc2A22dC9c3c24680435bCc3aAca56A79FC1723B7
5. 0x31FA40e2064F16295810DAFe5A6d4E6813Fa71ae
6. 0x2443b35326527af5FebE83A11884924Ca0fE5705
7. 0xAB670Bd61d10c638203308D9466dba5125A7e728
8. 0x5D989545C7E5c5c5DBAd532f61Bca17472f8B28A
9. 0xE99854186B02300A53d39c9323Cc95BBFc803757
10. 0x06C864fdFc4F12d592DbE2c1641973192A66C6B6
11. 0x8610A16881B6dA14f41348518A731d761Cc9622e
12. 0xeE059D48EcA70639a29FD1f6D0261eA1e81b07A3
13. 0xd04E7093f1edf14321128F4DfdBda12876A112a5
14. 0x40Ee0247aDDe97283D14ABb00016eC88CC459716
0x9A10e54923F44b8bbebAe73345E46DFB53f47898
0x6cc3688b23F5b263560BC1a097f76239F0faf6f2
0x766880Bb5156f4183996F97850D74CD17a5bE049
0x7cE4E26c0ecc1C157069c488a6DbBf367A6c6E5F
0x35593374B060D8F7adF0e917B83cbdFc5D3b4C3f
0xc13f08F0A0B6AEFEc429a173037Cf0b30517C633
0xE3BEd347649D34828aBF0BD089946E0b6CCCDe67
0xd04E7093f1edf14321128F4DfdBda12876A112a5
0x3cCdE524937D7D8F05C647225394A6EaDF4BF570
0x9Fd9A3f46e1C7b3d188c7cC45821Bd94f533d16e
0x1Ee081381ACE1Bd5B857ce8524842dFD05A1e0bc
0x5E0dF00BCA5F088b6ebFb87cda3B7B76bA7685d3
0xD782471463694257B1a2cB6eB217C2Fb9c62622a
0xa56B217C9a5e75782a87fCcc32e9d638dd402466
0x14e2796F4F294Aa1C08E67b85D6Bdc0a95284888
0xED7C6717DD492d0c96B5bC649D884233Ef58d5fF
0x9E060eC16aA604513fd1888d8FeAeb24A5f0aF63
0xb06bbcc4113dd62bb389b084372496D04F62652b
0xC6260d6653342ad585d3F657342944F48472a14A
0x467800E33f361809307c1ADa9Ae6E83d05C4eF12
0xb5383D67C5f4b877768bb34a196Cf53fC4216899
0xA392c10a19D01418c70fb59CCf17817c709aCFC6
0xdec28a302c34D36C72c1A2209dDAeB0dECF5bC25
0x46954ef66eAc6f7B09474D922CdF10cedB994B86
0xfc46ea2DD1e794a5480F6f7f654caE9B6Cb45565
0xc65B6755fA66C6439E3d1Da4e960FF624c4909C2
0x9E78CbD4a4c79B4544391ae0b6e7AC9636754718
0x60E4A54DDa2B1F452e0C2aF5c280fAE366999193
0xeE8ef097b6bB276C40dAe08c4599AcdAD9006260
0xDE186E0e94256109BE21BB0c398E2618B030b88f

# Reasoning

Its simple.User transfered fund to wallet 1 and then splitted to multiple wallets and bridged. Found through small LP tokens

# Methodology

Wallet and tnx tracking through ethscan etc.

# Rewards Address

0x72F287f0b25CA98C793cD25b3d988A6f08D5BD86

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
