### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by 0u8120u812** [hop-protocol/hop-airdrop#179]
# Related Addresses
0xae8453d0d4c581dec82dab0ff1c5048690bd6c12
0x6ef3f0ff397c3de367c6ca2cc3e6b6955e7993a5
0x5eeA118E75f247014c6D0E990f02a0c254EDC852

# Reasoning
These addresses were exposed in the Ribbon Finance airdrop scandal on October 9th 2021 on Twitter. All three addresses qualified for 38,000+ HOP each. Addresses have farmed multiple airdrops. RBN, 1INCH, LYRA, Optimism, Arbitrum (no token yet), +more. 

# Methodology
See the following tweets: 

https://twitter.com/ZoomerAnon/status/1446947030325071875?s=20&t=uxFzhZXL9JMjmd1Mc_AkZQ

https://twitter.com/0xSisyphus/status/1446955284291801094?s=20&t=uxFzhZXL9JMjmd1Mc_AkZQ

# Rewards Address
0xD44A0bf0d00FF02BdF7e4594DdA349732DD800E1

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 1 of these addresses is eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
