### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Lee0130** [hop-protocol/hop-airdrop#182]
# Related Addresses
0x4FFC3884669E442e5d2F687B2C70504D942ba129

0xEaEA403F57CF1d143258AA5f30c53c313dB0bb14
0x620087aa7d016dA502Bed5841B71aee3C4887AC6
0x6B58bC920199eEfc3048A02d113627e6e0226f50
0xD1d399a5AB77CE9F481c7f6cD5AF8b96d0341dbE
0x6C1bB12D45851E34e63D3aEc1367702A2A01eF9e
0xdC6B8d16a7Bc3b95294d71b42f288B4fe14181Da
0x24A85F7af097F169Cfa8CB101D6Dd6dfcA96cab5
0x6A4f118AfE5eEfbEeB1591E516b3c9a8FaBE6026
0x8cE2410e46b27CebA76d7e8837b0D00b650Fdd42

#Reasoning
All the addresses are funded by 0x4FFC3884669E442e5d2F687B2C70504D942ba129 with  ETH around May-02-2022 07:11:56 AM +UTC. Then perform addLiquidity.

#Methodology
I found the the address 0x4FFC3884669E442e5d2F687B2C70504D942ba129 is transacting with lots of addresses eligible for airdrop.

#Rewards Address
0xc56C121B52ED2688e4e08906Bc7cDebc4d9C198e

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.

**Comment by Lee0130** [comment]
I submitted it 7 days ago and someone else copied my report address
