### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by xuebb512** [hop-protocol/hop-airdrop#183]
0x1eBef03483030dd746c0BBa924E828Ce2C0534ea 
0x76cAbCB35A953912F95b47ef2285A156d527C709 
0xd98a122E466cDD6967770d5aA482e8dfae31419a 
0x1318FBa089731549275532137F30ad878CeA9e49 
0x34C65D21Dc2dEd4afAe9A1f86b9536485B3dAA82 
0x663736e59082689046799b2fd49e724A84b51d7F 
0x457dA487cEEE7D89bdC85848d405158A77A44bC9 
0x901cbCc34784426a82b6a602AEfA98fe0ba7c59f 
0x7c43214bF9Ef79Ff1FcbC0E477E0Dc36897Db326 
0x19275BEb75fb14Ce2Ed58b684Dc286F402721C58 
0xb700E57a071a939EC2F68707812d6Bb84f276d18 
0xc41C96d3f7fd42039C050C9e9C9842dE4845FDD9 
review188.eth 0x2d58E5e7380b801A0Af9C133890981C5EdE5f248 
ziyia.eth 0xe92A0A5C8fEf3BE8722C0Eb0D29a53eE505B95DD 
52o.eth 0x0A47A2e744Fb1095A5F4C590F659D5b6BFf4b35c  
0x5D258ae1c803c9ee80c068f0E27b534b5d063B4f 
review888.eth 0xc15d7ef92A7BCDA3D64B1465947bD446d671EBB3 
sbf777.eth 0xfF993ac38A6eCf53572964eD747A16964a17c1F3 
0x6fd3ba02D46f0cD64dC40Dc945D2229eA5824255  
tony1386.eth 0x6fd3ba02D46f0cD64dC40Dc945D2229eA5824255  
woogle.eth 0x4abDF782327d3447f614525C842571E8172ce5a9  

All 21 addresses posted here belong to one single individual trying to gamble the Arbitrum and Hop Protocol airdrop. 
On Apr19th, 2022 at 3:14pm, about one dozen wallets sent over 0.03-0.04eth to wallet 0x1eBef03483030dd746c0BBa924E828Ce2C0534ea at roughly the same moment.(from etherscan.io)   
Wallet "0x1ebefo34......34ea" has also been sending ethereum with the wallets with ENS name.  For example, on May 5th, 2022, wallet "0x1ebefo34......" sent 3 ethereum to 52o.eth, and immediately wallet 52o.eth sent back 2.5 ethereum. The wallet owner tried to gamble the Hop protocol airdrop by providing equal and tiny amount of liquidity.     
Most of the data come from etherscan and arbiscan.io research. https://etherscan.io/address/0x1eBef03483030dd746c0BBa924E828Ce2C0534ea

**Comment by xuebb512** [comment]
reward address
0x572Ae335AaC8F32DC1ac53B97Fe248C3c9B3aF77

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 7 of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
