### ISSUE TITLE
Sybil Attacker Report (more than 50 wallets)

### ISSUE THREAD

**Issue by Iseeyou23** [hop-protocol/hop-airdrop#190]
# Related Addresses

Main wallets (used for transfering coins to multiple wallets ) > bluecapital.eth, 
0x6455daef1ce0898d61ff34fbbd3b6c8b2ebf6aa9 , 0xB4aEF20183f6da0dF05506965c46f16514Bc434b ,
0x7d4af955c68ae03B32e586D65A9c3e132C62cA68 , 0x9654dda28c96fe9e28b93542c3c9a68f59f7f766
0x415740a259977c17f8d4fe8ebcfb9a3c2ac55467

bluecapital 0x95f6B040A013d89883e36545dF53844dbda4D8D1 send funds directly to these wallets >
 
0x0B3C92d05EcAEA81885F04B76b696160572832B0
0x71a242c892557626399147Bf0d54Bfb20128E86F
0x170582D968Caaa2ADa012B306aD1FECb73d04d8c
0x802BFaD35a9FEcaB66B9A0210505617d7513d1c3
0x69fbC77E6453D0b207835e117cF1C2a26101237d
0x9A41885b73c07EDD0c82345C37C5907E0A5A3F8f
0xCF0444E6aBFcf4a81A76F038648bBa502cb57C02
0x281b546B7395D60a1542beb92776c97A0b45F191
0x71c025F3AB087D33B16CBff698add01EA5DfAe02
0x13e748107031f5C21E805D9dC0e8007B26B2f96c
0xF10a3317afADA2a7dBC5405638EBA8050DF562d7
0x5e9f2eAa3E2C9f095987f0ABb93C8336Ba24671c
0xa84FDae87e7887B926eb4f0f52313D60aEEa7364
0x8163b6E425A0123Cb607c6ea13AE27cDD550ed8b
0x500e48B5D5F7440160E2955240c15abA806Fe375

FROM 0x415740a259977c17f8d4fe8ebcfb9a3c2ac55467 to > 

0xd73832DD55637305a9c0EB140e25d87e2CEe13c5
0xd0d970Cf534E0Ab732acb6266583530454c3365D
0x5D83bdEFa5856F538C5fa2B8a4bFbddBF11E2664
0x094b5A6F2612d82e8721aD4EE6513e81ebB1c88d
0xBD2dDc11E26D6254c1c25e319c7999dB83972022
0x8abfc3cF44068698e6ac030529938Aca66D7Cf13
0xD3ABe6f63664e1a4F6735D636588a4bC98Fc5F5f
0xB4aEF20183f6da0dF05506965c46f16514Bc434b
0xD7dC1C602241D6551de6CFAf55c2da7D6Be3F146
0x30FFC6d905B387aACb20aFf2040712B4E1ea51b6
0xBef9a53506046C632C2D299b03475957a0BC554D
0x44bFf81fbF7D5e44c09Df1e33bd6A422CF9f137c
0xac11d582eE82dEB0153ee40e5d6C5Ac2E6ca23F7
0x19Ee36b57cC793C3185265EBf9EDaC3B96A32C5d
0x7951772Dbbb5e63D877A92F20D63032EC00417ff

0x6455daef1ce0898d61ff34fbbd3b6c8b2ebf6aa9 recieved
the funds and then bridged and created hop LPs on all of them > 

0x6Ac9689Fe3b476dfb4aE5FE27bC5D30CB4c810a9
0xF10A97Eb9BfED1394f06eB433B9D7C733f7a17e8
0xD37866070D719ef8fE99669Ac1459e74bAae0Ab9
0xbC5c6d750f023790beBEC4d7219cb1cc7f0500cD
0x224cE3dd0c5384c793cC3649bd0008d8B8C29375
0x5F1Ff225B2b5b80bE165596f7C2FaD3ddaF4973B
0xff994F60980Ae3F7E9cF73e11aD5554A646851E9
0xA58678D6C7e4f12411A222619641aEb4240f0C5C
0xb57AB710952770756999378F8d94e5c290257C0e
0xD4A7Ba62da446faC153388B0855b97b88660151C
0xDa87269fC798806dcE15536F457C6d3b5c2cB3f8
0x30019fa6fef048c91165e29Cf9C26D419e59f97a
0x9cd15754296A98289840FcA77f2065b192A92cC5
0xd8e987875cf3496a77793b0214c00700caD50adb
0x18cF98aC15c6a6A10A4385b178E010dF1830440d
0x29B4f377789c269DC0910C99DD7276dbB3E51d1e
0x3aFf39BE5433A2038cd97A37caDaa29D1cAE6482

0xB4aEF20183f6da0dF05506965c46f16514Bc434b (connected with bluecapital) , transfered funds to more 
wallets then bridged and created LPs > 

0x9bA624a70958427a2629Bc746FBaEdc6310da925
0xE06E0aE7e09f848079C60F48DcD74f74280C0e8f
0x956E9FfB988c3e64C9055ef024c2e77538684239
0x4F1be60308037b9D263E2AE81CAfbd49c0027a97
0x24F752Ac90f28e443bBefC93C63e4DFBE62Fbf4e
0x7951772Dbbb5e63D877A92F20D63032EC00417ff
0x16a45B34bABaf43e1E74b52fccFC2B2A07E6Af68
0xb49287eD0E4fCd3C24Ac5ad7511C10eb96f4B181
0xFb60E3251b30f2c1db0e310CD2F1b75f84B28543
0x16a45B34bABaf43e1E74b52fccFC2B2A07E6Af68

# Reasoning

Sybil Attack from bluecapital.eth
sending fund from this w. > 0x415740a259977c17f8d4fe8ebcfb9a3c2ac55467  , to main wallet
bluecapital.eth
0x95f6B040A013d89883e36545dF53844dbda4D8D1 (bluecapital)  main wallet)
then splited funds to multiple bigger wallets and then inside those wallets to smaller wallets.
Attacker used 4 wallets to distribute funds to multiple addresses, on those addresses he bridged and
created LPs for purpose of getting airdrop on multiple wallets.
Inside smaller wallets are even smaller wallets or wallets that again serve as a distribution to multiple wallets. The attacker was smart and took his time but the pattern of small LPs gave him away.

# Methodology

Manually tracked similar LP tokens inside the pool.Then found connection with multiple wallets and 
continued to manually search through tnxs and wallets. The attacker created 4/6 main wallets , i then
tracked every outgoing tnx to find that all the wallets above are connected and all eligible for HOP token,
. Used onchain data to spot some patterns that attackers used.

# Rewards Address

0x82742CC8A0dF025Ff7B6bbdd22429A351FA2DE7c
Manually tracked similar LP tokens inside the pool.Then found connection with multiple wallets and 
continued to manually search through tnxs and wallets. The attacker created 4/6 main wallets , i then
tracked every outgoing tnx to find that all the wallets above are connected and all eligible for HOP token,
This probably goes even deeper but got stopped by some CEX hot wallets.

**Comment by Iseeyou23** [comment]
REWARD WALLET > 
0x82742CC8A0dF025Ff7B6bbdd22429A351FA2DE7c

**Comment by Markfxx** [comment]
i think the team says LP is not counting as a Sybil because they only got proportion based on how long they put on. can you make it so only bridge users are on the list?

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only one of these addresses is eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
