### ISSUE TITLE
Sybil Ultra Attacker !

### ISSUE THREAD

**Issue by Iseeyou23** [hop-protocol/hop-airdrop#202]
# Related Addresses

 
0x644Be8a25BE30A21E2DFFeAE4FC43937fBCf3efd > main
submain > 0x8bf3C28EA512F5E9CCE147bB98D18cB4E10bbc22 , 0x797fF69d2B53Fd720beb9F13bB77Ad827a7123cf

Sent from efd to 0x797fF69d2B53Fd720beb9F13bB77Ad827a7123cf  and then from one wallet to another (timestamp
54 days ago ) >

0x529A6586c4Ef4303f2f856e2201D364420147b64
0x1Cf124BDe71729f92e8Bbe76fB0a453b1A992310
0x113f35a8070510B149caBE03A630ca4c6A7883aa
0x0FDb00FD1F05EcAF2175E4E924feEffC0C4b4016
0xc03D49750b3a3087dde2eC8BD0b7398472C578d2 
0x73EDD20C2480cb6Ee825c24a8730e11cDb314690 
0x9985d8d8d225C2A6d7D0D99ef63FB34c3105fBe2 
0xFc1c64c669F1C00974633F3d30C0176D0D10578c
0x23aD589F2347732509ea62A0Ce9458e493072490
0x7e3394Cf1fe9801179807C7931f61282De192DF1
0xAc6c9C7164daDbC2D3AB717C1263239417FFD666
0xD6ac80DB2935270276FB967426372E100ab1DD2f
0xbc644d131511EBa91F01E88004062Ac99682596f
0x619179884b2C59887c0b30BB39fB37B5A01c9f94
0x52d11cDE474f24974E82BC256589a92E9385F2cd
0xA67c232DA87Af682D36c772256eBCaF8197e5eec
0x68e925b16eac510E3b7E24E5c506102850921b73
0x0C167A439ade4F89ef3606341435529f384c2ce7
0x58DA8e3Dc913406bE243dEc8F7f24e7843780038
0x0FDb00FD1F05EcAF2175E4E924feEffC0C4b4016
0xc03D49750b3a3087dde2eC8BD0b7398472C578d2
0xcd3e81f2dc97e53c3a8cd1ef253f64dd4f9aea26

transaction from main wallet to
 0x8bf3C28EA512F5E9CCE147bB98D18cB4E10bbc22 , then attacker sent to the next wallet and then the next etc. All seen
in wallet transactions inside the wallet (55 days ago)  > 

0x7bF9a2C396584097E703eF599343Ee961bdf9851
0x3eE4BDfb0762B0542e5366a5343719EFadd24927
0x886A95410f3F68ADBF4F72102245dC08Cf80862A
0x2C4fc66d169D0834bF913BF5Ab6ADB835394fA83
0x1CfC9522d7bAC5448B9045d023B5FA6349fa7a2c
0xCd3e81F2Dc97e53c3a8cd1eF253F64dD4F9aEa26
0x12420285fFA28B8d7670093ba6E43B4a874F2079
0x7A8272aB00Af34FC82B7C8A88db2C2E06D2cB576
0x7cC463Ff4116126dD08220D7742480BeDD9AB2F6
0x3F864D603d614376446bA1eca4f541bE86e12f24
0x3d607ccf2Fdd1a512133Cb2aD96E0af4c312d0b0
0xbcD915050B884c5342eFB249e4Acf4e924eab5eC
0x5aF1A40Ba40D0cF6C8E289fAd5b2dF497e8AA1c7
0x15866C967aF0Cc86d79F36022D3494727fCF639F
0xb97DbDeeB07930A44F65Db1cd4D887918cc69A42

# Reasoning

Attacker used one main wallet to distribute ETH to many different wallets where he then created LPs and bridged 
so he would be eligible for airdrop.He then distributed funds back to the main wallet and gave himself away
all incoming transactions from the 1day 20 hours ago are sent from attackers mini wallets that he used
to make alot of bridging and LPing.
Attack strategy > Sending ETH to main wallet then sending it to multiple wallets. 
>from multiple wallets he created LPs and bridged and then transfered the funds to the next wallet where he repeated
the process.
>all wallets are connected and have received hop airdrop

He used more then 100 wallets. Still digging deeper and will update full list etc. in the comments.

# Methodology

Used etherscan.io combined with wallet tracking too see similar LP token creation number. When i found the first
creation number i followed it through scan and got to the main wallet. Inside main wallet i saw alot of small transfers
at the same dates (2 days ago and 54 days ago) . I went through tnx and saw that he is actually sybil attacker and have
created many wallets to bridged and create LPs.

# Rewards Address

0x82742CC8A0dF025Ff7B6bbdd22429A351FA2DE7c

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
