### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by zzupbine** [hop-protocol/hop-airdrop#205]
0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) with 8 connection wallets 
FIRST 8 WALLETS CONNECTED WITH AIRDROP START WALLET:
Arbitrum chain:
1 )   0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) =transfer(ETH) 0x23f6b54bdcc271f8f47d39d18095a64ca45bc68a (airdrop)

2 )   0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) =transfer(ETH)  0xabf19858ca23664b043fe492c14c60fe70003645 (airdrop)

3 )  0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) =transfer(ETH)  0xb741cdf956938c631945275488ad2485e757c480 (airdrop)

4 )   0x7e638248e5279bba56f2966bd05af4f001898909( airdrop) =transfer 1ETH to 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet)

5 )   0x7fd6d2761eab2317be33285ac1095b11a1bf886a (airdrop) =transfer 1ETH to   0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet)

6 )   0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) =transfer (ETH)0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5(airdrop)

Eth chain: 
7 )   0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) = transfer (ETH) 0x8fe6490a02cc5660a23a62dd6232a96c4ca83167(airdrop)

8 )   0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) = transfer (ETH) 0x1245b933164054384f73d17895ef518a1bd87ecd (airdrop)

HERE IS WHAT I FIND OUT ABOUT 8 WALLETS

1.)Research of first wallet connected with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet):  0x23f6b54bdcc271f8f47d39d18095a64ca45bc68a:
ARBITRUM CHAIN
This wallet add liq in hop protocol Transaction Hash: 0x4a0497129453e8886d606144d1ce2bc45f8b32eb06aa1760ffd14d96664b287c
This wallet is also connected with 0x711f12231d16d96b083be22abdc97d9ab6c9f6eb(airdrop) transfer was made (Apr-28-2022 08:13:50 PM +UTC)

2.)Research of second wallet connected with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet): 0xabf19858ca23664b043fe492c14c60fe70003645:
ARBITRUM CHAIN
This wallet add liq in hop protocol Transaction Hash: 0x56ec0bae78a12cae282eda8dba4e26ee6bb4086d8566db2300cbbcd12343e469

3.)Research of third wallet connected with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet): 0xb741cdf956938c631945275488ad2485e757c480 :
ARBITRUM CHAIN
This wallet add liq in hop protocol Transaction Hash: 0xce279d13ce983f45c808167033d4c35eddef0bcf3414eb7cdd1c651cbdd3409f
This wallet is also connected with 0x8d11e36ef592f0702f14327bf7a5b182bc3a40db(airdrop) transfer was made (Apr-28-2022 01:52:01 AM +UTC)
ETH CHAIN :
this wallet is also connected with 0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5(airdrop) transfer was made (May-18-2021 03:06:14 AM +UTC)
this wallet is also connected with 0xf17e6b621861990f096b60172b3d700fa9ccec85(airdrop) transfer was made (Oct-30-2020 02:02:13 PM +UTC)

4.)Research of forth wallet connected with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet): 0x7e638248e5279bba56f2966bd05af4f001898909:
ARBITRUM CHAIN
This wallet add liq in hop protocol Transaction Hash: 0xbced4908ffa9faa0fbfa523d5f046e04b9dd47f2ee1f8d736fc3431576c5ff6d
This wallet is also connected with 0xe91091c074a4033734a387a52573fdb66e3cd092(airdrop) transfer was made (Sep-11-2021 06:48:22 PM +UTC)
This wallet is also connected with 0xf527277ddc787974e57fc195a0ed5c86cf5ddeec (airdrop) transfer was made (Sep-11-2021 06:49:47 PM +UTC)
This wallet is also connected with 0x1ed09b8b375f1c7a59a78a16338597564ed3d87c(airdrop) transfer was made  (Sep-11-2021 06:52:19 PM +UTC)
This wallet is also connected with 0xa31d16b2bca58332b4af97a257ebcea195acec9f(airdrop) transfer was made (Sep-11-2021 06:56:41 PM +UTC)
this wallet is also conneceted with 0xbb8553c897849f7190377a9ce7683fcb78057c85(airdrop) transfer was made (Sep-11-2021 09:37:39 PM +UTC)
this wallet is also connected with 0xc2214c9cfa3666867fc4e5eae2e2bd4928ce0b8d (airdrop) transfer was made (Sep-11-2021 09:39:24 PM +UTC)
this wallet also make next transfers to following adresses:
0xdc5ec04293c1a05f9b933d849216cef9cc7333e5(airdrop)
0xcb206a0a68b168f8cd60ece42bb7f8e9e4990d57(airdrop)
0x06612a5fe90b5638c9451bb0eec69cfd1ada7647(airdrop)
0xaf8ff3ed5bc303cd2710080f320b28edcdca6542(airdrop)
0x675d696d28451f9b07090bbb6f569f9011563a80(airdrop)
0x29ec294cca2f38cda6b4b2199627946ce61df131(airdrop)
0x7d261990f425c7b26a2586151051028e408220cf(airdrop)
0x0d58e7275c771ae90a4e440c3753c33bed3d91cc(airdrop)
0x8d625569e04a178e0eaeacbe5d222e4f52851253(airdrop)
0xfa9af4db3bbf3f60ae74ee871f660bbcb5a5257e(airdrop)
0xaadc4e67bfa85e7575f6f7f399eb28bdbfd803ce(airdrop)
0x3616f643cc52e59d3fa0d72b161be53691054ea2(airdrop)
0xaa6311823491bf912cb1b105273bd71b83cd4378(airdrop)
0x3616f643cc52e59d3fa0d72b161be53691054ea2(airdrop)
0x8c7751c07ccc062dab7863b6d2fd2d3b872b23c1(airdrop)
0xee9fc57d5808a212a199f587ec150c3b41ee72ba(airdrop)
ETH CHAIN:
This wallet is also connected with  0xb2b389b623398e3b1d7d7a3dd28c836e043f9d2a(airdrop) transfer was made (Sep-12-2021 06:25:11 AM +UTC)

5.)research od fifth wallet connected with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) 0x7fd6d2761eab2317be33285ac1095b11a1bf886a
OP CHAIN
This wallet is connected with 0x8fe6490a02cc5660a23a62dd6232a96c4ca83167(airdrop) transfer was made (May-04-2022 05:23:44 PM +UTC)
ARBITRUM CHAIN
this wallet add liq in hop protocol Transaction Hash: 0xcc835fdcec02f6727a2a38c49c05b57cb25ec5b4cbf8737b607d27cb03e6ad68 
This wallet is connected with 0x5e459b0e5f0e4df91b5920d8f128ba43690cb525(airdrop) transfer was made (Sep-11-2021 05:50:05 PM +UTC)
this wallet is connected with 0xec1e204c314be9d404804a99ccc9ce7d9796a25d(airdrop) transfer was made (Jan-04-2022 08:27:33 AM +UTC)
this wallet is connected with 0x4c37739c1927a8702bb4edb9d6214357070baf07(airdrop) transfer was made (Apr-28-2022 02:22:18 AM +UTC)
ETH CHAIN
this wallet is connected with few already known wallets and some new:
0xbe7ae9e43d4373bce5b2d9195bbe31f6a7a0db6f (airdrop)
0x755c72635644da821fe915118defc2acd8b87cd8 (airdrop)

6.)research of sixt connected wallet with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) 0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5
ARBITRUM CHAIN
this wallet add liq in hop protocol Transaction Hash: 0x4b34053f45a3d0f41025ebaea267b0677758a658f756c97efc0ee33cb01262d8
this wallet is only connected with already know wallets which are already eligible for airdrop.

7.) research of seven connected wallet with with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) 0x8fe6490a02cc5660a23a62dd6232a96c4ca83167
ARBITRUM CHAIN
this wallet add liq in hop protocol Transaction Hash: 0x26389d186e3171dee04c5d7964a2a283e58354fb0601de2a5e63ce49f285f69a
this wallet is connected with few already know wallets and some new:
0x833c8d1bf01456da0ed61d4deef6449fcc7e0c0a (airdrop) 
0x677413bb2101ae2a496f7067ffa1ecdd81c8c139 (airdrop)

8.) research of eight connected wallet with  0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet) 0x1245b933164054384f73d17895ef518a1bd87ecd
ARBITRUM CHAIN
this wallet add liq in hop protocol Transaction Hash: 0xb1400018b136a845bf6ea4b681829b2298e1d277e6e2460e636d878c01597143
this wallet is connected with few already know wallets for airdrop, nothing new here.

here is the list off all connected wallets from the start to end of resarch so you can follow the attacker:
0x1F1356Ff901845f4A57f87cEDA516825b4F251f3   (airdrop)
0x23f6b54bdcc271f8f47d39d18095a64ca45bc68a  (airdrop)
0xabf19858ca23664b043fe492c14c60fe70003645  (airdrop)
0xb741cdf956938c631945275488ad2485e757c480  (airdrop)
0x7e638248e5279bba56f2966bd05af4f001898909  (airdrop)
0x7fd6d2761eab2317be33285ac1095b11a1bf886a  (airdrop)
0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5  (airdrop)
0x8fe6490a02cc5660a23a62dd6232a96c4ca83167  (airdrop)
0x1245b933164054384f73d17895ef518a1bd87ecd  (airdrop)
0x711f12231d16d96b083be22abdc97d9ab6c9f6eb  (airdrop)
0x8d11e36ef592f0702f14327bf7a5b182bc3a40db  (airdrop)
0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5  (airdrop)
0xf17e6b621861990f096b60172b3d700fa9ccec85  (airdrop)
0xe91091c074a4033734a387a52573fdb66e3cd092  (airdrop)
0xf527277ddc787974e57fc195a0ed5c86cf5ddeec  (airdrop)
0x1ed09b8b375f1c7a59a78a16338597564ed3d87c  (airdrop)
0xa31d16b2bca58332b4af97a257ebcea195acec9f  (airdrop)
0xbb8553c897849f7190377a9ce7683fcb78057c85  (airdrop)
0xc2214c9cfa3666867fc4e5eae2e2bd4928ce0b8d  (airdrop) 
0xdc5ec04293c1a05f9b933d849216cef9cc7333e5  (airdrop)
0xcb206a0a68b168f8cd60ece42bb7f8e9e4990d57  (airdrop)
0x06612a5fe90b5638c9451bb0eec69cfd1ada7647  (airdrop)
0xaf8ff3ed5bc303cd2710080f320b28edcdca6542  (airdrop)
0x675d696d28451f9b07090bbb6f569f9011563a80  (airdrop)
0x29ec294cca2f38cda6b4b2199627946ce61df131  (airdrop)
0x7d261990f425c7b26a2586151051028e408220cf  (airdrop)
0x0d58e7275c771ae90a4e440c3753c33bed3d91cc  (airdrop)
0x8d625569e04a178e0eaeacbe5d222e4f52851253  (airdrop)
0xfa9af4db3bbf3f60ae74ee871f660bbcb5a5257e  (airdrop)
0xaadc4e67bfa85e7575f6f7f399eb28bdbfd803ce  (airdrop)
0x3616f643cc52e59d3fa0d72b161be53691054ea2  (airdrop)
0xaa6311823491bf912cb1b105273bd71b83cd4378  (airdrop)
0x3616f643cc52e59d3fa0d72b161be53691054ea2  (airdrop)
0x8c7751c07ccc062dab7863b6d2fd2d3b872b23c1  (airdrop)
0xee9fc57d5808a212a199f587ec150c3b41ee72ba  (airdrop)
0xb2b389b623398e3b1d7d7a3dd28c836e043f9d2a  (airdrop)
0x8fe6490a02cc5660a23a62dd6232a96c4ca83167  (airdrop)
0x5e459b0e5f0e4df91b5920d8f128ba43690cb525  (airdrop)
0xec1e204c314be9d404804a99ccc9ce7d9796a25d  (airdrop)
0x4c37739c1927a8702bb4edb9d6214357070baf07  (airdrop)
0xbe7ae9e43d4373bce5b2d9195bbe31f6a7a0db6f  (airdrop)
0x755c72635644da821fe915118defc2acd8b87cd8 (airdrop)
0x833c8d1bf01456da0ed61d4deef6449fcc7e0c0a  (airdrop)
0x677413bb2101ae2a496f7067ffa1ecdd81c8c139  (airdrop)
new 2 wallets add 08.05.2022 
0xc5fd479180991999032d53b0c876b9f0a0a7a922(airdrop)
0xf02ab538e0D02d167E04b0d294cE6A2e3544D861(airdrop)

[hop rewards bonus.txt](https://github.com/hop-protocol/hop-airdrop/files/8645970/hop.rewards.bonus.txt)
my wallet  for reward 0x0BC65e2Dae05097F5E9BF57886149D2A347F48C9

**Comment by zzupbine** [comment]
4.)Resarch of forth wallet connected with 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 (airdrop start wallet): 0x7e638248e5279bba56f2966bd05af4f001898909:
ARBITRUM CHAIN.
here you see that a lot wallets was made for airdrop, but today i go futher more into it, and find out there are new wallets.

0xf527277ddc787974e57fc195a0ed5c86cf5ddeec(already on the list)  is connected with new wallets:
0xc5fd479180991999032d53b0c876b9f0a0a7a922(airdrop)
0xf02ab538e0D02d167E04b0d294cE6A2e3544D861(airdrop)

**Comment by shanefontaine** [comment]
Thank you for the submission @zzupbine.

Can you please format your submission in order to very clearly show which addresses you are submitting? Please consider following the provided template.

**Comment by zzupbine** [comment]
> Thank you for the submission @zzupbine.
> 
> Can you please format your submission in order to very clearly show which addresses you are submitting? Please consider following the provided template.

Hope that help,
 0x1F1356Ff901845f4A57f87cEDA516825b4F251f3 
0x23f6b54bdcc271f8f47d39d18095a64ca45bc68a 
0xabf19858ca23664b043fe492c14c60fe70003645 
0xb741cdf956938c631945275488ad2485e757c480 
0x7e638248e5279bba56f2966bd05af4f001898909 
0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5
0x8fe6490a02cc5660a23a62dd6232a96c4ca83167 
0x1245b933164054384f73d17895ef518a1bd87ecd 
0x711f12231d16d96b083be22abdc97d9ab6c9f6eb 
0x8d11e36ef592f0702f14327bf7a5b182bc3a40db 
0x21ef4da62819f7ae485f650ad8fe21dd4776c1f5 
0xf17e6b621861990f096b60172b3d700fa9ccec85 
0xe91091c074a4033734a387a52573fdb66e3cd092 
0xf527277ddc787974e57fc195a0ed5c86cf5ddeec 
0x1ed09b8b375f1c7a59a78a16338597564ed3d87c 
0xa31d16b2bca58332b4af97a257ebcea195acec9f 
0xbb8553c897849f7190377a9ce7683fcb78057c85 
0xc2214c9cfa3666867fc4e5eae2e2bd4928ce0b8d 
0xdc5ec04293c1a05f9b933d849216cef9cc7333e5 
0xcb206a0a68b168f8cd60ece42bb7f8e9e4990d57 
0x06612a5fe90b5638c9451bb0eec69cfd1ada7647 
0xaf8ff3ed5bc303cd2710080f320b28edcdca6542 
0x675d696d28451f9b07090bbb6f569f9011563a80 
0x29ec294cca2f38cda6b4b2199627946ce61df131 
0x7d261990f425c7b26a2586151051028e408220cf 
0x0d58e7275c771ae90a4e440c3753c33bed3d91cc 
0x8d625569e04a178e0eaeacbe5d222e4f52851253 
0xfa9af4db3bbf3f60ae74ee871f660bbcb5a5257e 
0xaadc4e67bfa85e7575f6f7f399eb28bdbfd803ce 
0x3616f643cc52e59d3fa0d72b161be53691054ea2 
0xaa6311823491bf912cb1b105273bd71b83cd4378 
0x3616f643cc52e59d3fa0d72b161be53691054ea2 
0x8c7751c07ccc062dab7863b6d2fd2d3b872b23c1 
0xee9fc57d5808a212a199f587ec150c3b41ee72ba 
0xb2b389b623398e3b1d7d7a3dd28c836e043f9d2a 
0x8fe6490a02cc5660a23a62dd6232a96c4ca83167 
0x5e459b0e5f0e4df91b5920d8f128ba43690cb525 
0xec1e204c314be9d404804a99ccc9ce7d9796a25d 
0x4c37739c1927a8702bb4edb9d6214357070baf07 
0xbe7ae9e43d4373bce5b2d9195bbe31f6a7a0db6f 
0x755c72635644da821fe915118defc2acd8b87cd8 
0x833c8d1bf01456da0ed61d4deef6449fcc7e0c0a 
0x677413bb2101ae2a496f7067ffa1ecdd81c8c139 
0xc5fd479180991999032d53b0c876b9f0a0a7a922
0xf02ab538e0D02d167E04b0d294cE6A2e3544D861

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only eight of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
