### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by lbjcxbjyynl** [hop-protocol/hop-airdrop#213]
# Related Addresses
**#1**
0xec561dd73346f761d1c09f46999bc8ea1b1e95a2
0x99d6d24012361620bfa1a3f16d4e745066fc7c69
 0xce9cc2efb00a730009346b173045dba73fd3327c
0x15446371fe06e86fcd27b1f567491a3eee9c238e
0xdf23d6fd44249716a515bdddc81b82c18b915345
0xe6318ac14dc1235e01af21d354088118e15783ba
0x78e95eabc4f0115e87825e20ef040ad89d973f0d
0xc5ba2b86292a73830cfe7619f24f4fcab66e398b
0x42acf5773af88b0e49f413e10edf9bcef93c3805
0x97e5a15342e3c08dd8882dc8033be2d0271569c0
0x3cbf5a2ad28271f6ec30e0d891905e663b78b865
0x91d87e8ba48a0e40f7913305792541191f92404e
 0x6dae9dc6ee8a4e28dabb1acb019ae9bd4c7dd928
0xb08e71a3c5472d30a571dc0f04691d13611f7ae0
0xf935861a8b8cc6867eeb463d97b501c69d177092
0xf81d02a2797afd51c71225b07076f87b29bca025

**#2**

0xde88d146f61463d582262a1dcdf6ea1323aba34a
0x12cd3dca194161fe3535755075499f115982ee63
0x5cfc2c648ba36144644758f8d39553c0ce355fc6
0x27695076ef87e7749ee7ca387f47549ee55dade3
0x939bac3bad78752763be4dd1da19e8e70995a408
0x1ac81fdcd10b27d2af73ef0f097159cdf0f0aa8a
0xbb7bb43af885549f1bbf5724213ee48b40ebee83
0xbcc7e64d6b522ef804450000f5bb8d944c7ddd01
0x61c4d254051cdbf86dc71d13070a1b6e9abc2489
0xf20bb1ea28a496db525efbad28a23003c9d73724

# Reasoning

**#1**
(https://etherscan.io/token/0x5faa989af96af85384b8a938c2ede4a7378d9875?a=0x254b9c1d9789c69a356b2419fbeba8b364e66e8c
Please check this transaction, these 16 addresses claimed their airdrop and sent it to the same binance recharge address (0x254b9c1d9789c69a356b2419fbeba8b364e66e8c) when GAL was listed for trading a few days ago
The binance top-up address is uniquely owned by one KYC account and it can be decided that these 16 accounts are owned by one!)

**#2**

https://etherscan.io/token/0x5faa989af96af85384b8a938c2ede4a7378d9875?a=0x2e2d1786e24e8840a60f6ced55ab702961bb0ccd
Please check this transaction,these 10 addresses claimed their airdrop and sent it to the same binance recharge address (0x2e2d1786e24e8840a60f6ced55ab702961bb0ccd) when GAL was listed for trading a few days ago
The binance top-up address is uniquely owned by one KYC account and it can be decided that these 10 accounts are owned by one!)

# Methodology

I manually checked the top-up records for that day, and given that they were all eager to move the GAL tokens to binance for cash, it was straightforward to determine the attribution

# Rewards Address

Please provide an address or ENS name that will receive any rewards earned from this submission.

0x6CaB818DAaF4040476E2489A7ED29Ca685aD0623

**Comment by shanefontaine** [comment]
Thank you for your submission @lbjcxbjyynl .

It looks like most of these addresses were submitted with a detailed explanation in #308 . Because submissions of 20+ were considered before submissions of 10+, your submission is no longer valid. I will close this now.
