### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by wkx0** [hop-protocol/hop-airdrop#215]
# Related Addresses 

0x61e2c57fa38363e70823ceec7e431d00f07240c9 
0x383262bf9b85914023427f5a5c10fef1be50564a 
0xe9c298cc56976782374fbe153c3212febab6a35d 
0x49b8469a3aa6180d5a6b990f55f0e9e888303ea5 
0x7ecc026838c2cfa5ea11277bd875e92ea7347f35 
0x7e9fb2730c3e079f80be9e91dfb24412f1d2ecdb 

# Reasoning 
1. whether the first From address is the contract address
2. The transaction record is less than 20
3. ETH interaction is 0 - because the interaction in other chains, temporarily excluded and abandoned
4.  transaction records less than 20 
5. Addresses that have interacted with the HOP smart contract 
6. Establish a trading relationship between them manually

I drew a picture between them, in which 0x49b8469A3Aa6180D5A6B990F55f0E9e888303Ea5 is the actual controller of these addresses, the red part is qualified for airdrop, and All other addresses are interacting with ZkSync, Apparently he separated the addresses to get different airdrops so as not to arouse suspicion

![未命名文件](https://user-images.githubusercontent.com/58239466/167300253-99f1c205-6848-4889-a78a-a616bd71c9e1.jpg) 

# Methodology 
This is only part of the method, and the method is only for filtering, the final determination is manual

```def check_airdrop(address): 
    urls = f"https://airdrop-api.hop.exchange/v1/airdrop/{address}" 
    res = requests.get(urls) 
    data = res.json() 
    airdrop_sums = float( data['data']['totalTokens']) / 10 ** 18 
    airdrop_sums = f"{airdrop_sums:.2f}" 
    # print (data) 
    return float(airdrop_sums) 

def main(): 
    airdrop_dict = {} 
    address_lists = read_address("de-from-exchange.txt") 
    count = 1 
    for address in address_lists: 
        airdrop_nums = str(check_airdrop(address)) 
        if airdrop_nums in airdrop_dict: 
            airdrop_dict[airdrop_nums].append(address) 
        else: 
            airdrop_dict[airdrop_nums] = [address] 
        print(f"{address} {check_airdrop(address)}") 
        print(airdrop_dict) 
        count = count + 1
``` 

# Rewards Address 
0x126Fd0455D0B6DB5990bc7669A31b9470C7325Da

**Comment by cshav** [comment]
Sur plz report addresses which are in eligible list.. have randomly checked 3 addresses and are not eligible for hop airdrop.

**Comment by r4bbit2015** [comment]
> Sur plz 报告符合条件列表中的地址.. 随机检查了 3 个地址并且不符合跳空投的条件。

Hello, are you with the team?

**Comment by Markfxx** [comment]
You need minimum found 20+ address correlation

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only one of these addresses is eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

We appreciate the work put into the submission and the detailed report!
