### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by anondev204** [hop-protocol/hop-airdrop#222]
# Related Addresses

185 wallets with 20+ linked wallets used to farm the airdrop

[wallets.csv](https://github.com/hop-protocol/hop-airdrop/files/8647735/wallets.csv)

- `main_wallet` -> the address from which the transaction was sent
- `linked_wallet` -> the address to which the transaction was sent
- `trx_value` -> the value sent in the transaction
- `trx_ts` -> the time of the transaction
- `trx_hash` -> the transaction hash

# Reasoning
All addresses are on the [airdrop list](https://raw.githubusercontent.com/hop-protocol/hop-airdrop/master/src/data/finalDistribution.csv). The `linked_wallet` addresses have received transactions from the addresses identified as `main_wallet`. Majority of transactions were sent around the same time with the same value.

# Methodology

The first step was to pull down the top 1,000 transactions for all wallets listed on airdrop list linked in the previous section. Using Etherscan API 11 million transactions were pulled down to a local database. The key insight was realizing that the 166,000 duplicate transactions out of the 11 million must have been between the wallets on the airdrop list. These transactions were then analyzed to find the most often occurring `from` addresses and then grouped together by the `to` address to identify unique wallets. 

# Rewards Address
0x5f5922D129A6e74E6995320e31f7d10c506A77B8

**Comment by anondev204** [comment]
## Column Update

#### All the addresses in the file are the same as they were in the previous submission (wallets.csv). I am just adding a few columns to make it easier for the team to read the report. 185 wallets with 20+ linked wallets. 

(Note: the data is for Ethereum blockchain only)

Additional columns are:

 - `hop_total_tokens` -> The total amount of tokens assigned to wallet in the airdrop. (can see consistent amounts across many wallets)
 - `linked_wallet_trx_count` -> Total transactions for linked wallets. (Low count indicates farming)
 - `linked_wallet_first_trx_ts` -> First transaction for linked wallet.
 - `linked_wallet_last_trx_ts` -> Last transaction for linked wallet.
 
updated columns (same rows): [wallets_updated.csv](https://github.com/hop-protocol/hop-airdrop/files/8654354/wallets_updated.csv)

**Comment by shanefontaine** [comment]
@anondev204

Thank you for the submission. This is pretty incredible. Unfortunately, this submission does not meet one of the criteria for submissions:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Addresses can be linked by this if they are friends, performing OTC trades, selling NFTs to each other, etc. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours.

Additionally, can you please show all of the eligible addresses you are submitting in some centralized places, such as a .txt file or pasted somewhere to easily observe and copy?

I will leave this issue open and check back for more updates.

**Comment by anondev204** [comment]
@shanefontaine 

Thank you for your feedback. Completely understand your point about it not meeting the criteria. I adjust the methodology to eliminate any non-negligible chance that real users will be included in the output.

Specifically, I added another very important criteria when filtering the wallets, which is that all `linked_wallets` must have interacted with the same contracts or received or sent transactions to or from the same address on the same date and this 'signature' must make up a substantial fraction of the wallet's total transactions. This is illustrated in the final column that has been added to the file called `identical_trxs`. Some wallets may have a 1-2 more transactions that other `linked_wallets` in the same group do not, but they all share the same significant address + date signature in their transaction histories. As expected this correlates with the other indicators (low and similar transaction count, similar first trasnaction and last transaction dates across all `linked_wallets`).

I can not definitively make any conclusions about the addresses in the `main_wallet` column, so I am taking them out of the `txt` file you asked me to submit, but will keep in the csv file for your convenience.

Just to be clear, I am not adding any new wallets, just filtering the list I submitted previously. Overall the number of wallets went down to 1,176 total (31 main wallets with 20+ linked wallets). 

The official list of wallets is below in a `txt` file per your request. (spaces are used to separate the wallets into groups)
[wallets.txt](https://github.com/hop-protocol/hop-airdrop/files/8684185/wallets.txt)

The updated `csv` file with the additional `identical_trxs` column is below.
[wallets_v3.csv](https://github.com/hop-protocol/hop-airdrop/files/8684181/wallets.csv)

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
