### ISSUE TITLE
Sybil Attacker Report 

### ISSUE THREAD

**Issue by JomoScope** [hop-protocol/hop-airdrop#231]
This report is closed for further detail investigation

**Comment by Markfxx** [comment]
Nice analysis sir, big reward waiting for you👀

**Comment by ha514** [comment]
做的时候不努力，看到别人发空投了 眼红了 懒狗命！

**Comment by cakdemir** [comment]
I hope that the team will also correct the legitimate users that were marked as sybil attackers from the initial announcement. Thumbs up for your work.

**Comment by r4bbit2015** [comment]
Widespread conditions can lead to the misuse of a large number of users, such as funds for the same cex address?

**Comment by r4bbit2015** [comment]
Are Rule 4 and Rule 5 serious? Does this mean that trading at the same time is prohibited?

**Comment by JomoScope** [comment]
> Are Rule 4 and Rule 5 serious? Does this mean that trading at the same time is prohibited?

You have to meet ALL 20+ rules to be classified, which is more trustable compare using only 1 or 2 rule.

The rules here needs to be "AND" not "OR".

**Comment by JomoScope** [comment]
> Widespread conditions can lead to the misuse of a large number of users, such as funds for the same cex address?

Like i said, addresses needs to be meet all the rules above with plus 15+ more rules to be identified.

This is also help to identify the actually users only interact with 1 or 2 addresses

**Comment by JomoScope** [comment]
> Widespread conditions can lead to the misuse of a large number of users, such as funds for the same cex address?

We are not identify the addresses by single rules, it has to be meed the 3 or 4 rules at the same time to reach the level.

**Comment by JomoScope** [comment]
> Are Rule 4 and Rule 5 serious? Does this mean that trading at the same time is prohibited?

Not mate, meets rule 4 or 5 or 4&5 will not be counted, but meets rules like 1&2&3&4&5 will.

We judge those addresses based on important rules and use less important rules as additional help.

**Comment by cakoyo** [comment]
This is not correct. My account kiira.eth was reported in Group3. It clear that I'm not owner of these 300+ addresses. You shouldn't report without any detailed and convinced evidence.
