### ISSUE TITLE
I have been tagged as sybil attacker, But I am not. Please include me in the airdrop.

### ISSUE THREAD

**Issue by panchsutha** [hop-protocol/hop-airdrop#234]
# I have been tagged as sybil attacker, But I am not. Please include me in the airdrop.
```
      "0x1bfc5d3d41e78ed1f761876a00c596c40c481e03"
```
-->

# Reasoning

I got this address as a birthday gift from my uncle and using it for a long time in defi space. Please exclude me from sybil attacker. I used hop protocol for transfer my tokens between multichains. I am early and guine user. Please help. I can give u my id proof if you want.

**Comment by Markfxx** [comment]
Which thread that explain you as a sybil?

**Comment by cshav** [comment]
Sur you don't have even 1k vol.. You are not eligible for Airdrop condition.

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
