### ISSUE TITLE
Not sybul attacker, me a real cryto member and used hop for my transfer purpose.

### ISSUE THREAD

**Issue by jayaworld2002** [hop-protocol/hop-airdrop#235]
I am trying to reach hop discord serer for long time , i could not get any guidence on how to reach , hence i got link just now from discord support to raise my issue. I am not sybul attacker, i am real cryto member and used hop for my transfer purpose.

0xb6ca7a7c6034a8219af7ddb49739bd70ac62b20a. Please include me in the airdrop. I am eligible user and used for my transfers.

**Comment by Markfxx** [comment]
I checked you transaction and your volume only show below $1k 
https://explorer.hop.exchange/?account=0xb6ca7a7c6034a8219af7ddb49739bd70ac62b20a

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
