### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by nullsd** [hop-protocol/hop-airdrop#240]
### **Related Addresses**
 
20 related addresses:
0x600F9Faa8A2D39A710b28e2D0EC8a5daCC12B00f  (tanshello.eth)
0x34c0fd5F1dC4929549Ad414026Fc68060549f9C8 (superfinance.eth)
0x3082f27581a2449268a14af56d810cacd9984ec1 (superens.eth) 
0xdac3eb0E30562f14e565c8c1BA713f58B9EA59a0 (gitcoin001.eth)
0x5e41c8e8021cf36ba4f84126b0f9e54a7ba04a5b (gitcoin002.eth)
0x321df53adfc7cfa13cedad669bbf06b8013c7d5b  (gitcoin003.eth)
0xebb27880e21b574e1aceef0f51cc972ded2f19be（gitcoin004.eth)
0x42cd6699444fb08253bdbc4bfc1166b1bcdb8a14 （gitcoin005.eth)
0x5ba1cc771ba9241d0fc11e6e222450eedef4337a  （gitcoin006.eth)
0x3b793cf8fadaf22ede4c27b161d2a97afb590153  （gitcoin007.eth)
0x347f37f4ed042a208f1be1202aa0577b1d5f1a31  （gitcoin008.eth)
0x5fC9cdc8407d9d31260d52825d27115B5350a96e（gitcoin009.eth)
0xe76677c629aaa4fe6283c87fe4d75a24b59b384b  （gitcoin010.eth)
0x1bd62b3922b1163a1518c703ee278a9895833c0b  (gitcoin011.eth)
0x9605f460a115eceaa03604644687253e89539a6e  (gitcoin012.eth)
0x699e8d711E71cf976a101ACa2C9DE127fb2C44B3
0x9B2f16D79654B30a1d7Ceaa844B56f9f51cD2835
0xeAd8272fCA277E2c917b77ECD2a2daa0d171DfBb
0x3f9cFd0d0a07b1124418d1755BfDc3Ead16990f6
0x5c44EB0A0C1E813BE3083d55768F51cE61866BB9
![1b2e6e641c640f23fd1a13576c6699c](https://user-images.githubusercontent.com/105219872/167422620-efbc9f50-c490-4d9f-8854-10ecbc3212ba.png)
![04fa3d3870bed1f45467505924f7692](https://user-images.githubusercontent.com/105219872/167422630-f27eafa8-e079-49b7-9f7a-12e016671368.jpg)
![4fa50527cfb49dd7202a21988ec9a79](https://user-images.githubusercontent.com/105219872/167422635-49fb0ffc-1669-4b89-9454-742fcfc63f3e.jpg)
![8d41dc1f7b65a96deddd4c923c5f029](https://user-images.githubusercontent.com/105219872/167422642-4691f050-db6b-417e-8fbe-d0364b075ee0.jpg)
![22](https://user-images.githubusercontent.com/105219872/167422646-596e0e29-f502-4232-9d5d-cd7f1dcae953.jpg)
![33](https://user-images.githubusercontent.com/105219872/167422673-53892257-59d8-4f93-8214-5715020edfdd.png)
![92bcec517c9a7b9f30196ffe694e069](https://user-images.githubusercontent.com/105219872/167422680-d840c7b6-e346-4f68-8100-d4b19d1ad52e.jpg)
![8506726c336681eca301049463ecf0d](https://user-images.githubusercontent.com/105219872/167422693-2d5e8c44-d76b-4df3-80b8-1584a621159f.png)
![c2209d0e4044c5740688cd6cbf5d426](https://user-images.githubusercontent.com/105219872/167422696-7ad6f39d-8d30-49aa-a182-4716d32d8d40.png)

### **Reasoning**
three elligible for the airdrop Address : 
_0x600F9Faa8A2D39A710b28e2D0EC8a5daCC12B00f
0x34c0fd5F1dC4929549Ad414026Fc68060549f9C8
0x3082f27581a2449268a14af56d810cacd9984ec1_
send ETH on mainnet to anthoer 17 addresses that elligible for the airdrop. These transactions can find here:
[https://etherscan.io/address/0x3082f27581a2449268a14af56d810cacd9984ec1](url)
[https://etherscan.io/address/0x34c0fd5F1dC4929549Ad414026Fc68060549f9C8](url)
[https://etherscan.io/address/0x600F9Faa8A2D39A710b28e2D0EC8a5daCC12B00f](url)

### **Methodology**
I checked polygon's matic transactions with etherscan API and filtered transactions, where 20 recipients addresses and sender are eligible for the airdrop. Then I checked when and how this wallets interact with HOP.mutual transfer exists in all 20 addresses, please see for details.so this is Sybil Attacker.

**### Rewards Address**
 0x58B8288335cd4aA7A783b986D561fD0D68Bef496

**Comment by dextereth** [comment]
they regret buying ENS lol

**Comment by nullsd** [comment]
@shanefontaine @cwhinfrey checke it

**Comment by tryhard3eth** [comment]
> @shanefontaine @cwhinfrey checke it

you should check it yourself. looked into 5 addresses randomly and non are eligible for Bridging Airdrop.

**Comment by nullsd** [comment]
> > @shanefontaine @cwhinfrey檢查它
> 
> 你應該自己檢查一下。隨機查看了 5 個地址，沒有資格獲得橋接空投。


bullshit！these five are his trumpets,  he obviously doesn't have enough money to do it! so he didn't get aidrops. But it doesn't rule ot that is Sybil Attacker.

**Comment by nullsd** [comment]
> > @shanefontaine @cwhinfrey checke it
> 
> you should check it yourself. looked into 5 addresses randomly and non are eligible for Bridging Airdrop.

Aren't these domain names obvious enough?

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only eight of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
