### ISSUE TITLE
Wrongly identified as a sybil attacker

### ISSUE THREAD

**Issue by slipster** [hop-protocol/hop-airdrop#243]
Hi,

I used Hop several times many months ago and apparently now I am a Sybil attacker because I used more than one wallet, something which in your discord support channel I was told has been labelled as "shady" by the team, which I feel is incredibly bad advice.
When I am interacting with a new protocol I will never always use the same wallet in Meta Mask or Trust Wallet over and over again. This is good security practise to minimise my risk of being scammed of any tokens I have in my wallet, I have even read of people recommending you should use a new wallet for each and every transaction you make.

The addresses of my 2 wallets that have over $1k in transactions
0x9440a780Cd125cc12BD14EbcF7206777d638114f
0xeC85105F6CEA39Ac4b11A0d8391aD02a5D7764ED

I feel I have done nothing wrong apart from try and be safe with my own money.

Thanks for your time

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
