### ISSUE TITLE
Wrongly identified as a sybil attacker

### ISSUE THREAD

**Issue by gududefengzhong** [hop-protocol/hop-airdrop#258]
my dear project team. I am not a Sybil Attacker,
i have three addresses:
0xA3B9Fe8647aa9D7009B9A7Ad1D8D4A2381994eFa   main address
0x87f1d3359334A6c2FF5e189a91605eADe8E05459
0x84F665281B5Aa35b9CF5ebF47227Daf263f267aC

Kindly take a closer look why I am wrongly picked as a Sybil Attacker?
0xA3B9Fe8647aa9D7009B9A7Ad1D8D4A2381994eFa my main address, it is binded to my discord handler : moonedge#8579

thank you

**Comment by gududefengzhong** [comment]
other addresses in this group may be my friends' addresses. maybe we are connected by sending money once in testnet?i don't know.

![image](https://user-images.githubusercontent.com/7471735/167620164-d5d6ff21-8ea7-49f8-ae6b-3c0435ca7208.png)

**Comment by gududefengzhong** [comment]
last but not least, below is my tx, for your reference
https://explorer.hop.exchange/?account=0xA3B9Fe8647aa9D7009B9A7Ad1D8D4A2381994eFa

thank you my dear hop team for your kindness
god bless you

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
