### ISSUE TITLE
Sybil Attacker Report [Update (26) Address]

### ISSUE THREAD

**Issue by 0xtoshi** [hop-protocol/hop-airdrop#259]
# Related Addresses

All Address Related Sybil Attack Has 36 Address (Include LP Reward)
```
0x08528f40ab51be0c16b4f6179349099195c2e65b
0xf3df2825a6204003eb11c35498631593a204f938
0x4358d27024c75212432257f23580a530daa778a2
0x6b457600b015b2a2d8906daae9fb727e4113ea70
0xe680646122ff24da4fd9b786f92a0f67fa83a973
0x07f8bdd197a83ba37730763232533ec3e0839baf
0x9378cc93e726960c14823a67ef9f758dee58f19e
0x69be8b1535a614c5c0b354e519bd7b1b3906dba6
0xe549531cd49513c6a2192e9086e3d3c62f3414c4
0x7ad84fbc2b2af748559b6c5621bdbe7d3cd44c9c
0x6e3d52bba18bf356104513dd5f89a0bef9da52c1
0x3616583975ebb07605644e474ec6906581806861
0x07e4d37654c0af93e8300f302ae716b67b3b8080
0x17dc833838609da0607bbc30d7abd86979c765d3
0xa4a71e743891a7c77bd3299fc935f8309def245c
0xf7fcd95ec4c45a62d54bc3b5ef584b2134ff0281
0x6bc35cf94c31d8d14e31946d07f76620174fc2e8
0xb34732094b80a60d4d7bca43f300267275a6a4c0
0xd62e3cf9e9589777f32af1b5f72a18b18ffd9ca7
0xaf9c0ba5f2227de2adcc361718cfd9479c14c1d1
0xbe8b9b0f6239d2f2075a37bba1140edc389da602
0x46164a6e794c10c8f55d0dc8b20ed2b556e4b19c
0x9ab55e5f1adafd6988a7463bb821c03a08ffa3c1
0x736cead64c944ac1d6700836ca1a83653d65f6ff
0xc7921a6cfbc6b4f36bcd357e8944502a9231e647
0x98bb89f405e0afaf4c2af99554a9cb42777d74fb
0xc7921a6cfbc6b4f36bcd357e8944502a9231e647
0x83da03f007b990d925c156e2be9305d063f9b58f
0xdc335928bf2057c9602d854b98202bbf834c9215
0xb4ebcb96cd1fed748433c45ec2b13a6eb200714c
0x7be2fa997d883659eab123e36d523299379d498d
0x8213e411072c2489ff6f41bb3244ed500412969c
0x15de46ac5700b062c58c09b24cb74c12d023fbc2
0x7f0ddafdb68b9abe3343e2f48eb5b60b95ce6463
0xbf9488da00fdfbb70aed990ec83f1a6d36b9b05b
0x29904c63a8310085eb28cf079014948b3337128f
```
So Iam Filtering (Exclude LP Reward) Has 17 Address On List

```
0x07f8bdd197a83ba37730763232533ec3e0839baf
0x08528f40ab51be0c16b4f6179349099195c2e65b
0xa4a71e743891a7c77bd3299fc935f8309def245c
0x7ad84fbc2b2af748559b6c5621bdbe7d3cd44c9c
0xe680646122ff24da4fd9b786f92a0f67fa83a973
0xd62e3cf9e9589777f32af1b5f72a18b18ffd9ca7
0x6b457600b015b2a2d8906daae9fb727e4113ea70
0x29904c63a8310085eb28cf079014948b3337128f
0xaf9c0ba5f2227de2adcc361718cfd9479c14c1d1
0x83da03f007b990d925c156e2be9305d063f9b58f
0x7f0ddafdb68b9abe3343e2f48eb5b60b95ce6463
0x17dc833838609da0607bbc30d7abd86979c765d3
0x3616583975ebb07605644e474ec6906581806861
0x07e4d37654c0af93e8300f302ae716b67b3b8080
0x4358d27024c75212432257f23580a530daa778a2
0x6bc35cf94c31d8d14e31946d07f76620174fc2e8
0xdc335928bf2057c9602d854b98202bbf834c9215
```

# Reasoning

All address controlled by 1 address know "0x721d1fa38CA040A4E4a5496f6c65D392BbCc13De" on [Optimism](https://optimistic.etherscan.io/address/0x721d1fa38ca040a4e4a5496f6c65d392bbcc13de) And from Controlled Address Make Transfer To Address2 (has 2 txn receive from Controlled Address && Send To Address 3 ) and Transfer Again To Address 3 (its interact with Hop Router Contract)

# Methodology

Iam Creating code multi literation interact with address who has know sybil attack write on javascript (NodeJS) 

```JS
const fs = require('fs');
const axios = require('axios');
const ROOT_ADDRESS = "0x721d1fa38ca040a4e4a5496f6c65d392bbcc13de"; //Address Controllerd By 1 Person
(async () => {
    const CovalentAPI = await axios(`https://api.covalenthq.com/v1/10/address/${ROOT_ADDRESS}/transactions_v2/?key=ckey_2ff81c42792746f894a75bce3ba`); // Check Tx Outflow
    const TxList = CovalentAPI.data.data.items;
    TxList.forEach(async tx => {
        if(tx.from_address == ROOT_ADDRESS){

            const CovalentAPI2 = await axios(`https://api.covalenthq.com/v1/10/address/${tx.to_address}/transactions_v2/?key=ckey_2ff81c42792746f894a75bce3ba`); // Literation Tx Outflow From Main Address -> Secondary Address -> Eligible Address
            const TxList2 = CovalentAPI2.data.data.items;
            TxList2.forEach(async tx2 => {
                        const data = await axios(`https://airdrop-api.hop.exchange/v1/airdrop/${tx2.to_address}`); // Filter Only eligible Address
                       
                        if(Object.keys(data.data.data).length > 0)
                        {
                            //console.log(data.data.data.address); // All eligible has 36 Address

                            if(data.data.data.hopUserTokens > 0) // Exclude Liquidity Has 17
                            {
                                console.log(data.data.data.address);
                            }

                        }
            });
        }
    });

})()

```

# Rewards Address

0xdaa2fAA20484ef193F4678a802cEa58750638B2A

**Comment by 0xtoshi** [comment]
@shanefontaine no action for this sir only 17 Address was eligible on Swap And Send another has not meet criteria for swap and send so no more info should i close this?

**Comment by shanefontaine** [comment]
Thank you for your report @0xtoshi. We have verified that the addresses in this report are Sybil attackers.

The report included 26 eligible addresses as Sybil attackers which means you are eligible for 3516.699719009539755075 HOP! When Hop DAO is live, we will make a proposal for this reward — subject to a 1 year lockup, as mentioned in the [original Mirror post](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc).


The qualified addresses are as follows:

```
0x07f8bdd197a83ba37730763232533ec3e0839baf
0x08528f40ab51be0c16b4f6179349099195c2e65b
0xa4a71e743891a7c77bd3299fc935f8309def245c
0x7ad84fbc2b2af748559b6c5621bdbe7d3cd44c9c
0xe680646122ff24da4fd9b786f92a0f67fa83a973
0xd62e3cf9e9589777f32af1b5f72a18b18ffd9ca7
0x6b457600b015b2a2d8906daae9fb727e4113ea70
0x29904c63a8310085eb28cf079014948b3337128f
0xaf9c0ba5f2227de2adcc361718cfd9479c14c1d1
0x83da03f007b990d925c156e2be9305d063f9b58f
0x7f0ddafdb68b9abe3343e2f48eb5b60b95ce6463
0x17dc833838609da0607bbc30d7abd86979c765d3
0x3616583975ebb07605644e474ec6906581806861
0x07e4d37654c0af93e8300f302ae716b67b3b8080
0x4358d27024c75212432257f23580a530daa778a2
0x6bc35cf94c31d8d14e31946d07f76620174fc2e8
0xdc335928bf2057c9602d854b98202bbf834c9215
0x734246e1c9e352c6bba46d18c08d7b660f421d9e
0x9b47cb0e6d8e17f0f60793b542d32a8b065cbb04
0xb02248b9a53bc98827f77cf8dc312ca8a42c4fca
0x8e9e64680f14a095d1acbbd2c167cffa749f5179
0xd9698dd015887342a38ea6a98ad8f3e371061448
0x7a8ca0604b7a95ff8721d8b2b88429a0122e564d
0x32b028d4f50cb402c553b5929b29e7a181f6e1f2
0x8147c216e43bf3a5d475beeae98fcdb7220d0007
0x291997f1896d95890d788bd8f8ff5ff46c7677fd
```

**Comment by shanefontaine** [comment]
In addition to the data you provided, all addresses followed one of two patterns on Optimism. Additionally, their behavior on Hop protocol is very similar:

address | ensName | total | mainnet | arbitrum | optimism | polygon | xdai | totalVolume
-- | -- | -- | -- | -- | -- | -- | -- | --
0xb02248b9a53bc98827f77cf8dc312ca8a42c4fca |   | 2 | 0 | 1 | 1 | 0 | 0 | $9,637.81
0x7a8ca0604b7a95ff8721d8b2b88429a0122e564d |   | 2 | 1 | 1 | 0 | 0 | 0 | $6,155.21
0x8e9e64680f14a095d1acbbd2c167cffa749f5179 |   | 2 | 1 | 0 | 1 | 0 | 0 | $5,258.85
0x8147c216e43bf3a5d475beeae98fcdb7220d0007 |   | 2 | 1 | 0 | 1 | 0 | 0 | $5,049.26
0x32b028d4f50cb402c553b5929b29e7a181f6e1f2 |   | 2 | 0 | 1 | 1 | 0 | 0 | $2,936.69
0x08528f40ab51be0c16b4f6179349099195c2e65b |   | 3 | 0 | 0 | 1 | 2 | 0 | $2,751.66
0x734246e1c9e352c6bba46d18c08d7b660f421d9e |   | 2 | 0 | 1 | 1 | 0 | 0 | $2,638.57
0xd9698dd015887342a38ea6a98ad8f3e371061448 |   | 2 | 0 | 1 | 1 | 0 | 0 | $2,500.60
0x07e4d37654c0af93e8300f302ae716b67b3b8080 |   | 3 | 0 | 0 | 1 | 2 | 0 | $2,222.94
0x6bc35cf94c31d8d14e31946d07f76620174fc2e8 |   | 3 | 0 | 0 | 1 | 2 | 0 | $2,220.82
0xd62e3cf9e9589777f32af1b5f72a18b18ffd9ca7 |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,885.27
0x6b457600b015b2a2d8906daae9fb727e4113ea70 |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,667.65
0x7ad84fbc2b2af748559b6c5621bdbe7d3cd44c9c |   | 2 | 0 | 0 | 1 | 1 | 0 | $1,649.85
0x9b47cb0e6d8e17f0f60793b542d32a8b065cbb04 |   | 2 | 0 | 1 | 1 | 0 | 0 | $1,465.64
0x3616583975ebb07605644e474ec6906581806861 |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,371.63
0x17dc833838609da0607bbc30d7abd86979c765d3 |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,274.12
0x83da03f007b990d925c156e2be9305d063f9b58f |   | 2 | 0 | 0 | 1 | 1 | 0 | $1,218.11
0xdc335928bf2057c9602d854b98202bbf834c9215 |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,206.27
0x29904c63a8310085eb28cf079014948b3337128f |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,200.90
0x7f0ddafdb68b9abe3343e2f48eb5b60b95ce6463 |   | 4 | 0 | 0 | 1 | 3 | 0 | $1,188.81
0x291997f1896d95890d788bd8f8ff5ff46c7677fd |   | 2 | 0 | 1 | 1 | 0 | 0 | $1,171.39
0xe680646122ff24da4fd9b786f92a0f67fa83a973 |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,119.54
0x07f8bdd197a83ba37730763232533ec3e0839baf |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,111.49
0x4358d27024c75212432257f23580a530daa778a2 |   | 2 | 0 | 0 | 1 | 1 | 0 | $1,099.68
0xaf9c0ba5f2227de2adcc361718cfd9479c14c1d1 |   | 2 | 0 | 0 | 1 | 1 | 0 | $1,050.99
0xa4a71e743891a7c77bd3299fc935f8309def245c |   | 3 | 0 | 0 | 1 | 2 | 0 | $1,006.56
