### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Rayne-XYZ-Support** [hop-protocol/hop-airdrop#267]
# Related Addresses

1. **0x1c06efe1b692083d3d823687ffdc3b0e4332d12b**
- Used Disperse.app 
2. **0x02F54D7345c3E99D58B628f3EBE99A36EE682712**
- Used Disperse.app

---
# Address Batch

- Address 1: 0x1c06efe1b692083d3d823687ffdc3b0e4332d12b
- Disperse TXN 1
- [TXN; https://etherscan.io/tx/0xdedeec24cfa7675af829d2fffa12d611f79513943e6da6722ee61b28785e2229]

```
**0x1c06efe1b692083d3d823687ffdc3b0e4332d12b** used Disperse app to transfer 10,500 USDC to 10 different addresses— 1,050 USDC each.

1. 0x8b1cf708d9257552d600c18b1c249bb8ec145006
2. 0x086bD5A8Ce0C78e0F2D3170B19f93309F0Dbcb45
3. 0xa8fd257b8cfcfb17d6b43cc7576b747eaa933c1f
4. 0xe125bb6cac1eac72487e61caec1a864d0871a480
5. 0x1b4d45eb0e7f50df11fa30091b2bd2a15af4ebcf
6. 0x281ba367fbb848f13f3257f8009607cce77323d8
7. 0x89346a88bf1a57779cadbc897cdc3f56fb36189e
8. 0xd3cfb89bf95981c052384b33c331d0e02a472bd6
9. 0xe3ce3994f56c39d3d59b52622182315d629e9269
10. 0x15b11dd9302f420dc1ab7120ead4616e747a7762

```

- Address 2: 0x02f54d7345c3e99d58b628f3ebe99a36ee682712
- Disperse TXN 1
- [TXN; https://etherscan.io/tx/0x71425f24944cebc863c94a77e0317e2fb3cce4c180f676c18fb2af0b1e94132b]

```
**0x02f54d7345c3e99d58b628f3ebe99a36ee682712** used Disperse app to transfer 0.75 ETH to 30 different addresses— 0.025 ETH each.

1. 0x7A8cFA10452913e7dAa3920636987A3dDD80023c (28 txs)
2. 0xCDA69C882e1c4e6e44557D4590769C894703A498 (25 txs)
3. 0x808eE957f1D26A4FdEC57C6A3dFa066e8a41c90A (23 txs)
4. 0x5046B25Ec2B42E9C8554f9Cc94b056E57a13AEB8 (23 txs)
5. 0x9C7Eb3707d2b5078BC461eDDdFFef71464a3F945 (22 txs)
6. 0x94Ec9b292B153F046040766E46588664e1319DC4 (22 txs)
7. 0x6cC8839f1fD0eF79b8C788Ee677999446841Eced (17 txs)
8. 0x9E31c31C17ba676b009A55a0eE3C797e3ca09F25 (19 txs)
9. 0x4e334B6F2A56565514d733D2827F9C1820F52cFF (16 txs)
10. 0x2A1C9846FD452537992b0dBE7147a9F07aA3Cd05 (16 txs)
11. 0x26574904Ee4F836ae226642D673C1b057012627A (15 txs)
12. 0x02E2DB0D74f998141F341C4071ca936b6b0195Cd (15 txs)
13. 0xA08f91Df36d1492738E56759Cf8Af79e42C899e0 (15 txs)
14. 0x4a0d7D58b783d45988495FA4197137859CbE5811 (17 txs)
15. 0xaDf176bcd7C7f6fAD0Da0503C7063e2492B48571 (16 txs)
16. 0xc0BedF69cd9EE0F0978f90193A979c2901D3c4Ee (15 txs)
17. 0xD18A456a433BDb5DA4F4CBd39615FdD2F9D49986 (16 txs)
18. 0x0AD0a1A84d628A3A8bbe287859577F9F48a0FfF4 (15 txs)
19. 0x885F56ed3D8985c4128aC2CE8E315E31c74f7031 (15 txs)
20. 0xE68b04856ab8b27C58059D54382f6A584A0E014D (15 txs)
21. 0x8b1Cf708D9257552D600c18B1C249BB8Ec145006 (14 txs)
22. 0x086bD5A8Ce0C78e0F2D3170B19f93309F0Dbcb45 (14 txs)
23. 0xA8Fd257B8cfcFb17D6b43Cc7576B747EAa933c1F (14 txs)
24. 0xe125bB6caC1EaC72487e61caec1a864d0871a480 (14 txs)
25. 0x1B4d45eb0E7f50DF11fA30091B2BD2A15Af4eBcF (14 txs)
26. 0x281bA367FbB848f13f3257F8009607cCE77323d8 (14 txs)
27. 0x89346a88Bf1A57779cAdBC897CDc3F56Fb36189e (14 txs)
28. 0xd3cfB89Bf95981C052384b33c331D0e02A472BD6 (13 txs)
29. 0xe3cE3994f56C39D3D59B52622182315D629e9269 (14 txs)
30. 0x15B11dD9302f420DC1AB7120ead4616e747A7762 (14 txs)

```

- Address 2: 0x02f54d7345c3e99d58b628f3ebe99a36ee682712
- Disperse TXN 2
- [TXN; https://etherscan.io/tx/0x4cdf2a57f23c9b5661077e1cb484009d402ce85cfc3cf74ef4b19f1a34488407 ]

```
**0x02f54d7345c3e99d58b628f3ebe99a36ee682712** used disperse to send and equivalent amount of USDC to 10 addresses. (2,550 -> 255 each)

1. 0x7A8cFA10452913e7dAa3920636987A3dDD80023c (28 txns)
2. 0xCDA69C882e1c4e6e44557D4590769C894703A498 (25 txns)
3. 0x808eE957f1D26A4FdEC57C6A3dFa066e8a41c90A (23 txns)
4. 0x5046B25Ec2B42E9C8554f9Cc94b056E57a13AEB8 (23 txns)
5. 0x9C7Eb3707d2b5078BC461eDDdFFef71464a3F945 (22 txns)
6. 0x94Ec9b292B153F046040766E46588664e1319DC4 (22 txns)
7. 0x6cC8839f1fD0eF79b8C788Ee677999446841Eced (17 txns)
8. 0x9E31c31C17ba676b009A55a0eE3C797e3ca09F25 (19 txns)
9. 0x4e334B6F2A56565514d733D2827F9C1820F52cFF (16 txns)
10. 0x2A1C9846FD452537992b0dBE7147a9F07aA3Cd05 (16 txns)

```

# Reasoning

All of the above addresses (grouped in batches) had tokens dispersed to them from one central wallet. 

Both of the wallets are linked to each other via simple transfers. ([transfer example](https://etherscan.io/tx/0x31f66d1cc97ceb2d33a28d9618872ff257da8c86718864e15f746a3ce67435c1)) 

Both addresses have dispersed to the same set of addresses. Some of them provide minimal L/P but a large portion utilize the bridge. 

- Addresses have less than 50 transactions. 
- Addresses have a nearly identical pattern and execution. (suggesting one entity controls all of these addresses)
- Address 1 & 2 are active on the same chains
- Address 1 & 2 transfer to each other
- Address 1 & 2 use the same smart contracts as each other (not impossible but I'd expect different contracts)
- One address; **0x02f54d7345c3e99d58b628f3ebe99a36ee682712** is excluded
- The other address; **0x1c06efe1b692083d3d823687ffdc3b0e4332d12b** is included
- The majority of addresses interact with the same contracts 
- The majority of addresses transact with similar if not the same token amounts

 

# Methodology

I worked with a team of individuals following a prepared method; https://docs.google.com/document/d/1Zpg2QYK8fc-rVdvtB7DVP0RZ9bqhjeQFcDM5UaiAkvs/edit?usp=sharing

Four of us worked together to manually narrow down addresses by removing smart contracts, addresses displaying normal behaviour and using filters provided by blockscanners.

What we include in reports are unusual activities that are unlikely to be employed without the incentive of financial gain. 

There are a number of addresses we are actively investigating. Using a Nansen pro subscription we can take advantage of asymmetrical information like custom labels. 

**Steps;**

- Search Hop protocol addresses
- Grab suspicious address from txn list
   - Many interactions with Hop addresses
   - Frequently appears doing the same thing
1. Check Hop airdrop: https://app.hop.exchange/#/airdrop/preview 
   - Is address included? Yes → Step 2
   - Is address included? No → **STOP**
2. Check all chains
   - ETH; etherscan.io
   - BSC; bscscan.com 
   - ARBITRUM; arbiscan.io
   - OPTIMISM; optimistic.etherscan.io
   - POLYGON; polygonscan.com
3. Check transaction amounts
  - Look for similarities
  - Look for consistent transaction types
    - Transfers
    - Sends
    - Swaps
4. Check all the tabs; Txn, Internal Txns, Token Txns
5. Comments tab can add context 
   - Scammer
   - Bot 
   - Exchange
6. Identify additional wallets
  - Transfers; Easiest / Most obvious
  - Swap and Send; To different wallets
7. Use other platforms— check transactions
   - Nansen
   - Ethplorer
   - Zerion
   - Zapper
8. Use filters— search address in a blockscanner (example; etherscan.io)
   - Filter via ‘To’
   - Filter via ‘From’

Our goal is to find addresses that are _**without a doubt**_ connected to each other.

The batches of addresses were dispersed funds by single EOA's which then go on to make similar transactions— both nominal amounts, gas prices and times sent.

All of the addresses are manually verified through various platforms such as Nansen, Ethplorer and Etherscan.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/99563566/167727424-b2857062-a385-4066-8759-ea6d91cb7f54.png">

[Link to Ethtective query](https://www.ethtective.com/address/0x02F54D7345c3E99D58B628f3EBE99A36EE682712&0x1c06efe1b692083d3d823687ffdc3b0e4332d12b&0xd152f549545093347a162dce210e7293f1452150&/marked/0x02F54D7345c3E99D58B628f3EBE99A36EE682712&0x1c06efe1b692083d3d823687ffdc3b0e4332d12b&0xd152f549545093347a162dce210e7293f1452150&)

---
# Additional Report Information

Additional addresses related to; **0x02f54d7345c3e99d58b628f3ebe99a36ee682712**

These conclusions are drawn from manually inspecting addresses funded via Disperse app. 

The following addresses are related to a ‘central’ source and further investigation concludes they are controlled externally with financial motive related to transactional behaviour.

## Suspect (1 ; **0x41d3d33156ae7c62c094aae2995003ae63f587b3**

- 0x15B11dD9302f420DC1AB7120ead4616e747A7762 (14 txns)
   - [Link to ERC txns] (https://etherscan.io/address/0x15b11dd9302f420dc1ab7120ead4616e747a7762#tokentxns)
- Event: ERC20 Transfer
   - 0x41d3d33156ae7c62c094aae2995003ae63f587b3 → 0x15B11dD9302f420DC1AB7120ead4616e747A7762
   - [Link to txn](https://etherscan.io/tx/0x7302d0a2359f6aa4b562ec1baa02d08c06529a3fb6b2d11dc5329d120bfb5830)

### Conclusions;

- Address is EOA, funded via a Binance exchange wallet for 3000 USDC < 6 months ago.
- First transaction ‘out’ is for the Hop Protocol: USDC Bridge then Zksync bridge.
- Subsequent transactions indicate airdrop hunting; sending small amounts between addresses to increase transaction nonce.
> ie; Transactions that are significantly more expensive to send than they are worth [Example](https://etherscan.io/tx/0x87f91a113104fe2945f720fb8bcb678b6769eec8e81912a7fb9749c6ad0bde9d)
- Address implicated alongside other addresses involved in Sybil attacks.
- Address appears on the airdrop list.

## Suspect (2; **0xe5716d6168eF103AeF9C815135DF3e38ec488716**

- 0x41d3d33156ae7c62c094aae2995003ae63f587b3
   - Address has only five transactions on Polygon; one of which incriminates; **0xe5716d6168eF103AeF9C815135DF3e38ec488716** 
   - [Link to Polygon txns](https://polygonscan.com/address/0x41d3d33156ae7c62c094aae2995003ae63f587b3)
- Event: MATIC Transfer
   - 0xe5716d6168eF103AeF9C815135DF3e38ec488716 → 0x41d3d33156ae7c62c094aae2995003ae63f587b3
   - [Link to txn](https://polygonscan.com/tx/0xf038fa85f2cf5a15cce43bf1607061ef88babc831436aa3f4ccd83ecacea16ed)
   - There are subsequent transactions using USDC 
      - [Link to ERC 20 txns](https://polygonscan.com/address/0x41d3d33156ae7c62c094aae2995003ae63f587b3#tokentxns) 
   - 0x41d3d33156ae7c62c094aae2995003ae63f587b3 → 0xe5716d6168eF103AeF9C815135DF3e38ec488716
- Similar transactions on BSC 
  - [Link to BSC txn](https://bscscan.com/address/0x41d3d33156ae7c62c094aae2995003ae63f587b3)
  - [BEP 20 txns](https://bscscan.com/address/0x41d3d33156ae7c62c094aae2995003ae63f587b3#tokentxns)

### Conclusions;

- Both address transfer ‘to’ and ‘from’ each other
- Address implicated alongside other addresses involved in Sybil attacks.
- Address appears on the airdrop list
- The final transaction in the list for 0x41d3d33156ae7c62c094aae2995003ae63f587b3 is a [‘swapandsend’](https://polygonscan.com/tx/0x9b56aed269a7743c413fa21c6525cdb481b9a82d9782b5f708e8e42cedac8c0d)

## Suspect (3 ; **0x07E9aA40272429a4E2Ee072208FdEB76407249a2** 
> [Link to address](https://etherscan.io/address/0x07e9aa40272429a4e2ee072208fdeb76407249a2)

- It appears that this address—**0xe5716d6168ef103aef9c815135df3e38ec488716** : related to suspect 2—is a relayer. The majority of transactions are deposits and transfers. They occur in succession.

- This address—**0xc5755E2Fbf77573b6C4A154b7d8743a1a19Af45c** : most recent transfer is to the suspect. 
   - [Transfer txn](https://etherscan.io/tx/0x2642944b9b8873bbd1bf671f35a3f6627237df3a5731f23cdaedfe7aea07cdaa) 
   - [Link to other transfers txns](https://etherscan.io/address/0x07e9aa40272429a4e2ee072208fdeb76407249a2?fromaddress=0xc5755E2Fbf77573b6C4A154b7d8743a1a19Af45c) (On more than once occasion) 
   - There are no obvious reasons to transfer to this address more than once unless it was controlled in some way.

- ERC 20 transfers to the suspect from 0xc5755e2fbf77573b6c4a154b7d8743a1a19af45c; [Txn link](https://etherscan.io/address/0xc5755e2fbf77573b6c4a154b7d8743a1a19af45c#tokentxns) 

- This address—**0x41d3d33156ae7c62c094aae2995003ae63f587b3** : suspect 1— receives funds from; 0xc5755e2fbf77573b6c4a154b7d8743a1a19af45c : related to suspect 2 
- [Link to transaction](https://etherscan.io/tx/0x124362dbbcdac64012a6166f7c0987d05023f302f23b8507947bc76f6faf22d9) 

Additional evidence of collusion can be found on additional chains; 
- [Polygon](https://polygonscan.com/address/0x41d3d33156ae7c62c094aae2995003ae63f587b3#tokentxns) 
- [Arbitrum](https://arbiscan.io/address/0xe5716d6168ef103aef9c815135df3e38ec488716#tokentxns) 

### Conclusions;
 
- This address is tightly involved with the suspects above
- Many transactions for suspect 3 are related to suspect 1 + 2
- The number of transactions are similar

## Visuals

<img width="839" alt="Screen Shot 2022-05-10 at 9 04 37 PM" src="https://user-images.githubusercontent.com/99563566/167773736-ee650b21-436e-46b0-ab56-2463a357fa83.png">

<img width="865" alt="Screen Shot 2022-05-10 at 9 05 00 PM" src="https://user-images.githubusercontent.com/99563566/167773751-4d133664-b32f-42c7-865e-88f5bbba490b.png">

<img width="868" alt="Screen Shot 2022-05-10 at 9 05 43 PM" src="https://user-images.githubusercontent.com/99563566/167773797-eb2a0d7d-ddbb-4a45-94d2-212120ebf300.png">

# Rewards Address

0xa1b04C41B2b360b92a07926d3032d20A0A142F3e

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 5 of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
