### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by codyborn** [hop-protocol/hop-airdrop#268]
# Related Addresses

Group 1
```
0x64595e305f3671030af14d7fd6b0b2195671b4de
0xc3c4ff037904895d2c154bafec4f63feeb9958a9
0xf08961d8863c0535253061bcb7ec10034adacd60
0x394284739cc4e16a5d2faa971947fc06c951276d
0x81b8a61f1b345d9fb6963bcdea74d72cb5760600
0xed99808f05ba011cf391c3959149a4b1b4324088
0x122bd0cdb8feb80591b70c76bddebe7241a05685
0x48d800fb00f7e01bc14b7d3c2dfaade8a1ca6974
0x09f258f399c421afff697ff75caca4ba3c73f02b
0xed99808f05ba011cf391c3959149a4b1b4324088
```

Group 2
```
0x83195709c4dda9dac7d343b378c9cc17bb6344f9
0xfa93c414267f0bb41242ff82fd9a832891f41f1d
0x654b26c30b1b9294e6d670cb94ac2a960aec0ecf
0xc42b8048764ca138ac55d04a1e1791e937589194
0x5f370d192c2b86924faee4acfe817c0aef2ca59e
0x91639f372205661c81d0aa17f6793d81f57d59bf
0x1caaded48bc6a8bc81a3668cd6c1796b80bc0bdc
0x1b6b6bedbc40a236a54ae47032bee739e22a1f9e
0x87ee84f05c84cb5be15332189772498f2e59e477
0xbe7e2d7a479bcb9c82450e2450bae515f64141f2
```

Group 3
```
0xee44e08c44796af94b390722c4817f75f8092832
0xcf85546603343f28f9bcb38ce44ffb5ce77fecd9
0x18ed89e6d2f7f1bd1b65062b01633acb806a1dac
0x978e6cb75aad5c2857b054b00abb334219699ba4
0x1e7af8dea3168a3dd2deb678c2fdca39ea4a326f
0xd399a409a130da36818bb68d5f3d547ba995d040
0x32aac5709e9b69a324750fb9aed3e5a0623ab32b
0x3644101381ea2023883a486100700ed7d280c7cc
0x19e68b0bc7770e5a65a293a29b4b5172e7beb875
```

# Reasoning
Users were first aggregated by their `value` sent and `gas price` when interacting with HOP. I manually looked for abnormal patterns that were very unlikely to co-occur. For example, 8 addresses had the sent .35 ETH across the HOP bridge with a gas price of 52899273829 wei. I further found that each of these account groups were funded by the same transaction (using Disperse) or had interacted with each other heavily at various times (see below).

## Group 1
`gas_price: 52899273829`
`value: 350000000000000000`
Common patterns: 
 - All used Disperse.app (a way to fund many accounts at once) and were funded in the same transaction: https://etherscan.io/tx/0x96e6d8a73d608dabc3205bd0180326624f3fa04670feedb7bde981400af5c55c
 - Many used Nomad bridge, sending the same amount (1.6999 WETH)
 - Most of the addresses used Barnbridge
 - Most of the addresses farmed other airdrops (London, Botto, Salty)

## Group 2
`value: 1232500000`
Common patterns:
These set of addresses all have interacted with each other which is easy to see based on the ENS names.
- `0x1caaded48bc6a8bc81a3668cd6c1796b80bc0bdc` = `jaers.eth`
- `0x654b26c30b1b9294e6d670cb94ac2a960aec0ecf` = `bearcase.eth`
- Interacted with `bearcase.eth` - `0x83195709C4DDA9DaC7d343B378c9CC17Bb6344f9`, `0xBe7e2D7a479bCB9c82450e2450BaE515F64141F2`, `0x87ee84f05c84cb5be15332189772498f2e59e477`, `0x5f370d192c2b86924faee4acfe817c0aef2ca59e`, `0xfa93c414267f0bb41242ff82fd9a832891f41f1d`, `0x83195709C4DDA9DaC7d343B378c9CC17Bb6344f9`
- Interacted with `nft4real.eth` - `0x1b6b6bedbc40a236a54ae47032bee739e22a1f9e`, `0x91639f372205661c81d0aa17f6793d81f57d59bf`
- Interacted with `jaers.eth` - `0x91639f372205661c81d0aa17f6793d81f57d59bf`, `0x83195709C4DDA9DaC7d343B378c9CC17Bb6344f9`, `0x5f370d192c2b86924faee4acfe817c0aef2ca59e`
- Interacted with `0xfa93c414267f0bb41242ff82fd9a832891f41f1d` - `0xc42b8048764ca138ac55d04a1e1791e937589194`

## Group 3
5/9 have the same gas value and gas price:
`value: 500000000`
`gas_price: 50672805689`
```
0xee44e08c44796af94b390722c4817f75f8092832
0xcf85546603343f28f9bcb38ce44ffb5ce77fecd9
0x18ed89e6d2f7f1bd1b65062b01633acb806a1dac
0x978e6cb75aad5c2857b054b00abb334219699ba4
0x1e7af8dea3168a3dd2deb678c2fdca39ea4a326f
```

The other 4/9 all sent 502 USDT on the same day (Sep-22-2021):
```
0xd399a409a130da36818bb68d5f3d547ba995d040
0x32aac5709e9b69a324750fb9aed3e5a0623ab32b
0x3644101381ea2023883a486100700ed7d280c7cc
0x19e68b0bc7770e5a65a293a29b4b5172e7beb875
```

Common patterns:
- All of these addresses were funded in the same transaction using Disperse.app
https://etherscan.io/tx/0xf63a5e1fdaaa1a7fa72b371bc64c51a7affe6f3a8c900c2bf5b78877aa30f827

-->

# Methodology

1. Collected all interactions with HOP protocol from Airdrop address list ([BigQuery](https://console.cloud.google.com/bigquery?sq=750504289740:75c21f87ee61420a98dc1f9095be4eaa))
2. Grouped on `value` and `gas_price`
3. Looked for unlikely clusters and manually analyzed address behavior on Etherscan to verify all addresses had similar behavior.

# Rewards Address

`0xEeA95EdFC25F15C0c44d4081BBd85026ba298Dc6`

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
