### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by eser11** [hop-protocol/hop-airdrop#27]
# Related Addresses

# Reasoning

All addresses called `swapAndSend` on Polygon between May-03-2022 07:27:07 AM +UTC  in the exact same sequence. All addresses 
-->

# Methodology

**Comment by Markfxx** [comment]
Where is the address? Can you put in on the thread pls

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
