### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by antisaa** [hop-protocol/hop-airdrop#31]
# Related Addresses
```
0x4ffc3884669e442e5d2f687b2c70504d942ba129
0xeaea403f57cf1d143258aa5f30c53c313db0bb14
0x6c1bb12d45851e34e63d3aec1367702a2a01ef9e
0xa3fa994c98c37e97a71a440a1725b1571b1bfb02
0x5765d2e0f02d3479cbb0900fc4e242e46fff0333
0x8ce2410e46b27ceba76d7e8837b0d00b650fdd42
0xd1d399a5ab77ce9f481c7f6cd5af8b96d0341dbe
0x150453b44018797cec161ce9770aca07652953a3
0x1a447a505919a0be39291224d4a4b096248a4a8c
0x24a85f7af097f169cfa8cb101d6dd6dfca96cab5
0x9290a2170e18604aada853e5cea4f34aad6d3efb
0x7b731d3e1b4c6d71925833876af25fdd5c618191
0x6b58bc920199eefc3048a02d113627e6e0226f50
0xa1c4a0a3167ac52a6853477af1db4d882ef5f72c
0x64b998a7078c86e444facbf26ea220829b636103
0xdc6b8d16a7bc3b95294d71b42f288b4fe14181da
0x620087aa7d016da502bed5841b71aee3c4887ac6
0x6a4f118afe5eefbeeb1591e516b3c9a8fabe6026
0x5a09496e9cca89ba9289125817a5863ca6808b4f
0xfaa5ee4dce2a4e0479f651856d17e9cd93a15c55
```

# Reasoning
I was clustering all addresses that received airdrop by transfered eth between each other. These 20 addresses were transferring eth and other erc20 between each other multiple times on Ethereum, Polygon and Optimistic, so I assume they belong to the same person. They all interacted with hop protocol at the similar times and their airdrop amounts are very close ~ 1330 HOP, which rise my suspicion.

# Methodology
Here is the proof that all addresses used for the first time hop bridge to optimism in the similar times. Additionally, they used similar coins sETH, sBTC, sLINK, sUSD with similar amounts when bridging.

0x4ffc3884669e442e5d2f687b2c70504d942ba129 on Nov-21-2021 08:32:53 AM +UTC [link](https://optimistic.etherscan.io/tx/0x7249dde8d8a0f20c9a0f2acf01deea0322c5a315f7db877ac87f1359e9240699) bridged 0.43 hETH 
0xeaea403f57cf1d143258aa5f30c53c313db0bb14 on  Nov-21-2021 02:52:11 PM +UTC [link](https://optimistic.etherscan.io/tx/0x3576158f2f0cfe80bc131d72c27fe335b3594f7a7a959fa1d0edd6b3d4b9dd8b) bridged 0.1919 hETH
0x6c1bb12d45851e34e63d3aec1367702a2a01ef9e on Nov-21-2021 04:15:52 PM +UTC [link](https://optimistic.etherscan.io/tx/0xc2f02d82f591492440aa2ec96d4e210a89ce10e394d04531366e96a7d56c9f5a) bridged 0,2793 hETH
0xa3fa994c98c37e97a71a440a1725b1571b1bfb02 on Nov-22-2021 09:37:55 AM +UTC) [link](https://optimistic.etherscan.io/tx/0x626318c6faf540a1b3b734e03c47600717d660f44b0f7c86c5d1c85cb90e39c8) bridged 979,41 hUSDT
0x5765d2e0f02d3479cbb0900fc4e242e46fff0333 on Nov-22-2021 06:39:13 PM +UTC [link](https://optimistic.etherscan.io/tx/0x718ad9cbd14175bdbad3cac9b3a567c532fb359ae1ddd922838b052e7243fd81) bridged 0,011 hETH
0x8ce2410e46b27ceba76d7e8837b0d00b650fdd42 on Nov-22-2021 11:36:15 AM +UTC [link](https://optimistic.etherscan.io/tx/0x6ea8b553a98c2c6b6036dd681034dfc6ab78916eac6e98b70be1f778e62895ab)  bridged 0,0990712 hETH
0xd1d399a5ab77ce9f481c7f6cd5af8b96d0341dbe on Nov-22-2021 04:26:00 PM +UTC [link](https://optimistic.etherscan.io/tx/0xa0d385d085496d0bf4369f7ab874ca065f42a90519af0807554cd20a791a814f) bridged 0,0989799 hETH
0x150453b44018797cec161ce9770aca07652953a3 on Nov-22-2021 05:00:43 PM +UTC) [link](https://optimistic.etherscan.io/tx/0x1d4bfa42d6783d857859342dfa74d56f90a6183dd0530cc7bfb1385f7bbd36cf) bridged 624,25 sUSD
0x1a447a505919a0BE39291224D4A4b096248A4A8c on Nov-22-2021 02:11:42 PM +UTC [link](https://optimistic.etherscan.io/tx/0x6bc5ea21541016bc7bceb1bc7972db88146993125cc0688b2fec897e68aa5b59) bridged 0,1284 sETH
0x24a85f7af097f169cfa8cb101d6dd6dfca96cab5 on Nov-22-2021 07:22:57 AM +UTC [link](https://optimistic.etherscan.io/tx/0xfe9054ca71382044612706ec0bfffca46754cbd071ca05dcad0303db2ad3ce99) bridged 0,0689 hETH
0x9290a2170e18604aada853e5cea4f34aad6d3efb on Nov-22-2021 01:02:25 PM +UTC [link](https://optimistic.etherscan.io/tx/0xf465c714bfdac7763adf39b9d17244f7ad3544f6d982f03076cd3eecc945dd0b) bridged 635,7 sUSD
0x7b731d3e1b4c6d71925833876af25fdd5c618191 on Nov-22-2021 04:58:30 AM +UTC [link](https://optimistic.etherscan.io/tx/0xf63f6cd8addd2758e2df7ae5844bdb98bc046299c948f468cf9302f62e16a58c) bridged 0,2749 sETH
0x6b58bc920199eefc3048a02d113627e6e0226f50 on Nov-22-2021 05:35:07 AM +UTC [link](https://optimistic.etherscan.io/tx/0x5fdd5c89bbe27dfe1f53ecc0f414965aaee826f1661004e38bd27665007e5de2) bridged 0,07845 sETH
0xa1c4a0a3167ac52a6853477af1db4d882ef5f72c on Nov-22-2021 01:45:57 PM +UTC) [link](https://optimistic.etherscan.io/tx/0xbc37629dffc38d74813806c233f843e51b817ff3cf915d5a8518d2190d4cf937) bridged 0,162 sETH
0x64b998a7078c86e444facbf26ea220829b636103 on Nov-22-2021 05:59:24 PM +UTC [link](https://optimistic.etherscan.io/tx/0x92480090e98e21dcce444e73dac0257482e91512787346283222e9715b3f049c) bridged 570,96 sUSD
0xdc6b8d16a7bc3b95294d71b42f288b4fe14181da on Nov-22-2021 06:28:43 AM +UTC [link](https://optimistic.etherscan.io/tx/0xfeb0cfd49cac3f584030b1c4eefb9cefa555dcc00589bf8aeb993305abfcecaa) bridged 0,1915 sETH
0x620087aa7d016da502bed5841b71aee3c4887ac6 on Nov-21-2021 05:39:25 PM +UTC [link](https://optimistic.etherscan.io/tx/0xc10993157a9008c897c577f5c6f97f218e282689202ae8ae4daf44228ebb237e) bridged 0,265 sETH
0x6a4f118afe5eefbeeb1591e516b3c9a8fabe6026 on Nov-22-2021 09:34:14 AM +UTC[link](https://optimistic.etherscan.io/tx/0x2e159cef7b1a6b8085d3102ce8793b34375d60bec7dde960abccd47a73203a55) bridged 0,2132 sETH
0x5a09496e9cca89ba9289125817a5863ca6808b4f on Nov-22-2021 02:56:11 PM +UTC [link](https://optimistic.etherscan.io/tx/0x738d004bedd80a3deee7b889f279c64e42a7697e5e095223939df148823e52a0) bridged 0,118 sETH
0xfaa5ee4dce2a4e0479f651856d17e9cd93a15c55 on Nov-22-2021 05:48:03 PM +UTC[link](https://optimistic.etherscan.io/tx/0x6d364a19ea7eacacfe242923b666a269132569f670c33f4fe124150cab548b53) bridged 478,55 sUSD

Just look at the times of their first transactions bridging to optimism using Hop protocol and tell me could this be coincidence?
If you would need a proof of transaction between those addresses I can easily provide it.

They have registered ENS on similar times:
0x4FFC3884669E442e5d2F687B2C70504D942ba129 - 2021-09-19 9:49:19
0xeaea403f57cf1d143258aa5f30c53c313db0bb14 - 2021-09-19 10:16:01
0x6c1bb12d45851e34e63d3aec1367702a2a01ef9e - 2021-09-21 4:17:30
0xa3fa994c98c37e97a71a440a1725b1571b1bfb02 -2021-09-21 10:50:10
0x24a85f7af097f169cfa8cb101d6dd6dfca96cab5 - 2021-09-21 10:33:00
0x7b731d3e1b4c6d71925833876af25fdd5c618191 -2021-09-21 9:53:54
0x6b58bc920199eefc3048a02d113627e6e0226f50 - 2021-09-21 10:00:50
0xdc6b8d16a7bc3b95294d71b42f288b4fe14181da - 2021-09-21 10:23:44
0x620087aa7d016da502bed5841b71aee3c4887ac6 - 2021-09-21 9:46:43
0x6a4f118afe5eefbeeb1591e516b3c9a8fabe6026 - 2021-09-21 10:41:59

0x5765d2e0f02d3479cbb0900fc4e242e46fff0333 - 2022-04-24 13:06:33 
0x8ce2410e46b27ceba76d7e8837b0d00b650fdd42 - 2022-04-24 12:51:43
0xd1d399a5ab77ce9f481c7f6cd5af8b96d0341dbe - 2022-04-24 13:03:09
0x150453b44018797cec161ce9770aca07652953a3 - 2022-04-24 13:05:21
0x1a447a505919a0be39291224d4a4b096248a4a8c - 2022-04-24 12:59:38
0x9290a2170e18604aada853e5cea4f34aad6d3efb - 2022-04-24 12:57:02
0xa1c4a0a3167ac52a6853477af1db4d882ef5f72c - 2022-04-24 12:57:02
0x64b998a7078c86e444facbf26ea220829b636103 - 2022-04-24 13:06:33
0x5a09496e9cca89ba9289125817a5863ca6808b4f - 2022-04-24 13:01:33
0xfaa5ee4dce2a4e0479f651856d17e9cd93a15c55 - 2022-04-24 13:05:54

========

# Rewards Address
0xa52AaF7da0156d2D30a310aFe6f084a0DA9cEE54

**Comment by antisaa** [comment]
There are also 19 trasactions from [pengkui.eth](https://etherscan.io/address/0x4ffc3884669e442e5d2f687b2c70504d942ba129) (`0x4ffc3884669e442e5d2f687b2c70504d942ba129`) to others from `Aug-22-2021 03:12:17 PM +UTC` until `Aug-22-2021 04:35:05 PM +UTC` each transacting 0.021 Ether on Ethereum network.
First tx hash: https://etherscan.io/tx/0xf8cd639ca215e271d0178ff99abe9b643f385bfca4b2b124cba21aa054aaea5a
Last tx hash: https://etherscan.io/tx/0x738c306fb034fea7e41d390fd1edea8e1c4929558fbf6e651ad543b731b60cf4

**Comment by shanefontaine** [comment]
Thank you for your report @antisaa. We have verified that the addresses in this report are Sybil attackers.

The report included 20 eligible addresses as Sybil attackers which means you are eligible for 6724.628520358758242395 HOP!

The qualified addresses are as follows:

```
0x4ffc3884669e442e5d2f687b2c70504d942ba129
0xeaea403f57cf1d143258aa5f30c53c313db0bb14
0x6c1bb12d45851e34e63d3aec1367702a2a01ef9e
0xa3fa994c98c37e97a71a440a1725b1571b1bfb02
0x5765d2e0f02d3479cbb0900fc4e242e46fff0333
0x8ce2410e46b27ceba76d7e8837b0d00b650fdd42
0xd1d399a5ab77ce9f481c7f6cd5af8b96d0341dbe
0x150453b44018797cec161ce9770aca07652953a3
0x1a447a505919a0be39291224d4a4b096248a4a8c
0x24a85f7af097f169cfa8cb101d6dd6dfca96cab5
0x9290a2170e18604aada853e5cea4f34aad6d3efb
0x7b731d3e1b4c6d71925833876af25fdd5c618191
0x6b58bc920199eefc3048a02d113627e6e0226f50
0xa1c4a0a3167ac52a6853477af1db4d882ef5f72c
0x64b998a7078c86e444facbf26ea220829b636103
0xdc6b8d16a7bc3b95294d71b42f288b4fe14181da
0x620087aa7d016da502bed5841b71aee3c4887ac6
0x6a4f118afe5eefbeeb1591e516b3c9a8fabe6026
0x5a09496e9cca89ba9289125817a5863ca6808b4f
0xfaa5ee4dce2a4e0479f651856d17e9cd93a15c55
```

**Comment by shanefontaine** [comment]
It looks like all addresses had similar behaviors on the Hop protocol as well:


address | ensName | total | mainnet | arbitrum | optimism | polygon | xdai | totalVolume
-- | -- | -- | -- | -- | -- | -- | -- | --
0x4ffc3884669e442e5d2f687b2c70504d942ba129 | pengkui.eth | 19 | 3 | 0 | 1 | 9 | 6 | $18,333.49
0x6c1bb12d45851e34e63d3aec1367702a2a01ef9e | btczz.eth | 13 | 1 | 0 | 1 | 7 | 4 | $12,700.85
0xeaea403f57cf1d143258aa5f30c53c313db0bb14 | zhena.eth | 14 | 0 | 0 | 1 | 9 | 4 | $9,032.28
0xdc6b8d16a7bc3b95294d71b42f288b4fe14181da | ens68.eth | 12 | 0 | 0 | 2 | 6 | 4 | $8,810.96
0x620087aa7d016da502bed5841b71aee3c4887ac6 | bnb88.eth | 13 | 0 | 0 | 1 | 7 | 5 | $8,164.96
0x7b731d3e1b4c6d71925833876af25fdd5c618191 | ltc88.eth | 11 | 0 | 0 | 1 | 6 | 4 | $7,733.20
0x6a4f118afe5eefbeeb1591e516b3c9a8fabe6026 | veths.eth | 12 | 0 | 0 | 1 | 7 | 4 | $7,611.98
0x24a85f7af097f169cfa8cb101d6dd6dfca96cab5 | neonb.eth | 12 | 0 | 0 | 1 | 7 | 4 | $6,882.93
0xa3fa994c98c37e97a71a440a1725b1571b1bfb02 | bchzf.eth | 11 | 0 | 0 | 1 | 6 | 4 | $6,830.70
0x6b58bc920199eefc3048a02d113627e6e0226f50 | ethys.eth | 12 | 0 | 0 | 1 | 7 | 4 | $6,415.45
0x5a09496e9cca89ba9289125817a5863ca6808b4f |   | 12 | 0 | 0 | 1 | 6 | 5 | $6,279.56
0x5765d2e0f02d3479cbb0900fc4e242e46fff0333 |   | 13 | 0 | 0 | 1 | 7 | 5 | $5,409.48
0x8ce2410e46b27ceba76d7e8837b0d00b650fdd42 |   | 12 | 0 | 0 | 1 | 6 | 5 | $4,149.55
0x150453b44018797cec161ce9770aca07652953a3 |   | 11 | 0 | 0 | 1 | 5 | 5 | $3,919.15
0x9290a2170e18604aada853e5cea4f34aad6d3efb |   | 11 | 0 | 0 | 1 | 5 | 5 | $3,862.03
0xd1d399a5ab77ce9f481c7f6cd5af8b96d0341dbe |   | 12 | 0 | 0 | 1 | 6 | 5 | $3,829.79
0xa1c4a0a3167ac52a6853477af1db4d882ef5f72c |   | 10 | 0 | 0 | 1 | 5 | 4 | $3,757.98
0x64b998a7078c86e444facbf26ea220829b636103 |   | 11 | 0 | 0 | 1 | 5 | 5 | $3,690.93
0x1a447a505919a0be39291224d4a4b096248a4a8c |   | 11 | 0 | 0 | 1 | 5 | 5 | $3,481.14
0xfaa5ee4dce2a4e0479f651856d17e9cd93a15c55 |   | 11 | 0 | 0 | 1 | 5 | 5 | $3,315.19
