### ISSUE TITLE
Sybil Attacker Report [50+]

### ISSUE THREAD

**Issue by Bal7hazar** [hop-protocol/hop-airdrop#329]
# Related Addresses

```
0xf4700630f9d6d51d31abf82aaa88bda223240468
0x43574a11f5a783db442b74b902c7567326fdd293
0x72f60aa98c4a1d4c75e5e436fb3f98ea85cc1a3d
0xedfe14fceb460cdb4b3b0128e073631165dbfea8
0x89cbada8c98919e8c44d744a4234c2a8e22dc4d9
0x695f8458f3cbd90809fda109661467c82d69600d
0x92ad53dc1e598f2e491f945a80a28eab82917ba4
0x5a9381ff0b2bf6beee09e80cc2a7beeb1a526b75
0x61144f133cee6eb6a3cb1e7a22dacfe57fd625e4
0x77e97af53e7e680fbc52dfa0e8891f504c9e7ad2
0xf01b0ddebd3c22125ac691489a856d7e562ba534
0x71a1deb9560f805f098c72f50ba4c4dea1dcd480
0xef3d64395988443e6cbafbe37d1433cddc7ef047
0xf97f7ab7ad98590ecbf9d1870d976bb1acecb696
0x27eb7ea0611347d72506c7fd3210afe2a8b213e9
0x5e764d0874c5773194542a7572ac2d640af41eb5
0x633ccab60e6f010c5f9ca86be620cea252e00960
0x7e0a6f814a57e1919f60525294d834b7532476a4
0x089b89993e4ec80ac8ded4dad44ae65a1b04e55b
0x859743c36575b443dca62cdef10ee3cdd86c2667
0x19bbaf8f9ad9906873323a221b3a701606bcd6d9
0x4d40f99215bd41c9cdb5149cd7e50ecb67d22916
0x7d1584e65ce1cc5451a48d1025ae86b836d3a365
0xea959ab6b12e9d5875fb73cb7286716917d4653a
0xb5a9ddf4a2361a196c9ccf4014af1ebb83850a3e
0x91654cd36ae510c330624686a99f8d35d3a4acb7
0x572e16cf444ebcff1fb38b2b1842d96fecc8f019
0x1857edfb56cf8828ac7ee77edc065ab885a0b3dc
0xd524dafabefeff3adc021d23783a7fee771833fd
0xad578e7fa7b78feef3786d60614a740a9af88c04
0xc2ff8b2fb8082c811b310ca1c2d5cb235f3059bb
0xc4f88c35bd1485c846847c093b5a77a126cf1b05
0x6ca836d937a9154f5fe8f0ac224460628010646f
0xa43993d4fdb76ad4ff4d6684e17a7c5de7368617
0x264571c538137922c6e8af4927c3d3f681399e50
0xba503966e3430b7ac6885350d025677a2b873eeb
0x88410277b308bb03d6a4909acff2f426f6875488
0x2bbab61449b5c292c38323508b0ce378e884d3fc
0xc6c9c1660c83403e883c8a25fa4df92097fba131
0xaa8660430bb627d9a490099e77c357b48e545a17
0xcdd27fdf1b991e9deb8647ee3d8ac1bdb7d6b675
0xbac2fcee7a46e91cf4cd26de00a5536c889c3e9e
0x4eef4eebecfc07debcc06f707db144b2d6996d3e
0x12c34540d90f832c78bf3f1355b61dad5a087ec2
0xa5edd760b959c1fae53ae50b92a278b5eee47c55
0xe9f157f18848fa600bd003e4a81ff98349c9c55c
0xa0e1eee5ce9881c716ed5d09377f693dfbb65a9a
0xf7c83f8bda18d8a9dfa77cdee42defaab4c74f36
0x8c80c1fe10912398bf0fe68a25839defcaef588e
0x218b7f2ad75ec6b5f25b744c6f7bccc26e623e35
```

# Reasoning

Same reasoning as #192.

# Methodology

Same methodology as #192 with same filters but for networks **from 10 to 20 size**:

- Network with a average score of 90+ with a size of 10 to 20
- Only addresses with a score of 100% (txs exclusively with their belonging network) are reported

Note: I guess this issue must have the label `10 to 20 addresses`

# Evidences

Here is the picture of the considered networks:
- Red wallets (100% score) are the only ones reported.
- Grey wallets are those already removed from the `finalDistribution.json` but belonging to the network
- Other color wallets are those belonging to the network but with a lower than 100% score (so not reported)

![image](https://user-images.githubusercontent.com/97087040/168423419-21eff757-eb3d-470a-a19d-6de7be58c75c.png)

Here the [sheet](https://docs.google.com/spreadsheets/d/1lJ_U_aPxDGjIbGWiSRclkQu9st-fwXgc6rp-vYDXuqs/edit?usp=sharing) with the evidences.

The html to interact with the networks: [network.zip](https://github.com/hop-protocol/hop-airdrop/files/8692840/network.zip)

# Rewards Address

`0x987ffC303bEa07c4aD724f2BA9800b1FDC6a7dB0`

For any question, you can contact me on:

Twitter `@Blthazar2`
Discord `Balthazar#6199`

**Comment by zlgitol** [comment]
You can report 10-20 addresses and combine multiple groups together to report. 
This is not a fair-play.
And historic transactions can prove nothing, except they show similar behaviors in token transfers.

**Comment by Bal7hazar** [comment]
@zlgitol, I assume Team is aware of their rules, I did a proposition and I'll be compliant with the final decision.

Moreover, I didn't try to hide that it is a combination of multiple groups.

My position is to say that some remaining addresses have been missed from previous reports leaving them alone among eligible addresses. Here is what is really unfair to the community.

**Comment by peter9998** [comment]
return my hops 0xc75839b60f61be10ebeeb8c5a9c0008d30862905

**Comment by Bal7hazar** [comment]
@shanefontaine , sorry I'll be unable to add information for the next 2 weeks (until Tuesday 31st) since I will be away from my computer.

**Comment by peter9998** [comment]
I don't know what the logic is, but you have found out what I have to do
with these addresses. You sent so many related content, I don't know the
above address. I am worried about your IQ. Therefore, the computer software
also has errors, and the transfer between friends is very normal. Even the
pig knows the truth. If you define it as a witch, you are not even as good
as the pig.

Bal7hazar ***@***.***> 于2022年6月2日周四 03:56写道：
