### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Ukraine0224** [hop-protocol/hop-airdrop#335]
# Related Addresses

0xe8b29ffbbdfd6383a152a0af78153419659e385f
0x6072e28d5412208dbee7a1e41764b6c9a45d6067
0xc465316264b9fc846a346d38819ca21f0fac871f
0xB80BD6E1abCA379e650926BdCaA0131a02D565aA
0x78cC1b466D32d17fA79af3dBD1cB7fbE980ff6C9
0x2bF125679008fB09CB284338848f65fD578943bB
0x7C655ab077c09fdd357230e0C73D044A4dCe87f7
0x96e51CE5A04bAd5918982f37Fa21be96976D9a3b
0x587b7ec41dB6666bf304c468b10Bf2342545C3CF
0x0179b62C44958Ea18Aca99d8371DAF72bC51489e
0x3861eD6706559E98b6e6682198990bF235a57B7d
0xf80bF90f6C0bce6798C0E18Cb4df7f4476F5b897
0x77deFc6af00bec863b06Dbf8b30a30EAC34DdF2B
0x160db942B7fcC54c7a16531E22F1D7C0E14947AE
0x26c2DB15d47f4036Ac5C07043B34527655349567
0x944dE56706116e1f1Ed2F37d6Fa6D6EBAf5351cD
0xce76e52541dB665E9BA2770E8CaF947a171aeb34
0x20654d70b1855174d059F1cBEA53B3a1FD904c63
0xe422538C0a39ae889E4E7C41360CF77800a261A0
0xef22788323FbAf28a2002e2F520703707A26d4B4
0x9F22f644Ce847DEFC6675d0E0AF2490B73C10766
0xE1c15D4e966160e29C3e45e47772571A923b372b

# Reasoning

The following addresses made very obvious transactions on the ETH network and sequentially transferred ETH from one wallet to
the next wallet makes them the sybill attckers wallet. I've listed the exact details of their deal below.

# Methodology

0xe8b29ffbbdfd6383a152a0af78153419659e385f(linchuan.eth) transfer 0.04eth to 0x6072e28d5412208dbee7a1e41764b6c9a45d6067
time:5-02-2022 06:31
TX Hash:0x02b261d880873a6ebf68406f57b90011722d70def5a33f9066959005c867dd2e

0xc465316264b9fc846a346d38819ca21f0fac871f(szfreeman.eth) transfer 0.05eth to  0xe8b29ffbbdfd6383a152a0af78153419659e385f
time:05-14-2022 06:45:10
TX Hash:0x38254a342ecf8b53b59db454f4cc71efcde36e5d7b1bbde60e7dbb943529b19d

# Rewards Address

0xb1DFA2e690F24e916DC9e0bD7b2b0003Aa75cd4F

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 4 of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

It looks like most of these were reported in #276.

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
