### ISSUE TITLE
Sybil Attacker Complaint

### ISSUE THREAD

**Issue by mdizs** [hop-protocol/hop-airdrop#337]
# Related Addresses
0x9ae3762456f72d1F914A2a80ce7CCfD7CE91f99A

I have been using hop transactions at my address for over 6 months, with 4-5 cross-chain transactions per month.
The total transaction amount is over $30,000. I would like to request help to re-examine my address.

**Comment by tryhard3eth** [comment]
this you?


"groupName": "0x9ae3762456f72d1f914a2a80ce7ccfd7ce91f99a",
    "notes": "",
    "totalConnectedAddresses": 402,
    "totalEliminatedAddresses": 257,

**Comment by mdizs** [comment]
> this you?
> 
> "groupName": "0x9ae3762456f72d1f914a2a80ce7ccfd7ce91f99a", "notes": "", "totalConnectedAddresses": 402, "totalEliminatedAddresses": 257,

Yes, this is my address
I have a community of over 500 people myself and having that many associated addresses means that my web 3.0 activity is high, my hop interaction is happening normally, you should be looking up each of my interactions and not looking at my address associations, I am a consistent user for 6 months and my web 3.0 activity does not negate my interaction.

**Comment by tryhard3eth** [comment]
randomly checked some of the associated addresses, and there is always the same pattern (receive USDT from associated address, deposit 10 USDT LP -> send remaining USDT to next associated address -> repeat). Not looking good tbh.

**Comment by shanefontaine** [comment]
Thank you for the details. Unfortunately, these issues are only meant for Sybil attacker reports. I am going to now close this issue.
