### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by johnsgeorgecet** [hop-protocol/hop-airdrop#344]
# Related Addresses

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xffC2cE9c18A1fEf310BF0C99D902aED6f38361d2 > 0x3eCD8e3360bbeC4108A2E762bF5e26be3f0379db 

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0x6a4EB17072301631C825023E473A21DcbE2a91a8 > 0xffC2cE9c18A1fEf310BF0C99D902aED6f38361d2 

0xC78cD3354323Fb43b5540832234032B0DAc15d9F > 0x6a4EB17072301631C825023E473A21DcbE2a91a8

0x6dF8010ff3f6592b9Fb709AB59b767A7f4755928 > 0x14e4C0E5a9D72c657c8C4a5979989Cd2CBB9d443
0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0x6dF8010ff3f6592b9Fb709AB59b767A7f4755928

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xfA35A99C75113E94dc597C8dB0C9f708ced57c18 > 0x6dF8010ff3f6592b9Fb709AB59b767A7f4755928

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0x408A17963ea5f000811fc5FD1a069d6aCEe7fe54 > 0xfA35A99C75113E94dc597C8dB0C9f708ced57c18

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xACf745ef17a58C3DB56a3A601a48d1883aC71186 > 0x408A17963ea5f000811fc5FD1a069d6aCEe7fe54

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0x3eCD8e3360bbeC4108A2E762bF5e26be3f0379db > 0xACf745ef17a58C3DB56a3A601a48d1883aC71186

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xffC2cE9c18A1fEf310BF0C99D902aED6f38361d2

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0x6a4EB17072301631C825023E473A21DcbE2a91a8

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xC78cD3354323Fb43b5540832234032B0DAc15d9F > 0x6a4EB17072301631C825023E473A21DcbE2a91a8

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xE38177dAeDfB70DCa023FBAeB799E248d9369cdD > 0xC78cD3354323Fb43b5540832234032B0DAc15d9F

0x86e6034C0EB6eC8D323C709C345b36219F3d3261 > 0xea7Ed1807c1a18bcbef9c20624a3aa05A9f0B50c > 0x841bf5eA78df372a23fdE1d6A5730d713a8C68d8

0x7c16B38790C9c55d4128A84bD1302Ec63812b76E > 0x6524A47C6C6085150bf16A84b0c18F716CCe1D26 > 0x86e6034C0EB6eC8D323C709C345b36219F3d3261 

0xea7Ed1807c1a18bcbef9c20624a3aa05A9f0B50c > 0x7c16B38790C9c55d4128A84bD1302Ec63812b76E > 0x6772e63e690F4f5e8e8448a1543f60B8bE31ff1d > 0x6524A47C6C6085150bf16A84b0c18F716CCe1D26

0x6524A47C6C6085150bf16A84b0c18F716CCe1D26 > 0x8B02faaa4DBf774b4C43F35C22772160580CCAb8 > 0x841bf5eA78df372a23fdE1d6A5730d713a8C68d8 > 0xE38177dAeDfB70DCa023FBAeB799E248d9369cdD

0x6524A47C6C6085150bf16A84b0c18F716CCe1D26 → 0xc6deC38E7d170857C4111A620d2c9175374F16B7

0x6524A47C6C6085150bf16A84b0c18F716CCe1D26 → 0x4045D724656f586ae4A470d1CF7e10fecAde856F

0x6524A47C6C6085150bf16A84b0c18F716CCe1D26 → 0x970b1feC73b2c5ed9859384A60A70a5214447dC8

cleaned up list:
-------------------
0x86e6034C0EB6eC8D323C709C345b36219F3d3261 
0x6a4EB17072301631C825023E473A21DcbE2a91a8 
0xC78cD3354323Fb43b5540832234032B0DAc15d9F
0x6dF8010ff3f6592b9Fb709AB59b767A7f4755928 
0x14e4C0E5a9D72c657c8C4a5979989Cd2CBB9d443
0xfA35A99C75113E94dc597C8dB0C9f708ced57c18
0x408A17963ea5f000811fc5FD1a069d6aCEe7fe54
0xACf745ef17a58C3DB56a3A601a48d1883aC71186
0x3eCD8e3360bbeC4108A2E762bF5e26be3f0379db
0xffC2cE9c18A1fEf310BF0C99D902aED6f38361d2
0xE38177dAeDfB70DCa023FBAeB799E248d9369cdD
0x841bf5eA78df372a23fdE1d6A5730d713a8C68d8
0x7c16B38790C9c55d4128A84bD1302Ec63812b76E   
0xea7Ed1807c1a18bcbef9c20624a3aa05A9f0B50c 
0x6772e63e690F4f5e8e8448a1543f60B8bE31ff1d 
0x8B02faaa4DBf774b4C43F35C22772160580CCAb8  
0xc6deC38E7d170857C4111A620d2c9175374F16B7
0x4045D724656f586ae4A470d1CF7e10fecAde856F
0x6524A47C6C6085150bf16A84b0c18F716CCe1D26
0x970b1feC73b2c5ed9859384A60A70a5214447dC8

# Reasoning

the addresses in the above examples are kind of routed into each other. I have written them with arrows which shows the cross relation. It might not complete or contains 

# Methodology

Manually checked addresses from bottom of the sybil address list csv, observed cycling of routes in Hop protocol. Then followed the related addresses in the gnosis , turned out to be all of them are kind of related. 

# Rewards Address

Rewards address is the following:
0x0A09af869a835EE37dC99F29fD1F8fA19Bfdfb5c

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

It looks like the addresses you submitted were never on the eligible addresses list, as they were already labeled as a Sybil attacker by our algorithm.

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
