### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by crypto-elbarto** [hop-protocol/hop-airdrop#345]
# Related Addresses
21 addresses total

0x05f4f690f1450daae8892f76a8653004773e545c
0x3f8ff0769028b06af7aa97aa51ace9fd613a1f9e
0x2a177f4eb03695f35bb0276d6ff85779a1a4ff88
0xae15903e8384eb91e351d98dd1bad149b0ae85f0
0x232f7a2025a785efd462427163aaae34f3194a1b
0x3c6e55424afae4186f625310632d82f9c42a993b
0x56b3cacf437e12f7a15aa45f0cb199faaa6a67e9
0xa3796e9a31f55724d96cc963c4e21eee2cae9c0c
0xf8fe61dc400f46522e9e91b3eb522949d86bd888
0x9d465229d04f137f6ef34f84b7960aa2fdb76912
0x0b1add04206db11eeb23a15fd3a87f2b7e153b7a
0x6dd08bf27abda0357453e57b0e050b9ca40deb4d
0x2a9f1fef3144cd2c120ac2c5d12d1adb3c50d65f
0x4a17cc793d69680a5eec51262f0d3f26d4364b90
0x4033a32a2bc1f8f46eea7719a92b54bacddf9820
0xc5e7b677771b8adfb4e994bfc7abad1ee8e0dc7b
0xc68676bf9496e938d0b727f0209e5c27178cc2fe
0xcf86ad5358316051255cc5fdd0f54c94e4eeeab4
0xf3a65e38f82692e2bfc5c31b4025763e156e3ea3
0x5e6679522dec0a0408abb58c5cb21b358d7df107
0x1710e8b06244fba240cd7aa76293511479ae77da

# Reasoning

The first 19 addresses have an identical pattern. They all receive very similar amounts of DAI from the Aztec bridge, then transfer it via HOP. These addresses also receive the DAI around the same time, and have several windows of doing this. It indicates the attacker waited a few days to make the same transaction, but with different wallets. The last two wallets are related, given the same pattern of DAI/ETH Aztec deposit. While they do not have the same exact pattern, they both received ETH around the time the attacker started, but waited several months to make a HOP transfer. When looking at a screenshot of these addresses, it becomes obvious

<img width="568" alt="Screen Shot 2022-05-15 at 3 43 39 PM" src="https://user-images.githubusercontent.com/105606567/168491735-dc610d29-b5da-4124-a12c-3974218de8c0.png">

Example:

An address receives ETH from the Aztec bridge, then DAI. The next step is to transfer the DAI and ETH to the HOP bridge. ETH is left in the account for when the attacker pulls the money back and claims the airdrop
 
Example 1
<img width="1377" alt="Screen Shot 2022-05-15 at 4 08 36 PM" src="https://user-images.githubusercontent.com/105606567/168491973-f2b0b035-b6ac-44e7-b848-d0c4362ca274.png">

Example 2
<img width="1365" alt="Screen Shot 2022-05-15 at 4 08 45 PM" src="https://user-images.githubusercontent.com/105606567/168491976-aa847ca7-b203-40c3-a6ec-7c14213c0f51.png">

# Methodology

I first wrote a SQL query to look at a which addresses had their 5th or less transaction to the HOP bridge. Then i filtered addresses down to see how many had 5 or less transactions across all chains (Optimism, Arbiscan,Polygon, Gnosis). The idea was to look for "airdrop gamers." I then examined the funding source of these addresses, to see if an address got there ETH from exchanges. Instead, I found that a large amount of wallets had received funding from Aztec bridge. I then looked at addresses which received DAI/ETH from the Aztec bridge and found the same pattern coming up again and again. 

# Rewards Address

0xab41733192b401c88f3c0e42cacab44365530fba

**Comment by shanefontaine** [comment]
Thank you for your report @crypto-elbarto. We have verified that the addresses in this report are Sybil attackers.

The report included 18 eligible addresses as Sybil attackers which means you are eligible for 2894.43709424744089139 HOP! When Hop DAO is live, we will make a proposal for this reward — subject to a 1 year lockup, as mentioned in the [original Mirror post](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc).

Please note, you submitted 21 valid addresses, however, 3 did not follow the described pattern closely enough to have a non-negligible probability of being legitimate users. These addresses are `0x5e6679522dec0a0408abb58c5cb21b358d7df107`, `0x1710e8b06244fba240cd7aa76293511479ae77da`, and `0x05f4f690f1450daae8892f76a8653004773e545c`.

The qualified addresses are as follows:

```
0x4a17cc793d69680a5eec51262f0d3f26d4364b90
0x2a9f1fef3144cd2c120ac2c5d12d1adb3c50d65f
0x6dd08bf27abda0357453e57b0e050b9ca40deb4d
0xae15903e8384eb91e351d98dd1bad149b0ae85f0
0xc68676bf9496e938d0b727f0209e5c27178cc2fe
0x9d465229d04f137f6ef34f84b7960aa2fdb76912
0x2a177f4eb03695f35bb0276d6ff85779a1a4ff88
0xf8fe61dc400f46522e9e91b3eb522949d86bd888
0x232f7a2025a785efd462427163aaae34f3194a1b
0xf3a65e38f82692e2bfc5c31b4025763e156e3ea3
0x3f8ff0769028b06af7aa97aa51ace9fd613a1f9e
0x0b1add04206db11eeb23a15fd3a87f2b7e153b7a
0xcf86ad5358316051255cc5fdd0f54c94e4eeeab4
0xa3796e9a31f55724d96cc963c4e21eee2cae9c0c
0x4033a32a2bc1f8f46eea7719a92b54bacddf9820
0x3c6e55424afae4186f625310632d82f9c42a993b
0xc5e7b677771b8adfb4e994bfc7abad1ee8e0dc7b
0x56b3cacf437e12f7a15aa45f0cb199faaa6a67e9
```

**Comment by shanefontaine** [comment]
It looks like all addresses had similar behaviors on the Hop protocol as well:

group | address | ensName | total | mainnet | arbitrum | optimism | polygon | xdai | totalVolume
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Group 2 | 0x4a17cc793d69680a5eec51262f0d3f26d4364b90 |   | 3 | 3 | 0 | 0 | 0 | 0 | $8,558.85
Group 2 | 0x2a9f1fef3144cd2c120ac2c5d12d1adb3c50d65f |   | 2 | 2 | 0 | 0 | 0 | 0 | $8,496.11
Group 2 | 0x6dd08bf27abda0357453e57b0e050b9ca40deb4d |   | 2 | 2 | 0 | 0 | 0 | 0 | $8,392.69
Group 2 | 0xae15903e8384eb91e351d98dd1bad149b0ae85f0 |   | 3 | 2 | 0 | 0 | 1 | 0 | $3,242.48
Group 2 | 0xc68676bf9496e938d0b727f0209e5c27178cc2fe |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,345.16
Group 2 | 0x9d465229d04f137f6ef34f84b7960aa2fdb76912 |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,320.25
Group 2 | 0x2a177f4eb03695f35bb0276d6ff85779a1a4ff88 |   | 3 | 3 | 0 | 0 | 0 | 0 | $1,252.84
Group 2 | 0xf8fe61dc400f46522e9e91b3eb522949d86bd888 |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,226.00
Group 2 | 0x232f7a2025a785efd462427163aaae34f3194a1b |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,206.45
Group 2 | 0xf3a65e38f82692e2bfc5c31b4025763e156e3ea3 |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,175.93
Group 2 | 0x3f8ff0769028b06af7aa97aa51ace9fd613a1f9e |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,147.58
Group 2 | 0x0b1add04206db11eeb23a15fd3a87f2b7e153b7a |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,136.88
Group 2 | 0xcf86ad5358316051255cc5fdd0f54c94e4eeeab4 |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,125.86
Group 2 | 0xa3796e9a31f55724d96cc963c4e21eee2cae9c0c |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,097.70
Group 2 | 0x4033a32a2bc1f8f46eea7719a92b54bacddf9820 |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,070.79
Group 2 | 0x3c6e55424afae4186f625310632d82f9c42a993b |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,032.24
Group 2 | 0xc5e7b677771b8adfb4e994bfc7abad1ee8e0dc7b |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,030.74
Group 2 | 0x56b3cacf437e12f7a15aa45f0cb199faaa6a67e9 |   | 2 | 2 | 0 | 0 | 0 | 0 | $1,020.85
