### ISSUE TITLE
hop is a stupid project(hop是个傻逼项目方)

### ISSUE THREAD

**Issue by smartpaopao** [hop-protocol/hop-airdrop#350]
hop is a stupid project(hop是个傻逼项目方)
hop is a stupid project(hop是个傻逼项目方)
hop is a stupid project(hop是个傻逼项目方)
hop is a stupid project(hop是个傻逼项目方)
hop is a stupid project(hop是个傻逼项目方)
hop is a stupid project(hop是个傻逼项目方)

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
