### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by themannumber8** [hop-protocol/hop-airdrop#356]
# Related Addresses
24 Addresses

0xBd5f7F276D94aFCAc1505F93a98C0eC39a6e6A23
0x62eFcd67ee9AE5cB4d6E595Db9Ee3861E50a45Bc
0x21Fa2cf8E56B9938402A7e08703BFBe4Be0943fb
0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7
0xba07e5cb42cA05D2fc3D96514461D7245050eb7B
0x896d6845fe202B70805212E372FE29be84682fE3
0x6Ea6bc1823f6ff7b55Edf80895d053BCd1029b13
0x62D1556564Aca67d7F92c61e1946a02d83255Cb2
0x46Dd1320B44329DcAb2ce3913F0F43CCfec871B0
0xA3B9Fe8647aa9D7009B9A7Ad1D8D4A2381994eFa
0xe6E2E69030c82aFe3dE8E0E5F3d422ACA43879A2
0x5a49C6d7712C0C2d7aF6F6bfeCA8D861CB980B58
0x4D184E5198ee0b9d646cd450243DaEbEB6b8cc86
0x87f1d3359334A6c2FF5e189a91605eADe8E05459
0x84F665281B5Aa35b9CF5ebF47227Daf263f267aC
0x123743121254cbC9A33bde9221e8bb5B4742550E
0xE62b0CBc141C7F57132AB60cf2D9Ae1FFaF0384B
0xCd6051dB1539633625420af44929DDBf202E85ef
0xfcb77425AaE58e7E51FA016f4bB4196Fb9102fF2
0x13BcD144A13fEDD803d70f248Fe99Ca2AaC5E9Ac
0x4aD9f09E879B483AbBf27872868D72dB4D1B0e72
0x20959D71A7ec0212Af1b649bDB4220a9FeC3FBfd
0x0D0206f970bd67965B410956184c1F87B8cE182a
0x713f90407fc49f0BC59A6661C23FB67692a80E6d

# Reasoning

Addresses are connected ( transfer ) on different chain  . They also behave similarly, for example, most of them have been deposited from special centralized exchange, or have traded on similar platforms, or most of them hold similar nft . I have prepared a table for easier understanding. In this table, I have numbered the wallets from 1 to 24 and examined them from different aspects. In the transfer column I have included a number of connections between the wallets. Clicking on each one will take you to the desired block explorer and you can check their accuracy. Of course, there were many more transfers between a number of wallets, but I avoided bringing all of them to avoid cluttering the table. I examined the connection between wallets on four chain : Ethereum, polygon, optimism, and Arbitrum 
https://docs.google.com/spreadsheets/d/e/2PACX-1vQYE2aUEKWKRmLUML_2QTeciFKuclt9IUvSAEtrsZLIJ6PRytBEEx4pwg7fjPtQWw-8VRke-_7TyvUQ/pubhtml
Also, if you search for person's ENS addresses on Twitter, most of them have profiles on Twitter and follow each other crosswise. For example, search greennft.eth and look at its bio (it mentions its other ENS addresses in the bio). I hope the attacker does not read this article and does not change them. In any case, it does not matter because I took a screenshot of them. 

# Methodology

I assumed that an Airdrop hunter was probably looking to hunt on other platforms as well, so I shared between GURU Season Pass NFT holders and eligible hop addresses. After that, I manually checked the addresses in the relevant block explorers and used dashboards such as zapper for additional review, the results of which were included in the table that I attached to the link in the previous section.

# Rewards Address

0x7F5F2980A85B363BD9013593A3D8b4f7DB3781Fd

**Comment by themannumber8** [comment]
![4A1AAB9D-A7F3-49E3-B437-917EEB4D0912](https://user-images.githubusercontent.com/105666863/168693489-ff7c5e05-5c1a-4b12-8442-5ac41d153482.gif)

**Comment by themannumber8** [comment]
It seems that just three hours before my report, someone else reported similar addresses (of course, fewer addresses than mine). At first I wanted to close my report but I thought my report could be useful if for any reason the previous person's report was not approved . So I decided to prove that my report had nothing to do with my previous report. I have taken a screenshot of the browser history and a screenshot of the conversation with lito in the DM, as well as a screenshot of the github account creation time, which shows that I created the GitHub account one hour before the previous person's report. . All screenshots include time and date. Also, the screenshot of my conversation with lito shows that I was looking to publish my report eleven hours before the previous person's report. I also think that by reading my report and the reasons I have mentioned, you will fully understand that it is not possible to write such a report in three hours, while I have reported more addresses. Anyway, I wanted to prove that I was not a fraud and that no one would think I was cheating from previous report. If the previous person's report is approved, I fully understand that he reported earlier and the reward tokens are his right. Good luck


![Screenshot (110)](https://user-images.githubusercontent.com/105666863/168699924-dd5aabfe-9a4e-4f80-b8f2-406ebcc905d1.png)
![Screenshot (108)](https://user-image
![Screenshot (109)](https://user-images.githubuse
![Screenshot (107)](https://user-images.githubusercontent.com/105666863/168699939-742b83f0-9dd3-4121-815f-87f6eff847b9.png)
rcontent.com/105666863/168699932-fe50a3ae-8375-4e37-ba9a-880263ec6747.png)
s.githubusercont
![Screenshot (106)](https://user-images.githubusercontent.com/105666863/168699944-4bea9596-b8f5-407a-9db0-faf5197c80a5.png)
ent.com/105666863/168699927-e0e2b568-4652-4fcd-bf1b-b51a8564f1c2.png)

**Comment by themannumber8** [comment]
It seems that just three hours before my report, someone else reported similar addresses (of course, fewer addresses than mine). At first I wanted to close my report but I thought my report could be useful if for any reason the previous person's report was not approved . So I decided to prove that my report had nothing to do with my previous report. I have taken a screenshot of the browser history and a screenshot of the conversation with lito in the DM, as well as a screenshot of the github account creation time, which shows that I created the GitHub account one hour before the previous person's report. . All screenshots include time and date. Also, the screenshot of my conversation with lito shows that I was looking to publish my report eleven hours before the previous person's report. I also think that by reading my report and the reasons I have mentioned, you will fully understand that it is not possible to write such a report in three hours, while I have reported more addresses. Anyway, I wanted to prove that I was not a fraud and that no one would think I was cheating from previous report. If the previous person's report is approved, I fully understand that he reported earlier and the reward tokens are his right. Good luck

![Screenshot (110)](https://user-images.githubusercontent.com/105666863/168700365-25d53f6e-fe99-4292-af78-c9ccaa5b4b0c.png)
![Screenshot (108)](https://user-images.githubusercontent.com/105666863/168700385-c18b3c06-c50f-45bb-9489-d614688355e6.png)
![Screenshot (109)](https://user-images.githubusercontent.com/105666863/168700397-8c0409b8-b591-494a-9f92-b29c69f74560.png)
![Screenshot (107)](https://user-images.githubusercontent.com/105666863/168700406-200b5e5b-e842-4b7e-9098-5bc5e11b0073.png)
![Screenshot (106)](https://user-images.githubusercontent.com/105666863/168700418-203c327b-8ee0-4cb5-bfe4-24b1ea02687d.png)

**Comment by shanefontaine** [comment]
@themannumber8 

Thank you for the submission. Unfortunately, this submission does not meet one of the criteria for submissions:

Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours. @Iseeyou23

Thank you for the submission. Unfortunately, this submission does not meet one of the criteria for submissions:

Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

There will need to be additional proof submitted in order to consider this a valid group that does not include any legitimate users. Please consider providing more information about the behavior of these addresses, such as identical types of transactions or similar timing of transactions. Please note that another user that submits an issue with a detailed, non-negligible chance of eliminating legitimate users, their submission will be considered before yours.

We have seen a number of OTC deals, NFT direct trades, and friends sending friends funds that connect addresses like this but do not imply a Sybil attack.

Some potential compelling evidence may be:

Identical transactions on the exact same day/time by most or all of the addresses
A trace of the ERC20 token between addresses (as opposed to the trace of MATIC tokens that you have provided)
A similar time/date that all the addresses started transacting on a chain
Please let us know if you can provide this data. Thank you for your work.

**Comment by themannumber8** [comment]
OK . Let's start with the attacker's own confessions 
![photo_2022-05-17_17-04-46](https://user-images.githubusercontent.com/105666863/168933857-088b623a-15ee-424b-b0aa-7466b8f2d8d0.jpg)
Please pay attention to this user's bio ( greennft.eth , moonedge.eth , metawoman.eth , tradersvillage.eth , metajapan.eth , formationfi.eth ) 
![photo_2022-05-17_16-55-25](https://user-images.githubusercontent.com/105666863/168934391-ced87688-f189-4d5f-adfd-6cc304bfb241.jpg)
Now the photo above ( swappi.eth ) 
![Screenshot (111)](https://user-images.githubusercontent.com/105666863/168934521-f2e0596a-6478-476f-890e-06ce02a89503.png)
In the first screenshot tradersvillage.eth  is specified now with photo above add 0x87f1d3359334A6c2FF5e189a91605eADe8E05459 and  0x84F665281B5Aa35b9CF5ebF47227Daf263f267aC 
See the next photo for more reassurance 
![Screenshot (112)](https://user-images.githubusercontent.com/105666863/168935301-0425d88f-2592-4229-9e62-d9eb5541bd92.png)

Next, using explorer, I want to show the connection between other wallets : 
0x6CC8184779ef93AfCBB4441343E3b80143a4E161 (Not eligible but required to show the connection between the next two wallet )  , greennft.eth , childhood.eth 

https://etherscan.io/tx/0xad15f5d719febc5c8168c498de9ff282d54c1f82a6bfd9ee7b822245e3556155  ( Between greennft.eth  and  childhood.eth ) 

https://etherscan.io/tx/0xe6e1cb4bcd66af0d4aeccebe63acb4cfdb9b88cf0fa7e600032634b369a73c74  ( Between first wallet and  childhood.eth  ) 

https://etherscan.io/tx/0x6eb8ff7f724c8bf625380cadbb31814ee5d6804e2653900ef42f145a8a701191  ( Between first wallet and  childhood.eth  )

https://etherscan.io/tx/0xac18b892452fb3aa011f2271bb0714eae49abac2fc5230c6bb3d91d5398c78f7  ( Between first wallet and  childhood.eth  ) 

https://etherscan.io/tx/0x767c2062537a8b81aa167d228d2b541936e951194b9a0dd0be06f9c506a58c2e  ( Between first wallet and  childhood.eth  )

https://etherscan.io/tx/0x10436cfd6555d84e36bf6aabab510b35e88aea7dcef2ac5e88a9c2aa4dca1bb9   ( Between first wallet and  greennft.eth  ) 

https://etherscan.io/tx/0x2bdf3d3600224eb65b57cab4306c20b0e7fb5024f1e435af8fc13fb7e65b2c5b    ( Between first wallet and  greennft.eth  ) 

https://etherscan.io/tx/0x660b95e72f2d1a5c2902aa92803036304f2e4eb843646113be99b54f067e8263  ( Between first wallet and  greennft.eth  ) 

From 8 transfers above : ( 1 transfer Between greennft.eth  and  childhood.eth ) , ( 4 transfer Between first wallet and  childhood.eth  ) , ( 3 transfer Between first wallet and  greennft.eth  )  
As a result, greennft.eth and childhood.eth are perfectly related . The attacker also participated in the hop with the first Wallet, but did not qualify ( made 753.4691 in total transfer ) 


Prove the connection between ( greennft.eth  and  dexbridge.eth ) : 
https://etherscan.io/tx/0xd9d06a6e4643bb63b5bd6acc2f231d9df6fa6c0f36f7476c2b535c423716c16e
https://etherscan.io/tx/0x291f75a19b1d27e4f4bfa010dfdd929144e0c6a8caa4c7c6498857a47b6142d2
https://etherscan.io/tx/0x0d6d6d4e8475926ef512f12e067d9216cab6b6800785a12cb19bc68f5be8d88d
https://etherscan.io/tx/0x8c8ab0f98d6d6397dc099fb3f6abd59ccc568856ec8f3c468c42f64f93bf509d
https://polygonscan.com/tx/0xf31631ab7c74aa4240930fa1a4256ab5890d93153e6a2e19ac8aeb229a2039ae



Prove the connection between ( dexbridge.eth  and  0x13BcD144A13fEDD803d70f248Fe99Ca2AaC5E9Ac  ) : 
https://polygonscan.com/tx/0xa3b4b6516cb77badea81ae74204f2f4cbf6b577a5ee6bf67f5984929e8850641
https://polygonscan.com/tx/0xc9eead503fbc1b79be2a3754d3927ba4ce5f50732cfa7b79daa68c54a082c754
https://arbiscan.io/tx/0xc4483dd7d045e605203b0ee32a98a4370bd408d30b098503ba9eb8e14037bf23
https://arbiscan.io/tx/0x02c88b1dc9e724f8aaa6cd864895155c419521156228201dbdd96821113ea766
https://optimistic.etherscan.io/tx/0x344687c2ddd4cef83c806ff9a9ad38ee46ef289c7a145b5e6d95af68ccf4d435
https://optimistic.etherscan.io/tx/0x7cd7fcb9eadaa41788656fc8dea1516070ed648b7ec57d462a2593281b8329fa


Prove the connection between ( 0x13BcD144A13fEDD803d70f248Fe99Ca2AaC5E9Ac  and  0x4aD9f09E879B483AbBf27872868D72dB4D1B0e72 ) : 
https://polygonscan.com/tx/0x4fd8cdc83adedc995655f8bba0f7a3e0f2518ae77c8b893ff5eb3894c384d908 
https://arbiscan.io/tx/0xa0b562a7ebf3f7d53dfdcaea2718fea4b03296791f2de44b166b00d361cc4add
https://optimistic.etherscan.io/tx/0x7e00f7a848cb4eb2569c6486ac0bc6d81ee7a0a631b8c11d7dc0138a18bede58


Prove the connection between ( 0x4aD9f09E879B483AbBf27872868D72dB4D1B0e72 and 0x20959D71A7ec0212Af1b649bDB4220a9FeC3FBfd ) : 
https://polygonscan.com/tx/0xde297650c2614e083b1d3c13788374abe70977e228c9285def0d4d4e8bfd8e5b
https://optimistic.etherscan.io/tx/0x81afc8c915831f8f1c0d630ecbc6c37590bf812f45a765c0a7b5a7807753680f
https://optimistic.etherscan.io/tx/0x354fe060431146ed34b4fd39c4a810c4e51c61c082a9802cec889e2c3e118803



Prove the connection between ( 0x20959D71A7ec0212Af1b649bDB4220a9FeC3FBfd and  0x0D0206f970bd67965B410956184c1F87B8cE182a ) : 
https://polygonscan.com/tx/0xc3af414fec112a9b815b31ae268650727270c8809facb3536cdb4cb0c9f7f585
https://arbiscan.io/tx/0xe7154e3212fc7a6c8dc2f9149c3049cc4d2bfd6d9ba2f5e9f701b290ebc83815
https://optimistic.etherscan.io/tx/4902430
https://optimistic.etherscan.io/tx/0x1a2a5c804b3dab523c61e76e22149d6dd75b5b7a49b391d571f7166eb4ae0a42


Prove the connection between ( greennft.eth  and  ssvip.eth ) : 
https://etherscan.io/tx/0x7990938fd8890d65ea6493070ac43dab4bee0d158393f13ee26b82ee7cd83bdb
https://etherscan.io/tx/0xce731f70f60299e1b12c58c69ff2dadadd3aa535566f5cf755bb2205ce98be08
https://polygonscan.com/tx/0xc46ddb7dc4bbf86cb485e719b17cd13525e3369e1f45a37942ee6c3a9a23fa3a



prove the connection between ( 1money.eth  and  ssvip.eth ) : 
https://etherscan.io/tx/0xaf8fb4bc3c21937b1a323372cbad165196703560f75beee058e5093276a59f8c
https://etherscan.io/tx/0x5116263c9575429c3f03264daaa940e06d920cc4806af6df8545775ce3eaf5fb
https://etherscan.io/tx/0xfa33124b290614c9e41bde128c4a2479062568101940786238ebc9b6b212ef94
https://etherscan.io/tx/0xa7b76a24a3d4174bb2f55d83f63d845b94479d0b00f6019b9d29bcfb424637ac
https://etherscan.io/tx/0x87ab7a4a0fcc9c6bf1be06b6e95eac204a4c3ab7f2ee55d6f3400a7c63d4b3b9
https://etherscan.io/tx/0x30ff72d6f250da711fcca5a2fa03fa80a230c961ea6d397418931b39c5c23fcc



prove the connection between ( ssvip.eth and  0xBd5f7F276D94aFCAc1505F93a98C0eC39a6e6A23 ) : 
https://etherscan.io/tx/0x0c1e3a8c9be4b6630f3e7b9b2649c6d55fb2c89a3790238c1bab7794c785cbfb
https://etherscan.io/tx/0x6dbecb9ac21b085634b76146fd2c719a8db2630c61b1053c5d8a37c5b4cf523d
https://etherscan.io/tx/0xc4ff2ed9031b599bff50bce01642fd0105f0833017e44671735bd97aae0f4ac3
https://etherscan.io/tx/0xe684e805ccaa70414382f75757a085eef462151c4cc28c276f20d1b8ad2dff40
https://etherscan.io/tx/0xd72d7c235d692c4672f8267f07a987fbc3ac4f3b02769e72c4ef928d4b70c7b5


Proof of wallet 0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7 : 
https://etherscan.io/tx/0xa1421ecb68320af0b9e21a59f90969cc32597452f3e8f61aa670e10e46f261d0
(between ssvip.eth and  0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7 ) 

https://etherscan.io/tx/0xe32fa5d9054de903b5a248be6c512f0db1175f6c255f594aa197cfb9298756b3
(between 1money.eth and  0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7 )

https://etherscan.io/tx/0x8b1bfbfa6cc6d47caae5d0a73edb5959e0ed3089bdcd9eaf914df13af2adacd3
(between 0xbd5f7f276d94afcac1505f93a98c0ec39a6e6a23 and  0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7 )

https://polygonscan.com/tx/0x17dbd39ef86b06def516053d3688479a81ec3d782dccee6c28b3b5f984e3060f
(between 0xbd5f7f276d94afcac1505f93a98c0ec39a6e6a23 and  0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7 )

https://arbiscan.io/tx/0x363fe8f91eb4cfa0a18ac4b39e16184be579214ed65ace172f848272c3910a99
(between 1money.eth and  0x2347b1B2B8Cd9eE89Ce4fA8c12F05bF65EB123E7 )



Proof of three wallets greennft.eth and  moonedge.eth and  0x84f665281b5aa35b9cf5ebf47227daf263f267ac  was given first, now using these three wallets, we prove the fourth wallet ( 0x5a49c6d7712c0c2d7af6f6bfeca8d861cb980b58 )
 
https://etherscan.io/tx/0xc6d07ec3c86a7fd50d991a4016db06c9444343e6f6f78c57522fad9158f2d053 ( fourth wallet and greennft.eth )

https://etherscan.io/tx/0xb5133fbe900cc3195c08fe66941ec0627532b7851c8f0de351a14e3699080061 ( fourth wallet and 0x84f665281b5aa35b9cf5ebf47227daf263f267ac ) 

https://etherscan.io/tx/0x3f9456f70595268335da16d887b96f6ff5012df8d023ed634cc795954f5abd24 ( fourth wallet and moonedge.eth ) 

For the four wallets baiduhub.eth, dashabi.eth, xiaoshabi.eth, and mobilesuit.eth, I could not find enough reasons through etherscan, and only two transactions in the polygon connected them to other wallets. So I deleted these four wallets and listed a total of twenty wallets with enough reasons .

**Comment by themannumber8** [comment]
In addition to the screenshots, there was a  transfer between the wallets that I showed the connection with the screenshot at the beginning of the text above, which you can see in the table that I put in the initial report.

**Comment by shanefontaine** [comment]
Thank you for your report @themannumber8. We have verified that the addresses in this report are Sybil attackers.

The report included 18 eligible addresses as Sybil attackers which means you are eligible for 3542.757087604775790891 HOP! When Hop DAO is live, we will make a proposal for this reward — subject to a 1 year lockup, as mentioned in the [original Mirror post](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc).

Please note that the accepted addresses were clearly and obviously related. Some of your submitted addresses were not included due to the fact that there was a non-negligible probability of eliminating legitimate users.

The qualified addresses are as follows:

```
0xba07e5cb42ca05d2fc3d96514461d7245050eb7b
0x62d1556564aca67d7f92c61e1946a02d83255cb2
0xe6e2e69030c82afe3de8e0e5f3d422aca43879a2
0x46dd1320b44329dcab2ce3913f0f43ccfec871b0
0xbd5f7f276d94afcac1505f93a98c0ec39a6e6a23
0x4d184e5198ee0b9d646cd450243daebeb6b8cc86
0x21fa2cf8e56b9938402a7e08703bfbe4be0943fb
0x87f1d3359334a6c2ff5e189a91605eade8e05459
0x896d6845fe202b70805212e372fe29be84682fe3
0x84f665281b5aa35b9cf5ebf47227daf263f267ac
0x62efcd67ee9ae5cb4d6e595db9ee3861e50a45bc
0x2347b1b2b8cd9ee89ce4fa8c12f05bf65eb123e7
0xa3b9fe8647aa9d7009b9a7ad1d8d4a2381994efa
0x6ea6bc1823f6ff7b55edf80895d053bcd1029b13
0x13bcd144a13fedd803d70f248fe99ca2aac5e9ac
0x4ad9f09e879b483abbf27872868d72db4d1b0e72
0x20959d71a7ec0212af1b649bdb4220a9fec3fbfd
0x0d0206f970bd67965b410956184c1f87b8ce182a
```

**Comment by shanefontaine** [comment]
In addition to the data you provided, it looks like:

* All accepted addresses had the same Orbiter.finance transaction behavior on Arbitrum on April 27
* They shared similar behavior on Hop protocol


address | ensName | total | mainnet | arbitrum | optimism | polygon | xdai | totalVolume
-- | -- | -- | -- | -- | -- | -- | -- | --
0xba07e5cb42ca05d2fc3d96514461d7245050eb7b | greennft.eth | 14 | 0 | 3 | 3 | 4 | 4 | $3,272.59
0x62d1556564aca67d7f92c61e1946a02d83255cb2 | metawoman.eth | 14 | 0 | 3 | 3 | 4 | 4 | $3,058.34
0xe6e2e69030c82afe3de8e0e5f3d422aca43879a2 | formationfi.eth | 10 | 0 | 2 | 2 | 3 | 3 | $2,824.09
0x46dd1320b44329dcab2ce3913f0f43ccfec871b0 |   | 11 | 0 | 3 | 2 | 3 | 3 | $2,811.52
0xbd5f7f276d94afcac1505f93a98c0ec39a6e6a23 |   | 21 | 0 | 1 | 3 | 6 | 11 | $2,660.13
0x4d184e5198ee0b9d646cd450243daebeb6b8cc86 | metajapan.eth | 11 | 0 | 1 | 3 | 4 | 3 | $2,567.85
0x21fa2cf8e56b9938402a7e08703bfbe4be0943fb | ssvip.eth | 21 | 0 | 0 | 1 | 9 | 11 | $2,565.46
0x87f1d3359334a6c2ff5e189a91605eade8e05459 |   | 9 | 0 | 2 | 2 | 2 | 3 | $2,447.18
0x896d6845fe202b70805212e372fe29be84682fe3 |   | 10 | 0 | 1 | 3 | 3 | 3 | $2,442.24
0x84f665281b5aa35b9cf5ebf47227daf263f267ac |   | 10 | 0 | 1 | 2 | 4 | 3 | $2,399.65
0x62efcd67ee9ae5cb4d6e595db9ee3861e50a45bc | 1money.eth | 19 | 0 | 1 | 2 | 5 | 11 | $2,296.11
0x2347b1b2b8cd9ee89ce4fa8c12f05bf65eb123e7 |   | 15 | 0 | 0 | 1 | 4 | 10 | $2,257.71
0xa3b9fe8647aa9d7009b9a7ad1d8d4a2381994efa | tradersvillage.eth | 11 | 0 | 2 | 3 | 2 | 4 | $2,093.68
0x6ea6bc1823f6ff7b55edf80895d053bcd1029b13 |   | 3 | 0 | 0 | 1 | 1 | 1 | $1,049.04
0x13bcd144a13fedd803d70f248fe99ca2aac5e9ac |   | 3 | 0 | 1 | 1 | 0 | 1 | $1,037.44
0x4ad9f09e879b483abbf27872868d72db4d1b0e72 |   | 3 | 0 | 0 | 1 | 1 | 1 | $1,028.31
0x20959d71a7ec0212af1b649bdb4220a9fec3fbfd |   | 3 | 0 | 1 | 1 | 0 | 1 | $1,018.11
0x0d0206f970bd67965b410956184c1f87b8ce182a |   | 3 | 0 | 0 | 1 | 1 | 1 | $1,008.72

**Comment by gududefengzhong** [comment]
thank you  for your hard working.

greennft.eth  metawoman.eth  formationfi.eth is actually mine
please take a close look at my previous issue
https://github.com/hop-protocol/hop-airdrop/issues/258

**Comment by gududefengzhong** [comment]
It is normal for a circle of friends to have similar chain operations.

ssvip.eth and 1money.eth and tradersvillage.eth belongs to several of my friends, please take a close look at your analysis

thank you

**Comment by gyltlsc** [comment]
Dear admin, "ssvip.eth" belongs to me.
I have been in the currency circle for about 10 months, and I have been using hop for about 6 months. I only came into contact with these projects under the guidance of my friends. Many of my friends in this issue include my wife (0xBd5f7F276D94aFCAc1505F93a98C0eC39a6e6A23) and A colleague (1money.eth), this is the truth, I'm not lying, I have a clear conscience.
We are not practitioners in the Internet or information technology industry and lack professional knowledge, so we need to learn together, guide each other, experience and use some projects of interest together (including the leading projects in the cross-chain bridge— —hop), so there may be some similar trading behavior and trading hours. In addition, we are all ordinary migrant workers with average income, and the funds for experience projects are very limited, and each operation has a loss of funds, so we will have funds borrowing (borrowing and returning), which results in that our address have some transaction connections.
Users are the foundation of the community and the soul of the project. We are all real users who have recently entered the business and are also loyal users of hop. We have a lot of transaction times and amounts. As real and loyal users, we should get a little airdrop of the project as a reward, which can also compensate for the transaction loss and gas，also can inspire us to continue to support hop, experience other projects, and make this industry more and more prosperous!
This is the appeal issue I submitted earlier:
Please verify again and re-evaluate your decision, thanks a lot!

**Comment by gyltlsc** [comment]
> Dear admin, "ssvip.eth" belongs to me.
> I have been in the currency circle for about 10 months, and I have been using hop for about 6 months. I only came into contact with these projects under the guidance of my friends. Many of my friends in this issue include my wife (0xBd5f7F276D94aFCAc1505F93a98C0eC39a6e6A23) and A colleague (1money.eth), this is the truth, I'm not lying, I have a clear conscience.
> We are not practitioners in the Internet or information technology industry and lack professional knowledge, so we need to learn together, guide each other, experience and use some projects of interest together (including the leading projects in the cross-chain bridge— —hop), so there may be some similar trading behavior and trading hours. In addition, we are all ordinary migrant workers with average income, and the funds for experience projects are very limited, and each operation has a loss of funds, so we will have funds borrowing (borrowing and returning), which results in that our address have some transaction connections.
> Users are the foundation of the community and the soul of the project. We are all real users who have recently entered the business and are also loyal users of hop. We have a lot of transaction times and amounts. As real and loyal users, we should get a little airdrop of the project as a reward, which can also compensate for the transaction loss and gas，also can inspire us to continue to support hop, experience other projects, and make this industry more and more prosperous!
> This is the appeal issue I submitted earlier:
> Please verify again and re-evaluate your decision, thanks a lot!
