### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by izcoser** [hop-protocol/hop-airdrop#360]
# Related Addresses

20 addresses: 
```
0x8e8e31cfb9298a432e24b7f94acf06bec8f5c887
0xfeb41f10aa0a08ac4ee0af30e0d0ee0ad225fd5d
0x5e1e0f59774052344cad68939025f2d959bd6e79
0x23fe60c2e63ddcc13d651946c24baace2bc295e2
0x8fb6db87f556a8207870abd3fae7ffbbaaae7b34
0x31e9a9a158d88628beffb2dfb8319615e377edf0
0x0a782717fc13e2158e09d129b2b58317cf30fdfc
0xc31be59f5522c4e3a89bc3e863f97e6f8253a21c
0x39af030facc2da718b12c490054c1f75887e862b
0x27dac4f72f2de2c4d8c1d702f25009ac7e189106
0xe1ad4a3f64df1c98fea91af310445bd0aea6dec0
0xddf85cb54be5ad31e9e14418233ca80e59eca2ff
0x732a38e6248109693bf63db97965f6cb6b087d2d
0x377361b23bc15310d32b7687aeb2d8e3950150de
0x017b6a73810a6223542044174144d7d4f5575656
0x45cf15179926a12ec50135cb291a73a14662fb51
0xc4a6ab2e75e52ecf18aae6f27d674a9794d623c3
0x2fabd827ed6802056ca189547965b74bb0ce057b
0xf978302181fb8cf711e5c38bbc9377ec1aa8b4a9
0x85f810fb757077ac011c39f9b398b6ad41430b32
```
# Reasoning

All of these addresses fund each other and have very similar numbers of transactions which occurs at similar times.
I only found them because the attacker poorly boasted about this on Twitter, showing his addresses and rewards. 

# Methodology

I found a person on Twitter boasting about his many accounts with airdrop rewards, the accounts were not properly censored so I was able to find them using the eligible list.
Then I manually went through the accounts on Etherscan and found that they do indeed belong to the same person, as explained previously.

I made a spreadsheet on Google docs to show the interactions between the accounts, available [here](https://docs.google.com/spreadsheets/d/1hPdMuLhZrh3aZAzmM9CWymDjHeY7z37LVf--Xve2SbU/edit#gid=0).

Archived Nitter (Twitter alternative frontend) link showing the user "hi_aewalle" and his addresses: https://web.archive.org/web/20220517030646/https://nitter.it/hi_aewalle/status/1526037968149852162
Screenshot of his tweet: https://i.imgur.com/hV9LoFL.png
Actual tweet: https://twitter.com/hi_aewalle/status/1526037968149852162 (may be deleted at any time)
Image posted by the attacker: https://i.imgur.com/bXqBpm2.jpeg (many of the addresses are visible)

# Rewards Address

igorc.eth

**Comment by shanefontaine** [comment]
Thank you for your submission @izcoser.

It looks like most of these addresses were submitted with a detailed explanation in #331 . Because submissions of 20+ were considered before submissions of 10+, your submission is no longer valid. I will close this now.
