### ISSUE TITLE
https://github.com/hop-protocol/hop-airdrop/issues/346

### ISSUE THREAD

**Issue by jukjh** [hop-protocol/hop-airdrop#378]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jukjh** [comment]
https://github.com/hop-protocol/hop-airdrop/issues/346

**Comment by jukjh** [comment]
https://github.com/hop-protocol/hop-airdrop/issues/346

**Comment by jukjh** [comment]
Why？
There are a lot of addresses here that are not mine

**Comment by jukjh** [comment]
You are malicious reporting, malicious attacks, and harming real users for your so-called interests. you are hurting others

**Comment by jukjh** [comment]
Are you the police? The police want evidence. Your so-called evidence is bullshit. I only have 17 addresses in it. You are connected to twenty or so. why

**Comment by jukjh** [comment]
You don't check hundreds or thousands of addresses.Check out a dozen or so addresses，I just want to ask you. Do you have more than a dozen bank cards or credit cards?

**Comment by jukjh** [comment]
You don't check hundreds or thousands of addresses.Check out a dozen or so addresses，I just want to ask you. Do you have more than a dozen bank cards or credit cards?

**Comment by jukjh** [comment]
You don't check hundreds or thousands of addresses.Check out a dozen or so addresses，I just want to ask you. Do you have more than a dozen bank cards or credit cards?

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
