### ISSUE TITLE
sybil attacker report 

### ISSUE THREAD

**Issue by zachxbt** [hop-protocol/hop-airdrop#4]
67 Related Addresses

```
0x04d0422ab7e1422c4f921d8c8864c6c2428ad4c9
0x57a4348ada7f4d5ec2d85309008f119a6e8f82a5
0x13777A8f845Fd6048f8CEFc2EAaa2c54C7019d47
0x15187377698e9003e0dc339dcc75901e00c979bb
0x3511e13dc1af7b6083c53e308f6acf70dae5f2cc
0xfd8cad34edb90c6b9cd00bd44712ad2b9b34d609
0xe733309ad12a87cd12e853d4f02eda88ef815a18
0x4015a04fad200c27160f81059ad548b3840d9b49
0x57ff4df705e76f249df14cbfbf186a453e21d08a
0x445d95e0b66424072983c8218f1326f5ce39c779
0xf99f75ebf2e39b36473c375fbaaa02120e8d55ff
0x93d3c359141a20b908eae9eda4a2b6e6e1fcff8a
0x577b78c5d7151379fecbe3204d2cef756cf1087a
0x3e8e0de29c003d6fb1f4d1d61341cd3b2aa9b9a3
0x762a43a2eb659dab6971678efba2a8906ffe79bf
0x9d92a98a9c4cca7e89b230c7979e7aa3404c28df
0x831d085efd652df4d408c3fa69b3f498d697d8d0
0x12bfb3fe98b90a728d6ee6f6f87c81642e945e64
0x49bd33765cc8f3d0be93e1c4ccb45368d095470f
0xb27c2d62492425202af463ebcd8922dcc85bee1f
0x165d7d4ab4cb23d7decaa6cd0e7475654c284fc6
0xe0f68c2f25bc8bf03f84289402b64cf9826f49f1
0xb07740008db5e90ce0cba6942569a0baa27b48e8
0x7dff783e65b647e16c1275913c4ee441b7040c3d
0xfb32776555b25d0e82b2de274b44ccc91a3fac95
0x85477cefe403c53b02aa57f2347a75a447021e46
0x5e60ee79ea5a4cd8575e3c718246d7218d9eefb8
0x03f4e44589413e7fd283cfe48e4e04e42eb14a24
0xbb2c75acf8404882375e61fea0780af327acd948
0x1aa782b56285355355b8457712fc8db072cd1559
0xa3cfa8c8f190a9689013c23cdc845d92432848b5
0x331c8de5fd98127a9ab78f22520b3254d3208005
0x9cc4a8c3c76f4b06e9d9979c263c6b9e45733898
0x24f4f9f4de83f08812d2006a272edcd3bda31723
0x7c92c65147f534513906e30aaa7e651c31115054
0x3aaa6d65736fee0ba40ac62b72d454bf6e61cdea
0xca4b534b413ebb3af3101b9acb3e1956ddbd7a79
0xd92e72e3858f8beca569173bf4395646ed090050
0x4334aa9e8aeb1c4e037bf8a84a841704fedda220
0x2ac1e9f9ee30d19d8bb62360e59e4761816e66c3
0x7a3a4e7d47b0992ccf3791b17dd223cdc977e0a9
0x4232f59d37d96ec049b2897dc80e0621008ccf29
0x37736cac092bed673d09380abda0e001054cded6
0xcc4af35fdcab62cd4636f87a9498fc6fde54e767
0x16a8cf375ebe076ea82a4a9dbc70f7203d4fa512
0xb80273c8bd5a41ce513f7283a7b15905861e5583
0xf1db4b8933a0bd45f7da020b0d2d846049920714
0x1c8acb794c60afc54f812e2c9ee2de60522020e6
0x7e2a58eac5e8d978e54a33d47f588b31a4b8733e
0xaa0770d195783dd0c9e08a0230c906760b72e901
0x8d3b43e495888d84e182ee3cf9a8d5f3b6a327b3
0x40490faa37a5127bf45b855e1b1e30f62a236030
0x6d6bf82a78965106d46c56652b955f3ed6fee514
0x0d18b613fb398b850b15c17269c262522e0a9a8f
0xae0e56c30b549946db0ce2c73d1d8aaaf97bc13a
0x156f3c465610698fa096ae01ae7b0b1eb54fba1d
0xa57f2e16baaab8927844b549c166531188765af9
0x845ee4cc57453a433fc3e6a057109f7704281d66
0xc428c4c610cbeca52d643736664c82561ef92858
0xedc85347bc63657906ee4394af43133b8e737b5f
0x7b7b035737202d16840440001e99203a6842686f
0x3cc622771851b96ef7c8201a32436349fd8ec968
0x1d31e9b808759128d64c688c243aa8795f441a75
0x00dcc080bd0a65ffeb5926e83b5bc4b5a3f088a5
0x3459a947fa186cdcd6107711c2739ed6194ae8d8
0x69c30bbb439e5fdfdf461f23e50d0a6f701a3f2a
0x67c1d41b8b84f7f075991254d868d6c67d4950c4
```

# Reasoning

All addresses receive 0.1 MATIC and 30 or 50 USDC from 0x13777A8f845Fd6048f8CEFc2EAaa2c54C7019d47 on Polygon from 11/6/21 to 11/21/21. They then receive $550+USDC from a previous address. They first addliquidity for USDC, stake, And remove within a minute. They then swap hUSDC for USDC and send away USDC to the next address.

Example:
https://debank.com/profile/0x156f3c465610698fa096ae01ae7b0b1eb54fba1d/history

# Methodology

The reported addresses were discovered by manually reviewing addresses from the airdrop raw dataset. Once discovered a potential sybil, then look to see where the funds originate from. Once the origin was identified I downloaded the transactions from PolygonScan and identified repeating patterns. 

Funding source:
https://polygonscan.com/address/0x13777A8f845Fd6048f8CEFc2EAaa2c54C7019d47
Debank:
https://debank.com/profile/0x13777a8f845fd6048f8cefc2eaaa2c54c7019d47/history
Example:
https://debank.com/profile/0xad7b59fed224e947f481d2628249d63ed0e32f80/history

# Rewards Address

0x9d727911b54c455b0071a7b682fcf4bc444b5596

**Comment by cwhinfrey** [comment]
Hey @zachxbt, not seeing any content here. Can I close this one?

**Comment by cwhinfrey** [comment]
@zachxbt I saw that your report was hidden since it was between the hidden comment markers "\". I updated your comment to unhide the report and we'll get it reviewed asap.

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt). Please note that the submitted addresses _may_ have existed on the list before, but someone might have submitted these addresses as a Sybil attacker before you did.
