### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by xp-git** [hop-protocol/hop-airdrop#423]
# Related Addresses

0x39Af030fAcC2dA718B12c490054C1F75887e862B

0x0a782717Fc13e2158e09D129b2b58317CF30FdfC

# Rewards Address

0xE1928C69153B377DBb5f4d170d720b5632b7Bf7D

**Comment by Bobb2906** [comment]
🤣 2 adresses?

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, there needs to be at least 10 eligible addresses per submission. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

I will now close this.
