### ISSUE TITLE
I'm not Sybil Attacker 

### ISSUE THREAD

**Issue by Jinghao-coding** [hop-protocol/hop-airdrop#448]
This is my addresses,0x68c41a057E660bC9DFBbaf83835EFb65C4f379CC,I am a real user，not Sybil Attacker

My addresses do not follow the "ping-pong" pattern as described by @pileofscraps . 
https://explorer.hop.exchange/?account=0x68c41a057E660bC9DFBbaf83835EFb65C4f379CC

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
