### ISSUE TITLE
sybil attacker airdrop is end?

### ISSUE THREAD

**Issue by cryptodaun** [hop-protocol/hop-airdrop#449]
sybil attacker airdrop is end?

**Comment by KaranRoy007** [comment]
No. It's still ongoing

**Comment by lohloh12** [comment]
Kommunistische Schweine

**Comment by 0xtoshi** [comment]
its still open until 24th

**Comment by HOPRATTEN** [comment]
Kommunistische Ratten

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.
