### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by qnmdzg** [hop-protocol/hop-airdrop#452]
# Related Addresses

0x7e0207d0c54cb91763d2d3bcc9a6cce349883409 
0x450af8222eb06e87b3566c7ff2e0e2a425427699
0x7fd9b6e2e4296a13577e6f8ab312da43df706e77
0x6f35109ddc4f3d1111b2ed82273b07755a1e923a 
0x7799648908de1565a9496098cbeb0257cf069b8c 
0x176396839fa923ec224e391da85089a16323e350 
0x276cd992ef150f7ab40caedea8eca429ec80b1ba
0x40930039d6c3E8c322E58E6D289245bFa826bfE4
0x87ae9672cf172124fac96ff7834f6b4331eaf94b 
0x4b710f9da3ff4a85284198aad2270775e2544f78
0xc27771fef68b052790bd3ab4f05ae2454b0a34a9 
0x87ae9672cf172124fac96ff7834f6b4331eaf94b 
0x6d63034b0b31c88c3667a4f35ca4793ccab73bfd 
0x9bea6364d6465dbf7a8efd5ca5699881b2d5f525 
0x483b7fc91dc1b4a2361fb98eccb8034f1ff9a914 

# Reasoning

1. Do a lot of Sybil attacks in the same time （hop，clipper，Wrapped, slingshot，），All of attacked project don't have token（hunter AirDrop） 
2. have the same transmission chain

# Methodology

![image](https://user-images.githubusercontent.com/41881700/169366204-2e7e5f63-3fcc-4a4d-93df-4708a06250ab.png)

![image](https://user-images.githubusercontent.com/41881700/169366609-2954be96-c60d-4d9c-9aac-0918fb2c07fa.png)

![image](https://user-images.githubusercontent.com/41881700/169367026-b2b893ee-c879-4991-af89-7984f64145d2.png)

# Rewards Address
0x2E1dAfc06A3A69483B7F5558F4e5a3cB68f434Bd

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only two of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

It looks like most were reported in #177 and #354.

I will now close this.
