### ISSUE TITLE
Sybil Attacker Report--shdwy

### ISSUE THREAD

**Issue by Forweb31** [hop-protocol/hop-airdrop#490]
Our rules are: The person reporting must be a hop user . But I see a lot of person reporting who are not our users, but they do go through the entire reporting process! 
shdwy  ，He completed 10 reports, but the address he provided never interacted with the hop. （0xD47CB1835EB36e4A108C33E446449192426Fc160 ）
So the whole proof process should not be established. for not complying with our reporting process and rules.
I have a few questions, if he is a real user why doesn't he provide his real address? Why provide an empty address?
This just shows that he is the real witch attacker. Make no mistake!
Lastly, I would like to say that if I report his reporting violation, then I should be rewarded for reporting.
All certified whistleblowers, we believe they should provide evidence that they are hop users. Otherwise all certifications are non-compliant, and I will prove them one by one.

**Comment by Forweb31** [comment]
Next, I will list all those who did not meet the reporting process. I suggest that the official do a whistleblower certification which is very necessary. This is also a necessary measure for the completion of the report. Otherwise it would be another witch attack.

**Comment by Forweb31** [comment]
If there is a problem with the proof process, then this is false proof. The proof is not established, so the certification is also not established. I am still continuing my search for evidence that they are hop users. But unfortunately I didn't find it.

**Comment by shdwy** [comment]
I'm guessing I reported one of your addresses, tough luck. If the team requests I provide another reward address, I wouldn't mind doing so.

**Comment by Forweb31** [comment]
0x7d3f6048091aEdE6198736b8C6ac527c314e25ff （[GreyPK] (https://github.com/GreyPK)）He has 15 violations
0xBCCD7DF161C0d155D3E56D8C57Cc31C185217546（[stabiloswano](https://github.com/stabiloswano)）He has 3 violations
0x61bC799fD0EB6C791E1cF22E1e9908635444d5A6  [zlgitol](https://github.com/zlgitol) He has 10 violations
