### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Forweb31** [hop-protocol/hop-airdrop#491]
https://explorer.hop.exchange/?account=0x483b7FC91dc1B4A2361FB98EcCB8034F1Ff9A914&amount=rotate.eth
![image](https://user-images.githubusercontent.com/105897625/169438005-237799c3-9e9f-422a-9ff0-15316692a868.png)
This is a whistleblower who has completed 14 reports, and I see his address in the interaction of hop. as the picture shows. A large number of repeated from polygon to xdai at the same time; as he himself analyzed, this is a classic witch attack. He himself listed numerous such operations and made detailed arguments. I'm sure you've all watched it many times, and I've learned a lot from his reasoning, which is why I figured out he's a witch.

rotate.eth  This address has accumulated more than 100,000 rewards, which should be cancelled because he himself is the real sybil attacker. @shanefontaine

**Comment by Forweb31** [comment]
rotate.eth （0x400aBc3DAE98Ec5aEEF2681b40D4CEd0A5aff934） 
This is his eth address, I hope everyone can help me find out more of his associated addresses! The witch is unforgivable!

**Comment by yohr182** [comment]
Your analysis makes a lot of sense, as you said, the reporter is probably a member of Sybil. Generally speaking, only people with certain programming skills would use scripts for large-scale Sybil attacks, because civilians don't know how to write scripts, and the team encourages mutual reporting, giving Sybil the opportunity to report others. This is definitely giving the confiscated hop back to the witch, but the team doesn't realize it

**Comment by shanefontaine** [comment]
I will close this now, as there is no actionable content.

**Comment by rotate-eth** [comment]
Good attempt at manipulation guys but you aren't fooling anyone.

That isn't my address. You simply took a verified sybil address (from report #354) and wrote "rotate.eth" in the "Amount" field 😂 Amount is for filtering transfers by a dollar amount, not searching for an address, so it's meaningless.

My real address is here:
https://explorer.hop.exchange/?account=0x400aBc3DAE98Ec5aEEF2681b40D4CEd0A5aff934

**Comment by Bobb2906** [comment]
> Good attempt at manipulation guys but you aren't fooling anyone.
> 
> That isn't my address. You simply took a verified sybil address (from report #354) and wrote "rotate.eth" in the "Amount" field 😂 Amount is for filtering transfers by a dollar amount, not searching for an address, so it's meaningless.
> 
> My real address is here: https://explorer.hop.exchange/?account=0x400aBc3DAE98Ec5aEEF2681b40D4CEd0A5aff934

![kinblood-ko](https://user-images.githubusercontent.com/105102923/169692000-089185ae-46d9-4aa4-a8bd-4f25376c1a53.gif)
