### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by vitalion230** [hop-protocol/hop-airdrop#57]
# Related Addresses
1st BATCH

0xE5c8B08A3597593835fD7EeBD002F0272F8F51eA
0xea664909e13134099a08D358ef3888C545e822d3
0xaa087281cFd53FbB4305F095d5eB23A732E6B3fF
0x54b2Cb178a2D5230aC02548Fe8597F5aA3758167
0x59b5C603Cc4f3Bf20818b7B57c2284F9309ab37F
0xE11B5f63024327E1E686ED7474323166bF7F84C2
0x4CD3DB23E7d069B1a0c9E08A2467dbDDEaa52bf9
0x8264746184800A2bC06B76C7b4227556cf94747C
0x78624f62021e9d3808df8D6d8e4701ACABCBA008
0x8cA23135f5Bb829beCccb327482BCD2417fF5B47
0xf6b6747B59c47CEEF405e302C26F46466dd2f9A1
0x2563aEEa9284708A3FeDFF1CaB0881286bB4C486
0x8b1fEf0A21728E1f626c44E598288f89279F060c

2nd BATCH

0x8cA23135f5Bb829beCccb327482BCD2417fF5B47
0x78624f62021e9d3808df8D6d8e4701ACABCBA008
0xaa087281cFd53FbB4305F095d5eB23A732E6B3fF
0xea664909e13134099a08D358ef3888C545e822d3
0x8264746184800A2bC06B76C7b4227556cf94747C
0x4CD3DB23E7d069B1a0c9E08A2467dbDDEaa52bf9
0xE11B5f63024327E1E686ED7474323166bF7F84C2
0xE5c8B08A3597593835fD7EeBD002F0272F8F51eA
0x59b5C603Cc4f3Bf20818b7B57c2284F9309ab37F
0x54b2Cb178a2D5230aC02548Fe8597F5aA3758167
# Reasoning

1st BATCH
Transfers 0.01 ETH from 0x09181e2D4242337334a73399a1C777B792983665 to addresses on ETHEREUM MAINNET, minting GURU pass, also eligible for hop airdrop. Hold GURU NFT on Ethereum Mainnet.

2nd Batch
Absolutely identical actions on addresses, sybil attack on other projects, determined by MATIC and TOKENS transactions inside the addresses themselves that create the chain.

# Methodology
# Rewards Address

0xFB7c1D49e006eaDdff2385c7eF8B0C5Cf49d038A

**Comment by shanefontaine** [comment]
This submission only has 13 unique eligible addresses.

**Comment by shanefontaine** [comment]
Thank you for your report @vitalion230. We have verified that the addresses in this report are Sybil attackers.

The report included 10 eligible addresses as Sybil attackers which means you are eligible for 1696.17401830068178953 HOP! When Hop DAO is live, we will make a proposal for this reward — subject to a 1 year lockup, as mentioned in the [original Mirror post](https://hop.mirror.xyz/AI5fOUR0X_l0mktShDOx3mwr-hsB24gp8GvTWtS-MBc).


The qualified addresses are as follows:

```
0x8ca23135f5bb829becccb327482bcd2417ff5b47
0x78624f62021e9d3808df8d6d8e4701acabcba008
0xaa087281cfd53fbb4305f095d5eb23a732e6b3ff
0xea664909e13134099a08d358ef3888c545e822d3
0x8264746184800a2bc06b76c7b4227556cf94747c
0x4cd3db23e7d069b1a0c9e08a2467dbddeaa52bf9
0xe11b5f63024327e1e686ed7474323166bf7f84c2
0xe5c8b08a3597593835fd7eebd002f0272f8f51ea
0x59b5c603cc4f3bf20818b7b57c2284f9309ab37f
0x54b2cb178a2d5230ac02548fe8597f5aa3758167
```
