### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by saeed8181j** [hop-protocol/hop-airdrop#578]
# Related Addresses

0x086ae6e0df56a9639de3194190628129906d4830
0xd9a7b5ba79fa7135a93d695685e56bf343d06e74
0x2b607a5a3b61f7ff777d2b0a63fe59de6819108b
0x1795e4018eca20c4c3d3ac28112978652f8217f1
0x95c9311599a4f06999dabc009af8574a5350fe29
0x15dc3da3d468ad848c756e9a0cdf8c6b3e6d0aad
0x5ce26eb625d6c9b4dfe68543dfc062fbd132c040
0x24e00a3a094f9e11d4bcd3ca561315e432cf2b31
0xba680cd6fa741ee0593e07ff5a7f5b3f5bbbeb89
0x7356446bb1990db89e53c09f424d9f54ef6ce8b3
0x5130ade0be9ab09dcc495e84da513748125eddd8
0xbb293ab9eed1a955bfaa82e0321f764ef8e6c14b
0x60ae86fe452524df5903fa18d6fc4f13f7a4c900
0x2966a78a24f10a5009b13d351ceaf1dd63d7dac5
0x5966b20c2f6fda0c269893bd99c98c18d098778f
0xeb853284f62271570a33ccab9c04e6f6bdde8d39
0x7b33e8a021455c8d9b6b4296a6630502694740fe
0xafee576c677e9517159f77ea0e59b71c1aed2438
0x7b473a396bdaede02a8b6b63129e3f2a1ff6b384
0xb28ed979919fff344974175c489e904d120b2239
0x794219da8b5eab398b641c41f48a221b8064abee
0x770692acfa46dea21ab59aac273f1cf51b74c40d
0x6edbd6b809ae7b5f18facbaa619b1402b330789d
0x23fef5a44b7446f61e386720e65d9b5ab90f1f2d
0x26fd3fb4961bf43f47f509004087a10fd4b05545
0xf93c45f8ac3e4e7f49cb6998171d6244ac5e3b5b
0x966f5ad9f0f084bee32a39893ada32a4a81863db
0x17e091681cbaac4e0f4372abd05cff4629051cc6
0x7c210e981b3d38e104e635d7b47de4f97b9e170e
0xb0322428180c4f555584e840f2c0e26539e8a682
0x29bbda09a66aaf18c69e654b4c4cb1b3eb1db39e
0x3d445483be834b79a39ad2a5680e0e878f885ac5
0x4750e190c7159b0f4c67d4d60a369070b579da8f
0xdddc11528c91b1255354a75ca4da5414acfed9cb
0x5a530b420822c565822a54848ad764dc069bd2d6
0x12e6d340e69ee3077cdfc292d7bcf255d15caab8
0x5093297f73c84fb0885989ecaf9e2a7abd283a23
0x3d65a5712432172d9a9bf07b6e2edf0a40b20fc8
group2: 
0x0e4179b814061da969cbcb8a4b220616173d12ce
0x804f9f9e167af804691557f017e14f52bd73860b
0x11aa8efa272b4949b5a133417e7489e12ad36856
0xc30c5ec6c843bf628e8d55af316d4b7d503ebc47
0x976bda4eb988dbbaa4c5f7e4264325fb3fc6dc77
0x44fda1a823d927dadacd386b499b00b3f6ed78b9
0xaa0b5a9bd5a6e2810773be49cc432c38b79a3906
0x84f1faf1458e8dab8e0454f8b62305dca75a9ba4
0xd146d497a9192a1e304908766a88f467ce9a2ee9
0xd27aca60b85da90e6fd73505ccf9448bd1223002

Provide a list of related addresses that are currently eligible for the Hop bridge user airdrop. Reports related to the Hop liquidity provider airdrop will not be considered since the liquidity provider airdrop was based on the amount and time liquidity was provided and does not need Sybil resistance.

The list must contain at least 10 eligible addresses at the time of review or it will not be considered. The eligible address list can be found here: https://raw.githubusercontent.com/hop-protocol/hop-airdrop/master/src/data/eligibleAddresses.txt. Reports will be evaluated on a first-come, first-serve basis.

Example:
```
0x0000000000000000000000000000000000000001
0x0000000000000000000000000000000000000002
0x0000000000000000000000000000000000000003
0x0000000000000000000000000000000000000004
```
-->

# Reasoning

All of these addresses have been linked to each other on different dates
Describe how the addresses are related with as much detail as possible.

Example:

All addresses called `swapAndSend` on Polygon between 1:30pm UTC and 2:30pm UTC on January 9th and then called `swapAndSend` on Arbitrum between 13:00pm UTC and 14:00pm UTC on January 13th in the exact same sequence. All addresses also interact with Zapper on Polygon and hold a “Governance Toucan" on Arbitrum.
-->

# Methodology

# Rewards Address

0x18031f7b7A0244dE47784592Ee8D7AE124b7978f

Please provide an address or ENS name that will receive any rewards earned from this submission.

Example:
0x0000000000000000000000000000000000000009
-->

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

It looks like most of those were reported in #524.

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
