### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by Cryptone9** [hop-protocol/hop-airdrop#6]
# Related Addresses

720

Addresses:

Below is a transaction hash for a Disperse.app transaction sending 100 USDC to 720 seperate wallets on Ethereum Network. All wallets then bridge to Optimism using the Optimism bridge and then provide liquidity to the HOP USDC pool. This transaction occurs on September 10th, 2021 and the bridge/liq. provide occurs shortly after.

0x0b9105a01eb1cb956957e10f2c8c3a3cde385bffba6551d9109da20d77e71d7d

# Reasoning

All addresses are linked to "0x35e3564c86bc0b5548a3be3a9a1e71eb1455fad2" from a disperse.app transaction of $72,000 USDC (see above txn. hash). All addresses supplied above qualified to receive a very similar $HOP airdrop.

# Methodology

The methodology taken to discover these addresses was by looking through etherscan completely done manually. The actual Optimism liq. providing transaction can not be found supplied as Optimistic Ethereum history being reset due to their EVM equivalence upgrade. 

# Rewards Address

0x1E094ed9Dfe65b02fD4dd14c046ac6b413d383a2

**Comment by cwhinfrey** [comment]
Spam

**Comment by cwhinfrey** [comment]
Thanks @Cryptone9! We'll review and circle back

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
