### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by wdnm8848** [hop-protocol/hop-airdrop#65]
The following addresses are relevant

0x4FFC3884669E442e5d2F687B2C70504D942ba129
0x6C1bB12D45851E34e63D3aEc1367702A2A01eF9e
0xEaEA403F57CF1d143258AA5f30c53c313dB0bb14
0xD1d399a5AB77CE9F481c7f6cD5AF8b96d0341dbE
0x6B58bC920199eEfc3048A02d113627e6e0226f50
0x620087aa7d016dA502Bed5841B71aee3C4887AC6
0x8cE2410e46b27CebA76d7e8837b0D00b650Fdd42
0xa3FA994C98C37E97a71A440A1725b1571B1Bfb02

0x6A4f118AfE5eEfbEeB1591E516b3c9a8FaBE6026
0x24A85F7af097F169Cfa8CB101D6Dd6dfcA96cab5
0xdC6B8d16a7Bc3b95294d71b42f288B4fe14181Da
0x7b731D3E1B4C6D71925833876af25fdD5C618191
0xA1C4A0A3167AC52a6853477aF1dB4d882Ef5f72c
0x5a09496E9CcA89BA9289125817A5863cA6808B4F
0x9290A2170E18604aAda853e5CEA4F34AAD6D3efb
0x1a447a505919a0BE39291224D4A4b096248A4A8c
0x5765D2e0f02D3479cbB0900FC4e242e46FFf0333
0x64B998A7078C86e444FAcBF26ea220829b636103
0xFaA5EE4dCE2a4e0479F651856D17e9cD93A15c55
0x150453b44018797CEC161Ce9770ACA07652953a3

Reasoning
2021.08.22 Around 15:00, the 0x4FFC3884669E442e5d2F687B2C70504D942ba129 address was transferred to the above address with the same amount of ETH 0.021, and there were frequent transactions on the Ethereum network. There were also transactions on the optimistic network and the same amount of airdrops were obtained on the optimistic airdrop

Methodology
Each address was manually verified

Rewards Address
0x620334a2a05AC5e7c13cD12c4Bb414A71c47EbcE

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

It looks like the report #31 submitted all of these before you.
