### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by tryout21** [hop-protocol/hop-airdrop#67]
# Related Addresses
```
0xcC2531FE5f8F6571A100302B688887aBad002B6B
0x860cDF9ce48Efa6bd8B3C30aF3a41Ef9f6A2A2a4
0xd15170C072b26226668c2C429132Fa98acA0839b
0xBe29df80312adAfAc817915BD907124F40DC1021
0x3E748C1e5dDF0CA19Cd9Ce361760bfEBBF216952
0x00805066382c38a722fFCfF4AC5Ee48Cd5f5Cda6
0xE77170bf38b827ce312e97C4FB08FA48B37CA05A
0x931d98DE83341Eb2ae20f6a4C3cF820Cb66a6e66
0xF9976c00dFD940b1440Db9Ab75C71C8be9805cAb
0xd81520217f1Edb0bcd9774dba706878b0AFc96FD
0xfadEe911FeA33A3900aD3d94f7D4cA7301449862
0x64DF5c3C35F1bf71eE87065647e029661Af4Ff1F
0x4FaF2860d646dDA4B359338cFd1Ed3690fe1d93a
0x4F9aD15974FF2a742fb2Def2485a1841aff37652
0xF9297d31CD7646532e66111Af3C82176AeADCA9e
0x4C52cF65B3B060fFeeC45585DE70798fB705ECBD
0xAE7B3922baA0fc53A56Feb3c5A0D9ae2FA643186
0xF0e0c2e550BE66Ac2D186DcF2BA44625a07aBB72
0x70d8f7017B10954C95Dd6fa7895A293970ba8b0D
0xb0CA2Fa87DE86d22009677235c9447c883900EC7
```

# Reasoning
Eth moved from two main accounts (0xF997......805cAb), (0x931d......66a6e66) to new wallets on Arbitrum from where the eth is bridged and swap and sent back to main wallets and then some of the Eth is sent to a new account on Arbitrum and the cycle is repeated. This has been done over 20 times. All the wallets mentioned above are receiving the airdrop.

All the wallets send Eth back and forth and after completing the bridging task send the Eth back.
example- 0xAE7B3922baA0fc53A56Feb3c5A0D9ae2FA643186 - Eth used for bridging and 0.4eth swap and sent to new wallet and the remaining is sent back to the main wallet (0x931d......66a6e66).

# Methodology

The addresses were found by checking for txs on optimism or arbitrum  with hop.exchange but no prior txs history on Ethereum, Bsc, Polygon. Basically new addresses with no prior use. it was further confirmed as the only task on these wallets was for bridging and and moving Eth to new wallets and not used again.

# Rewards Address

Please provide an address or ENS name that will receive any rewards earned from this submission.
0x3632b44f5bCadc5696453963A16F02C6F7275793

**Comment by tryout21** [comment]
[addresses-converted.pdf](https://github.com/hop-protocol/hop-airdrop/files/8637160/addresses-converted.pdf)

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 1 of these addresses is eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
