### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by sbmunna** [hop-protocol/hop-airdrop#7]
# Related Addresses

# Reasoning

# Methodology

The address is discover from the Link: https://raw.githubusercontent.com/hop-protocol/hop-airdrop/master/src/data/preliminaryAddresses.ts?token=GHSAT0AAAAAABH3XLL73LUVWXLKD5XWQPSMYTUCCRQ

Where the link provide by HOP itself.

# Rewards Address

Please provide an address or ENS name that will receive any rewards earned from this submission.

My Address:
0x5329961Ec34F2e38eF79C39FDc2c7e0B777826E4
-->

**Comment by cwhinfrey** [comment]
Not a Sybil report
