### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by vitalion230** [hop-protocol/hop-airdrop#70]
# Related Addresses

Batch 1
0xE298E3233e3d3522DE05dA0A00f6f2e2c41a5706
0x25F758F4b9AFBf658820F3f00773Ed3c7Bcb4733
0xe882b4303563d2Ed3b7b704054740EbA3B74F5CD
0xf71D1d94b39c7337958e416BaF99dd5a07ad3d83
0xd073E2304AC242B08FD355C68f8b757439d32825
0x1610ed24dCA1B083E8D13799b135459B5F14f0EA
0xc03d6744e442DF5454075124b747A18b8630ba16
0x60eA6Af51ceAd2618783b773CdF7E699C6756EF9
0x77aE8638d18EfA2759482B5738e674884fa9E3d6
0x0e59d6e74a11c74EBAA1667935554FF587eDd034
0xdFEC9f6d7b7920300bc505749F439444a2c13FC3
0x94eA5B3C4b318A5Fad55213cEa0E600Bb267A639
0xcAc0B640c75C5629A57A388D294226e6fd9666f3
0x8ca4a304c2F55C4D9ccd41EEfF70E1468C8f2422
0xcaD36645FACEcBd1B3D872ecb86A82fCd09B7ce6
0xBA9213733a47d7604c791C5a77d020E29356c451

Batch 2
0x13e2F7751e7c4475216e419763EF5BeefCa12F6a
0x050b236c4fe9f58a81303edd3507191AC337B4ff
0x3646832E705a1e4f72037458E575EeA32cb4A147
0x916A04660A3306497B0466471e002d6e3659904D
0x62875C163652500678920F63673Edf72bADebB58
0xEAA81D7FD760f2a9B41C74314A9907c1a3b725a8

Batch 3
0x5B9e3e1a2a12E85e12dA784CDC900cED4B012EEF
0xf4e748BDa212C6D5E190a7bA59758A79beabd1Eb
0xB11D6cAeA39F75f7103E642f384bBB7Fd26C56c7
0x8A60264f0d213b585C684F2BD34C8F9E54A666AB
0xFB385AF3e2C6b7F2aeE9Fef7dE752d9c41008df8
0xa10D011CBc17B3d7B9819b8F8Ea5E0B171536030
0x8A65eeC7F9F55cEA0D2b5C9386A582d744FBF5c1

# Reasoning
Batch 1
Polygon Network main, MATIC transaction chain, also all addresses called swapAndSend on Polygon and then called swapAndSend on Gnosis Chain.

Batch 2 
Transfers on 1-5 MATIC from 0xc03d6744e442df5454075124b747a18b8630ba16. Polygon Network main, MATIC transaction chain, also all addresses called swapAndSend on Polygon and then called swapAndSend on Gnosis Chain.

Batch 3
Transfers on 1-2 MATIC from 0x5B9e3e1a2a12E85e12dA784CDC900cED4B012EEF *also eligible*. Polygon Network main, MATIC transaction chain, also all addresses called swapAndSend on Polygon and then called swapAndSend on Gnosis Chain.

# Methodology

Transactions are monotonous, sybil attacks on the same protocols.

# Rewards Address

0xFB7c1D49e006eaDdff2385c7eF8B0C5Cf49d038A

**Comment by shanefontaine** [comment]
@vitalion230

Thank you for the submission. Can you please provide some more information so that your submission meets this criteria:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered

The report looks promising but needs more evidence in order to be accepted.

**Comment by shanefontaine** [comment]
It looks like all addresses had similar behaviors on the Hop protocol as well:

address | ensName | total | mainnet | arbitrum | optimism | polygon | xdai | totalVolume
-- | -- | -- | -- | -- | -- | -- | -- | --
0xe882b4303563d2ed3b7b704054740eba3b74f5cd |   | 13 | 0 | 0 | 0 | 6 | 7 | 2143.092629
0xd073e2304ac242b08fd355c68f8b757439d32825 |   | 17 | 0 | 0 | 0 | 8 | 9 | 1762.485034
0x13e2f7751e7c4475216e419763ef5beefca12f6a |   | 15 | 0 | 0 | 0 | 8 | 7 | 1676.106736
0xc03d6744e442df5454075124b747a18b8630ba16 |   | 16 | 0 | 0 | 0 | 8 | 8 | 1652.768566
0xf71d1d94b39c7337958e416baf99dd5a07ad3d83 |   | 17 | 0 | 0 | 0 | 9 | 8 | 1603.069186
0x3646832e705a1e4f72037458e575eea32cb4a147 |   | 16 | 0 | 0 | 0 | 7 | 9 | 1586.924177
0xdfec9f6d7b7920300bc505749f439444a2c13fc3 |   | 13 | 0 | 0 | 0 | 7 | 6 | 1497.85864
0x916a04660a3306497b0466471e002d6e3659904d |   | 14 | 0 | 0 | 0 | 7 | 7 | 1424.961077
0x1610ed24dca1b083e8d13799b135459b5f14f0ea |   | 14 | 0 | 0 | 0 | 7 | 7 | 1386.64731
0x050b236c4fe9f58a81303edd3507191ac337b4ff |   | 14 | 0 | 0 | 0 | 7 | 7 | 1353.327493
0x25f758f4b9afbf658820f3f00773ed3c7bcb4733 |   | 12 | 0 | 0 | 0 | 6 | 6 | 1322.473125
0xeaa81d7fd760f2a9b41c74314a9907c1a3b725a8 |   | 12 | 0 | 0 | 0 | 6 | 6 | 1290.103774
0x0e59d6e74a11c74ebaa1667935554ff587edd034 |   | 12 | 0 | 0 | 0 | 6 | 6 | 1274.582129
0x77ae8638d18efa2759482b5738e674884fa9e3d6 |   | 12 | 0 | 0 | 0 | 6 | 6 | 1256.009238
0xe298e3233e3d3522de05da0a00f6f2e2c41a5706 |   | 12 | 0 | 0 | 0 | 6 | 6 | 1133.442709
