### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by marblemonkey** [hop-protocol/hop-airdrop#73]
# Related Addresses

See the attacker addresses below:

0x03d69b3f7ac438be70e34fcccb0180efddff1a24
0x03ed7e6cd5608a0c5fccf384e4c3a648270f68eb
0x0619f79ed6d0a369849875bae160a34fbf154177
0x09b129ce5dc3011ba932e6e912ed6bc90a5124ea
0x0b196e393d5238d6dec662534f34a2ba105bd72a
0x10355d38b362bb2d197aa5c810dd26d4966932ae
0x12f0106d09e461d6d58db65f2cae1e2463820380
0x1326b4e8ac7d8f7e9c7552d00d676167ee0e1b4c
0x15c6d9d60ed5af0feb30a862241874f192f00b50
0x1a44d6e77cdb7cf21ff5e5cf8c98cd8f7a6b3b9f
0x1d7de3238a7c0d390cb82318a224ec668c3b5fe8
0x227882f9be294584889f17c46d54faef409de04f
0x25a0b10b68963d8e889595965f0c93111643aad9
0x2717513d8e46b9c3b547f55988b11bfc7d977959
0x29eb16d56c48fb2a0d0089993e9fe5e52f1b0105
0x3218037e56162a79cf5d38db97222edb4ea6d323
0x3277b60836a09afe7f4171b175bd5605bc3d3e40
0x34a6297890252b74bad0ce0d467d93dc2b089e2d
0x3984c353e77d4eac4b61fc249dbaffc24900dbe8
0x39a925e30a03a0db2596118d0a01ffffdcefb6bf
0x3c2fcb80be10f2f4c0b0bcffe16c90ac49eadede
0x3db90e96170c5402e75d7c12b74b3632444a39df
0x3dd568f76f40f9bb09c4b923a71d724cf6c185e0
0x48b0bcb790186a05046b3be88ac5d608cba260c6
0x4b98d9741aecff489020c67ec55653561b8828e4
0x550b17871502975488758dedd8cf45cfbd1cba70
0x580c3ee8bf0cd7b86d264cae82efabcc0a51a818
0x5be9f2023e49f378dd6aaba7e0634722788a449e
0x5fdc748978bd9d483793766a34cf72f7c01a337b
0x68a0d35ec89683c1dce4536578c300d32b94f75d
0x68c13f79a5c6254b80cfe3f27baba844e32f37fc
0x6e46919a375dc1dc8a484fef6b370b8e9492d32e
0x6ea649fc345f83a8c88b8f8cc3b1c3488aa3ba55
0x6f7d299b43ab1c500d9f87d6eb67a96dc1ed0d91
0x74d296c6c3236b7358321857b31b99868fc2b9fb
0x7b24adf8c37314bf9bf3d2062cae717e5ef73e8a
0x7c4dc502201406509e4e7ee901c5d9cca118ac0a
0x7c5f9306c28713821260da193ca629b62ab748a9
0x7f59a1d5bda3bb073bd926c79f208d1cae655309
0x821d33a9a1650548368e1a8f33d1ea5276a1f415
0x835c0b39f74b9e543d4d1a76623601607398905e
0x83b4e09e794e88db1c21c58a7112d41c300d991e
0x8763f449bb827174f35aa4838aa05477b37aa7d0
0x88e5d41e35ff9fd7e1a134c04f7303a6c52ed86d
0x8b89c507fa2a9fcc15be78fd0d4f610dccb5ba3e
0x8e7f0e64238eeb85ce87a5b19ad5616baba87719
0x8f883e11e581ec0a7ba692da88505c9679da2de1
0x932288a5c0eeb1f642cadd522ad0b65d91fdba9e
0x9b7f912f0fb4b91060c373f01ca43a418d926c97
0x9de27a4a7c9c15743620d6c4923da478c9e12916
0x9f9c63cf707d78332b0da997956d04d1f4033ce5
0xa1ea9afdc7e04fb0b13f0647a0b61f4bce030da5
0xa472b58282f29ecf03f9e878b7f17897b64b3eee
0xa5a05c03039d44b0b0619350c564b466d015399e
0xa5de3cf58ffc5f11d743b3ea1cfa8456d84a41c5
0xacd081310551fd333e1929d8dfcfea8a17c60ee8
0xafd50714ee4e6735899b4e27e36a3e7e7987d0f4
0xbc1b3d152c6a46c3deb07d1c2d853f10b8d4aae7
0xc13cc256f29f26c917781ae8290f593967ae3e9a
0xc213b1d0db3b5c834174451a45af54cd701c2935
0xc3e5ba40b7f7c3630da34fea0743a6b7209924d2
0xc62150d380bb311ba324fafd1a9fca2c6a24b5e5
0xcb3370eb70776d4b751cb4cc7187e9d7ce9be030
0xcfb3bea95b929fb702895c783272316db7b3b8e9
0xd584e950978d64adb09c05aca21d3e5e619c7d02
0xd62826698d5b9671424118202d9be57392f79c84
0xdb289b4175b27269cab6983092a87ec30233c44d
0xdb863729f2ba58928253c2e0421e647b7795135d
0xdc12a0da9cd18fe47dd6b935f0ed3ce8cb2d99e4
0xdeda5a135182309282465306ec83064674a6c7db
0xe50a1d0d8feef792cf5b767b60514cb794450d56
0xe575b870e9e68b948d4b0c97ffbfdf780b71bdc8
0xe6409e1ac20cb3164e029181a817d464b8d73609
0xf08c6968422f4bc0d28973caf800123e21534ed9
0xf3a76ae2b544190068d3bf89360ff0f555ec7a04
0xf4a47b08e071d353f92cca446cebdbe3bebe04e0
0xf60662fb199fd4d0f55cb11aa83e45c5b0e3bcb1
0xfbd3c686a90082a4785899a8048c2c6602d145f4
0xfc1fb6eb81330942d0dec1a53698b2922abca17c
0xfc4fe27b0199a53a6102dcd64892cbc88591f9df
0xfcd3ec2965160ce9567e976b415cc69733071dea
0xfd79a92c6d7d7e6296cf2608119cc3d56f254f3d

# Reasoning

Viewing the attacker addresses on Etherscan reveals a pattern consistent with a sybil attack.
In each case, exactly 125 $MATIC has been sent as LP to Hop protocol on Ethereum mainnet.

The pattern of transactions is consistent across the attacker addresses, and all were done within a short timespan.

The addresses were funded by a single source: 0xca9245A982387e964A8ee0048797beaE5Fda23Ca

# Methodology

Address screening was conducted with the below script:

    import csv

    with open("addressesMetadataAllUsers.csv") as f:
        addresses = csv.reader(f)
        for a in addresses:
            if a[2] == "162.55787188131688":
                print(a[0])

Verification and analysis was conducted via Etherscan.

# Rewards Address

0xEfbC103259B500EBe6408fc7c91535b0e158E22b

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
