### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by marblemonkey** [hop-protocol/hop-airdrop#75]
# Related Addresses

See the below Sybil attacker addresses:

0x0a099cdc45bbe13f1e67517dffea94425f7dd840
0x918537132d008fb2335d386ee6609bb001c598f2
0x2a346244867029914e9de225b2f55d394878a11a
0x8304b8a73a717c07dae64e7cbc46c7c6da16aa58
0x965d291a1bf63f651e3c8622d4fc5cf0cadd132e
0x5996997af40e761b66f1c7d0f4cc2b926bbf3012
0x6f443448ad55334d623ecd80ed8636a579e0862b
0xe5258ce2e378929d021d4c8055e88d5230995109
0x8eff4a07e4d858297fb8bd8cd31ad0b7f8aecace
0xb2b0dfa4eff0dd4ecf9515813578e1f00a88c5c3
0x2e7cb0171dd8d5dee4b0ebef8d6cb153ebf4c82f
0x2240badceb2da228140466de961494d8a0b8cadd
0xc38db3e7693ecdf0caeb11e3943abf021f04548e
0x0dfe6194b56d276d0c3c6d5053b620bb4a92c08e
0xec38705f9aad6fc30c309704c36eeab9ab6fcc5a
0xab5cfc44daef6cfd6d66e68630db57909b19f1c8
0xbe13f504182a27c8284169d27e706b9afa5c8dbf
0xf6eadc1413ac51998ec0560dda5273ecfe4bc7e1
0xabe6f7b20dfad9c745dc3da1df638386f3a12319
0xf53248d71976608a25ca7280f7b87867ce54a142
0xd9333da03191ef48fb562f5f1fc8bd10270761e5
0xad222f8159849995df644c80943b6b6c10721fd8
0xc0fb90b869e6f2e0ecf35147c1400b8ef8eb3c50
0x8aa18f2bdef1145e5a2a298b7401523f4938a541
0x37972bb6737693be96aad82f44ade0305fadf4e8
0x5e00613089214b89ea8de31a6af3e401e0282fcf
0xbef28fc99de76c0cc8ae9b31f6dec69b4cbb202a
0x329f235ee09e8e545d8069faea91ce1cadf79cd6
0x55131bc446be5fbc071f981afbce28ae9cd62514
0xb85e121afa587a4db541d04c54fc7b901be660d6
0xa2c90b1aca96ccaff71e62d78e481a0c0600f235
0x887c39fd2d9005f5b5fabd8ab7b5f73dddfb1462
0x19c33720e258920ad52d6434013adeca67e32663
0xef0f50c7444635c1a21351ff6a51f1966087a9f2
0x99dbe8537d42f6b74730bd93b8160fd2c9d94d23
0xec21c0ae4acf35d316d8387297d977eedc3075dd
0x0c3869e9774b55346afe337faba99485fc8a05b1
0xeb43e1f0895af0e309a279705de58da004e25d4a
0x45be4c0f3853541e7ba83517e1a8b7594e967422
0xd86448674af2dc442e90ec201a35f723c57e399f
0x61bbf5c7c42ffe0495b7063cc66dacb6b61455c2
0xc94af1cdbfce6faf91c1757724d2eb968c189c55
0x5c7b3bc1578b3b76e92b00212ebf93502d3cbfdf
0x687ee9432263061b631b53d943d8876a2a6bb7dd
0xfda949b78264a9aef907a05474ab513aa85af7ca
0xab5731109df0aaf48a7b5f3345ebe5a2dd8e71e4
0x9d7e14fb509834fac0c516a698c0c78d971e4f5a
0x799c425988b560525604794ac4cf830418a9781f
0x68125a88a1e9a1427ab72287abb38b5ee7670a2a
0x5eecc9d7f6ecd7d4fded5f67f0b87db8443abdaa
0x04475de9c9d81a07f48f276e56d8e8b7656aa397
0xd30014ce45f2438c77f4dee427872299781807bc
0x0800250086fb5d94a3be831d339c9006bbc18245
0x2a2e6ea986e3eaae0be3a4787ef7ee104a0ed177
0xf763a4a32a7ada1dffe9d223d166fb087f4134fd
0xa00667bbbed4c17ba46918de4355a6b4ff4677bb
0x3854d5a3116f99bce4e62181049c75caf9132791
0x781718ce11bf62e3e947e790d66c55474b78b070
0x12c6b14d6a903efe5fe0fb4fff6aee3d9468a61c
0x99caad0f049a0de547cb485885b4bde05419bbd4

# Reasoning

The attacker has used Disperse.app to distribute $USDC to 60 different sybil-attacking addresses and then cross the Hop bridge with them. In all cases exactly  2500 USDC has been sent.
The transaction pattern is identical for all attacking addresses

The distribution from Disperse.app may be seen here: https://etherscan.io/tx/0xe9ef935ab4e39c1b7c7ebd5fbc8da2060483aab1c224ef25b700cf4cfcee5e13

# Methodology

The above addresses were retrieved from the destination addresses for this Ethereum transaction: 
https://etherscan.io/tx/0xe9ef935ab4e39c1b7c7ebd5fbc8da2060483aab1c224ef25b700cf4cfcee5e13

All the subject addresses were funded in a single transaction so can be easily verified with the above link

# Rewards Address

0xEfbC103259B500EBe6408fc7c91535b0e158E22b

**Comment by toddm1922** [comment]
Found the same, but these addresses are not still in the eligible addresses file.

**Comment by marblemonkey** [comment]
That's odd because I checked manually on the airdrop preview and saw that they had tokens allocated.
I also can't see them in [eliminatedSybilAttackers.csv](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv)

Maybe these were excluded earlier but not included in the list, and the website was not updated?

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, none of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.
