### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by bbbbbtttttccccc** [hop-protocol/hop-airdrop#99]
# Related Addresses

list1:

```
0x4cd4b247bde11887a7662826d5225b9f5729000b
0x9032ce9549fca3e3b04a75255e185ea9324da4fd
0x728a4a4f8310698f6417400c386322b433d24b0d
0xf78899968a12243f5da0c6a83bc7ce63ac4abdb3
0xf95e9d448a09a7708e00476058752ff61b2d2a42
0x98a60a279b8f8ffc28d0817813377127c38ee841
0xc42d9ce4a49f562e8999650e0ef65dff91a1ac10
0x41259b7c4052ab07d5e23db71210e8ab862cedda
0x4fb06b24ac4b2d8e540400aa52451a5cdbadfaf4
0x4ec899e7ae10a9a93b5244d198c5ec173de80a66
0x6488270124edf61b28fd3d3f2976339f633abf2c
0xc06c66c6096c1ff9545abb2b8463b8c508859897
0x99ed70868f9641983464ccaaa871d33d98c77431
0xbb3f327fd0864003130b9eb57344ef047659320e
0xfcef5b183b460db114a239c9911c8be3b2ca7328
0xd83d51a7e07090a266efe127f3eaf8ae59a85058
0xe2deac58d47b036345f480b4af9f261807b9c4f1
0x9edfc56775e4fa92775aec198ce416ec503e6433
0xe73d22bb2469a449a9807702e2d6e1349dc4d944   
```
list2
```
 0x5705adb7b8e459ac3df98508794e5713a015109b
0xba78e302dfd38bbc54aaafc304ec0b85f81ef8c4
0x1282ebd197c517ceae20edff19b01a5d0d436212
0x0ea43b74bb1bfaf2379e724c68f6320a81a2b1cb
0xe7c024048db19b5dc1a0f496b166d44e9bd368e4
```
 list3
```
 0x1cf111586304761dae4fd67b036a370814e81484
0x1b17f3106c2837dfc9cf0516393472604c234bd8
0x74d2995344d90c2d60e70defcb9bfa5036373f37
0x723C0dCE82FE6312D9094FC236d6dA1AD9d51532
0x124d962237bb20aecb65b9fe3269bf3e99d4ec29
0xbBDd3fD643e1C8F996Eeb7B3f9CAa12510072D06   
```

# Reasoning

  list1

All these addresses have 32-40 tx on polygon.
Time: Dec-01-2021 05:17:58 AM +UTC - Dec-05-2021 01:00:23 AM +UTC 
 Action:
'Transfer matic' - 'paraswap - 0x46c67b6d' - 'Approve usdc' - 'paraswap - 0xa94e78ef' - '0x- 0x415565b0' - 'Approve usdt' - '0x-0x415565b0' - '0x06e75722' - 'apply usdc' - '0x06e75722' - 'Transfer matic' 
Repeatedly trade usdt-usdc, transferring 550-600 MATIC to each other and now having only a few MATICs in the address

list2

All these addresses have 205 tx on polygon.
Time:  before Jan-21-2022
 Action：
‘[Celer Network: cBridge](https://polygonscan.com/address/0x88dcdc47d2f83a99cf0000fdf667a468bb958a78)’ - Jan-20-2022
'Metamask - swap’  - Jan-20-2022 11:18:37 PM +UTC - Jan-20-2022 03:49:09 PM +UTC
‘[0x: Exchange Proxy](https://polygonscan.com/address/0xdef1c0ded9bec7f1a1670819833240f027b25eff)’ - Jan-14-2022
‘[Mapper: USDT Stablecoin](https://polygonscan.com/address/0xc2132d05d31c914a87c6611c10748aeb04b58e8f)’
‘ [xPollinate:](https://polygonscan.com/address/0x6090de2ec76eb1dc3b5d632734415c93c44fd113)’
‘ [Clipper Exchange: Pool](https://polygonscan.com/address/0xd01e3549160c62acabc4d0eb89f67aafa3de8eed)’ - Jan-07-2022 
‘ [Zapper.Fi:](https://polygonscan.com/address/0xf231be40d73a9e73d859955344a4ff74f448df34)’  - Oct-08-2021 
Repeatedly trade usdt-usdc, transferring 0-2 MATIC to each other and now having only a few MATICs in the address

list3
Except for the parent address  ,All these addresses have 3 tx on arbitrum.
Time:  Nov-10-2021 06:37:32 AM +UTC - Nov-10-2021 07:28:45 AM +UTC
 Action:
‘Transfer eth’ - ‘Swap And Send’ - ‘Transfer eth’
Repeatedly trade usdt-usdc, transferring 0.16-0.18 ETH to each other 

The following hash is the list1‘s address mutual transfer matic：

0x4cd4b247bde11887a7662826d5225b9f5729000b
https://polygonscan.com/tx/0xa80697ee00d5e984f6815af9f91c2890acea3e7ffaeb9889e97422ef2a338dd7

0x4a1685e8ebbd6f791d343368b54fa4e2be3debfd
https://polygonscan.com/tx/0x588d1258182ff1c81b589c286f9c8abd6fff90e2bef98812fd50d4b8b3f30123

0x9032ce9549fca3e3b04a75255e185ea9324da4fd
0x728a4a4f8310698f6417400c386322b433d24b0d
https://polygonscan.com/tx/0xd1bd58748a5888d6d73c207df64be56e297bb87af65cf316ae25ea2af89d5179

0x728a4a4f8310698f6417400c386322b433d24b0d
0xf78899968a12243f5da0c6a83bc7ce63ac4abdb3
https://polygonscan.com/tx/0x640e41657bf7dd2602c152d44a70ba26cda0fb26c8ddccc49009345135e3a4ae

0xf78899968a12243f5da0c6a83bc7ce63ac4abdb3
0xf95e9d448a09a7708e00476058752ff61b2d2a42
https://polygonscan.com/tx/0xe3b7b15ae5c7ba149f93808fc45d60cf33705a6800337abc4eba300efaadeabf

0xf95e9d448a09a7708e00476058752ff61b2d2a42
0x98a60a279b8f8ffc28d0817813377127c38ee841
https://polygonscan.com/tx/0xae82f1df87cea1a05b62db695f44ce644e54d3178c9a8e918b5dc4a005e7f99e

0x98a60a279b8f8ffc28d0817813377127c38ee841
0xc42d9ce4a49f562e8999650e0ef65dff91a1ac10
https://polygonscan.com/tx/0x965e08f52b9ca609d674c63d4d19d937c7fc42262fc6d60835713054a61adbcf

0xc42d9ce4a49f562e8999650e0ef65dff91a1ac10
0x41259b7c4052ab07d5e23db71210e8ab862cedda
https://polygonscan.com/tx/0xac95efcbf563b346f999d2aa3ea6fd227b4828c9b870c135d31089978ccf1212

0x41259b7c4052ab07d5e23db71210e8ab862cedda
0x4fb06b24ac4b2d8e540400aa52451a5cdbadfaf4
https://polygonscan.com/tx/0x69bf49cb44df24af1b49a8a8d81555a11de04060e0ebbef5466f6d0b364ac374

0x4fb06b24ac4b2d8e540400aa52451a5cdbadfaf4
0x4ec899e7ae10a9a93b5244d198c5ec173de80a66
https://polygonscan.com/tx/0x596f997ab4b11d96c016b2d3c2835c16d2e63f5e3e170477d613cfdf4d987518
https://polygonscan.com/tx/0x49e30ef932b7dc987335b3e6b6571b1ff450dd5567f9f6c18ac3791d1d66a919

0x4ec899e7ae10a9a93b5244d198c5ec173de80a66
0x6488270124edf61b28fd3d3f2976339f633abf2c
https://polygonscan.com/tx/0xefba82adc63aca93e1486349039f5e8b07ab5599cd3155b3150880b9bfbf429f

0x6488270124edf61b28fd3d3f2976339f633abf2c
0xc06c66c6096c1ff9545abb2b8463b8c508859897
https://polygonscan.com/tx/0xb8831551cc87af7b595dff5d8461045f94debdaf332c250612d1ec8a7bb0b420

0xc06c66c6096c1ff9545abb2b8463b8c508859897
0x99ed70868f9641983464ccaaa871d33d98c77431
https://polygonscan.com/tx/0x70a42877a4e922e31f021b1dca17b3521c66ca7f9c6684aef07c08b41fe05b72

0x99ed70868f9641983464ccaaa871d33d98c77431
0xbb3f327fd0864003130b9eb57344ef047659320e
https://polygonscan.com/tx/0x70a42877a4e922e31f021b1dca17b3521c66ca7f9c6684aef07c08b41fe05b72

0xfcef5b183b460db114a239c9911c8be3b2ca7328
https://polygonscan.com/tx/0x8dff0a958adf7f3f036f2b85ef05e8b313eeed38cf1229fd580f9e4f2be69acd

0xd83d51a7e07090a266efe127f3eaf8ae59a85058
https://polygonscan.com/tx/0x2d3db45660d5254c49bc3958c3dc7ac7fa3bcbaabbd634b88854c55f5c0cfa91

0xe2deac58d47b036345f480b4af9f261807b9c4f1
https://polygonscan.com/tx/0x11d021c910f760fa51269ca372cf991a325e7d61d07420a0f4f4d92e92436be7

0x9edfc56775e4fa92775aec198ce416ec503e6433
https://polygonscan.com/tx/0xa9ef15ed15a16a30b6595952f833e3ab888c30d5a938078a4d1dcb86efa51487

0xe73d22bb2469a449a9807702e2d6e1349dc4d944
https://polygonscan.com/tx/0x5d0103716018c2b5d14a6e9771847c0e25a202b927191670f1cf057dc6ff1611

The following hash is the list2’s address mutual transfer matic：

0xba78e302dfd38bbc54aaafc304ec0b85f81ef8c4
0x1282ebd197c517ceae20edff19b01a5d0d436212
https://polygonscan.com/tx/0xb891470fcc909ef65f18e10a65a405e2ca69df0887ba66b7be0dcf0640670ea7

0x1282ebd197c517ceae20edff19b01a5d0d436212
0x0ea43b74bb1bfaf2379e724c68f6320a81a2b1cb
https://polygonscan.com/tx/0x4602a955785e7ed0515150924575d561fc89ceedff32d0ad45ed17ee97f724fa

0x0ea43b74bb1bfaf2379e724c68f6320a81a2b1cb
0xe7c024048db19b5dc1a0f496b166d44e9bd368e4
https://polygonscan.com/tx/0x656dd951c3c1253363bd956b7702f04daddb1ba7bf1ccef7cd823324a6fa75af

0xe7c024048db19b5dc1a0f496b166d44e9bd368e4
0xba78e302dfd38bbc54aaafc304ec0b85f81ef8c4
https://polygonscan.com/tx/0x820278531678cbe3f4277c09b065930a99b22c7eca2c5bc0ef4e75c510d75431

0xe7c024048db19b5dc1a0f496b166d44e9bd368e4
0x81e52c9b71e0d08e3ee70affc3cf286be7a979b3
https://polygonscan.com/tx/0xfe234eb1882fa384d8848e9e112f8f44100a797d765fb27665f62ccc17de0a71

0x81e52c9b71e0d08e3ee70affc3cf286be7a979b3
0x1ca8d95b60c55e4f7a51750b02eda39ce8ef068e
https://polygonscan.com/tx/0xcb5fa46a2c4f3c863d31ed5ab78f1744eed1d9b9d05ffe56b5d7e66b416be18c

0x1ca8d95b60c55e4f7a51750b02eda39ce8ef068e
0x58017a0c80cd1dde0866e449605455e75dd6b477
https://polygonscan.com/tx/0x3e59a8ca7719bc7c78837ecf51ef36315298b0c80b4f16c61cea930d4acc3d4b

0x58017a0c80cd1dde0866e449605455e75dd6b477
0x1570e5d520b261a64d5004e3cd09533bb7636471
https://polygonscan.com/tx/0xadbf9f78dcb775a69165f6c392d7a37ddaf57ca0923a484611ac8107517c156f

0x1570e5d520b261a64d5004e3cd09533bb7636471
0x92b64df16f1b0df235c252ef0023abf478a69c81
https://polygonscan.com/tx/0x35f2194a0adcdcea0ba15fa6ed3274dd994a8decfbfe1c198097cc56b8799776

0x92b64df16f1b0df235c252ef0023abf478a69c81
0x5705adb7b8e459ac3df98508794e5713a015109b
https://polygonscan.com/tx/0xef7e6a593776bdf743fca6c8bc1532e2f2ccada3ff722d288a20c26ffd614e77

The following hash is the list3's address mutual transfer eth：

0x1cf111586304761dae4fd67b036a370814e81484
0x74d2995344d90c2d60e70defcb9bfa5036373f37
https://arbiscan.io/tx/0xe333dc3eefec557f24585464e9619ebf8938c7cb4e032b23d82450ff53874adb

0x74d2995344d90c2d60e70defcb9bfa5036373f37
0x723c0dce82fe6312d9094fc236d6da1ad9d51532
https://arbiscan.io/tx/0x4167dcfde90d113c3fedffbe68873f94b47b9ed44a22d58de560b9cafaef9a15

0x723c0dce82fe6312d9094fc236d6da1ad9d51532
0x124d962237bb20aecb65b9fe3269bf3e99d4ec29
https://arbiscan.io/tx/0x3f57a93292e2a9b4cb8999e68cdb834c533e45de1450f29629cdefd68e57280a
 0x124d962237bb20aecb65b9fe3269bf3e99d4ec29 0xbbdd3fd643e1c8f996eeb7b3f9caa12510072d06
https://arbiscan.io/tx/0x1f6366a4f7a9f8e475dccef212120c406a5e31e4842318fac4289931012f314d

0x1b17f3106c2837dfc9cf0516393472604c234bd8
0x1cf111586304761dae4fd67b036a370814e81484
https://arbiscan.io/tx/0x6ebf91afced033a1d8babc143704b8768607731f8c7de77130dffec040597816

0x1cf111586304761dae4fd67b036a370814e81484
0x74d2995344d90c2d60e70defcb9bfa5036373f37
https://arbiscan.io/tx/0xe333dc3eefec557f24585464e9619ebf8938c7cb4e032b23d82450ff53874adb

0x74d2995344d90c2d60e70defcb9bfa5036373f37
0x723C0dCE82FE6312D9094FC236d6dA1AD9d51532
https://arbiscan.io/tx/0x4167dcfde90d113c3fedffbe68873f94b47b9ed44a22d58de560b9cafaef9a15

# Methodology

The reported addresses are discovered by building a dataset of addresses that interact with hop and the time they make other transactions, and then using a kind of count on the browser for final confirmation.

# Rewards Address

0xeB5ACdD5CbAdFD6A865A2e9BF76C7755a7518201

**Comment by shanefontaine** [comment]
Thank you for your report.

Unfortunately, only 10 of these addresses are eligible. All eligible addresses are [here](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eligibleAddresses.txt).

Please note that, per the rules, [only the Hop Bridge User token allocations](https://github.com/hop-protocol/hop-airdrop#readme) are taken into consideration for the Sybil attacker submissions and not Hop LPs. Additionally, the submitted addresses _may_ have existed on the list in the past, but someone might have submitted these addresses as a Sybil attacker before you did.

**Comment by shanefontaine** [comment]
Thank you for your submission @bbbbbtttttccccc .

It looks like list1 has no eligible addresses (they were reported in #11). The other two groups are each smaller than size 10, so they will not be considered.
